[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "8da7383d1f26c8e834e0e59e2b223de52c1fb526"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d713a06370827282be37bb496b1c14222429d169cdad7663bd1707fb8635232c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "277106ae9d6061d943beda3486ea7a9b88af1a87"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "436f4d08abf2a9fed255eea74c0146454538368c11944ee3e9bb86bee845c45f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a438ae38effaf979fe4874cc74ef3ed02f1456f8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "869796b371c85f31bd575596d7afffcaae578dff139cdfc230ab1d639268a04c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa1371b6d66319ff235815fe8c075142fe3f24de"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d5bae87931ce88e6bcfae85f391a011d9325e8b22d2416df8199a828033b44c0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1fc6d3e7d093c68d1a147a467965f6bd55002e5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "94f92439fb55977a89fd815782c15ef8222071dd70ad4e34742427faaf556988"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03eeab7c3bfbf49e8ea6eb71d3d40a8c837720bb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b6a9da27949efd41282350ebb0434d111f64af9de76792e6d953a73ffd20644d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f1e49a4a65f1acd2a2970efe8f163ec5d2c17f2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0fef3af70356314e71fc1deb114cec59adcac5bb88e1228b50e1aad1e97ecefb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f0fe59638e2035f222c855dfbdb0bf462313b3e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eac05b29d77b5c47604cb378e125690260ac78ae7981ed4d9bd530ec3872edbd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bba063e57bd3f5b99a3fbb8d6ffdd6289d590fc6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fe769058fb814b3246ce7be8267ed9c9a9148593d39f12c50e92bfc1599c58ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd36221a7ebcf5746eaaec76e14a9fd468f4d2f5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d88eeeb00b48674e48249c992b4cda9d70efc8c49767ae97138a9d97f2c2b612"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da1ee06877344dac587b8730d43d3e3d112d7903"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1a42846c9ed7dcec0a856c613c7f822a747e4149c2b097ee2553a6afad6178e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ece85f40b01967ba2dcea73e790c8633e8710e2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "27abaf1fc80257796fcb66f729c609a6019e9d3b56f4bd5685731e7eb56aed55"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db0861d88abc99384f1b74f25287effb46268e9e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bb3fe35dbdfeb4f96525c42525e58c7f4c5b09aa789237b0cbc85531d5386c69"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9e5a2534c301568337a37f1f5ec3096e990e361"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c4ef933785f649285dd506711873993b0f72ee91a062a85f430244b122d871c6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "641db1d6493c97b3b1d5e9572fddf8bb96d8bb6a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "65a08778f37d39b9f0cc28a173b964ff99193c2a04bc90417123849dcdb52194"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "647b3039a652cc6ec6ef5dd10ace59de43b6f5fa"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1e5146122006ae448676ba98f0d28ddaf1917f49f3490b453fc723677ecfcc00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f3b3368c139d96a79b884c8b2eed84f76eca2b7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2a9cb0fb6ebfe82511e876d279dcd05d4f308fe6ca266536daec9cce74f06b16"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50fb1a5d800f7ec8dfa1b5dff1ca1a96c896e036"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6fa1acc1deceaee17f61b6f5bcf4a59e0cbf4328329bc641afc3e417ca482752"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e71371e7cd4850ea7550c8e01d1a062ad75c3a9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "366e79ea5269714fe328c79b793f238ba50cbb856364705aafce238dce9b03ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e97f58cb1c15215cbc060d520a4764f47cf2ee4d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3d4a1824d07f788429fb3001c56999a7578dadca5b06c7bd99a825e6fd8e3830"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c579e9322198e237e26dcc45b9f30afc1b02e1fd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eff7ebdab0b84e3c851386b062d2910b8a6391c897a907cc3fea344b8a2e7db9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "d2dc2f3a8b51e4f899232d55e062b49b2a1c47e8"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "145e74a8dcb6328793ef20a227beb32c0b14a3a27e9d4edbb06d484e49ef2276"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1948ce9fa9e105d479971d7bb17f4483626f0b7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d2407e2958fafae21edd455409dcc912d063e32c79b8022b9119771f732ca7b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d70b48d45acaba066a63e48d0937d10571a5761"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b365cdb85f1b7630397e29383561cec45ba954eed26dd2a781640cf550d5e7b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22091cf4ae6e7a171867bc5e6ff9ba0c0fb9c408"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5f029d9ddb3ad017b0edaf94da8ffdb18726576b9301c6767cf38cebb4f30f42"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39138a165d896882f369656a5cfe63f6646ab016"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c1a75c5152bfeae4292f8b9268f15090c898201e86f491022c9e2c442b9c7457"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "e30ae8b67af96b7bfa7d6940143be6c6743c82be"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "a282ec58c25fc93ec3ea5c187e842456fac93409d8f7e35f9f3da240ff2d5b0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55ffeb786a8f25dbefdd99831203bacd4bc200d7"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "74bb39f663e96590898814c67adcf84452eda1287e0abe44162521391aa35dd6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f9bb6addb0618012e1bc50d0b0538ed6f10f233"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "61e41bc7dd275215cecb0e698b33d620bd904781d83c891f4a42dd6be914405e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+2/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
