[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "ebc9fc50998f951a9d7b01a39f459b103941ac43"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "29fc9a2a4fe8868db651de5d256dd546d5582a551f32238b0cf95b12396cce34"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be11bda9542294c9714ea12de0dbdb1088fe1ddb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d1934cb9b5a6f8491a7cffce75b7dd95d49cc14bd93e7ab53047c2f805ee5475"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae50a235ee0dd87b75ed604d4365cd951f503291"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d499311cd4c9401bcaba993be41e9c72b8bbbcb033973add9e0a089451b9de8b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05c3f79ab2f1622abb77c89606e1fcd477b37c38"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f2b16dc6b7e344c90b77a610a1f54cf6646dbab213cf1d0a353d6a5f57cc039e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49314dc245994e75a1f7c79642410af10acffb5c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "172121222e72617606cb39088e269abed2e806e825aab9fd04752758aae74620"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "dc5bd15e9cd9cd3eeeb2a6bb0003b931c3aa7c42"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "5606f1d87b73a2f02d8f1ae58583d9297c978b942f0a491895a1cc11401591bd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77ffb69c4f841f1eb21a1862141453f38f2770da"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b35092820e09c7809ee49ccffe59e9127e587e48891467c82aed52e143e691a5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e10829d6b9a020dd23cb1f39fe1b2ac5925578b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b5c12bc5af2fabcc7fc76017a848e3452caa9692adcebbe51e0ea45eeeab9d6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22741161159259e6df73ea22fa991b6c2fd80ade"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a78fb0ae6711ec791cc7bf3876084eba69bfd728c4ba4502f58b603da69cdfef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d672974723f0beceac3d68fd6b8b90d21446570a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "477ad98f51636bfff338df240e5707ecd2edaa86fa32c6f1cee819cf252a1456"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d389313d19c1a78f5777397457ab635a0646f59a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0ccb98a77e6b02c6458d34487154c9cc53360df70a5b010e2038024b05c04900"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32d0899c0febe0dcb01e918e8f07a070babb4e3a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cb97ad8af32384dc8697c15acfba41c657608b9721c8c5009f8c82f187f6b565"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "686d81be81e61aa654e821af5d8c6e9fde9ee99a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9b7222231dc7d0e03e359a4038aaf22eebc14b78856b9f86bcc1ce3253952732"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "776c7204759164ea747ac2bea73e96b51e756938"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e5694a9ee9a2cb62cd5af29ebcb92fe70e5474e8a88e7bf67cb03880fc720a89"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51a27dba07b89e5c166608ffb66253c3c1204925"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c78940156746cb59fa5c50a4bb8f38b811e6b03a8dabed233ef50c9c26bb82b6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30bd4499858e98fbc57ad0119a6c25d15998b873"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eb01470becff7007363f561d293d3d6c4425d2264d45369f91d20a2cdf95c119"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fec383aad416d75e61b04d00affce7dd0dec8ec4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e92f2402e35c7658101ac8d6bc7be06a221cf7047281ce02d3004cfb45e4f075"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a3daf17acdb1603cb3e2a002feff120eb9e9866"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "94a29fbf94c6c98c08107a9f310f4841674e8c56658c6d9897713fe175ed2a30"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5268e2af7f57a02fd6fc075ec3ae705d3f536c44"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c491c9dcfba19901f9086c0c8381676a3414fd525bd5ffc40e26a94ec5bb55b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9cdbcb6c4a1d4b369597f145499735f112f5d1a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fd7e7d32bf09fc7731b171726634cb82e333ad3777dff9d187acc417f897e53a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ceffe6177e71e38fe33f1c36e859af96961d4e0a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "10a597ac9de4c6efd8caf296ac34e3415518644724408932a92dba2bf0eeb79f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.riscv64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "803406205432f4459ea86ce37f0e797eab931bc0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "582989065abf1d6e83b3c7d1301be30a71850c13f5905d5866998c93565fe63f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "04848cfcaf06d028922f8ac1eead64ebfd5baea3"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d59da39d04885c57339c11016bb5793021a517d8e36d3a58cf0288a0cf3a6395"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b5671cc795c4e25285488d7964bdd13cc1065af"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "012820995b77fbd561c278ab2349d6e9372531f3642002286650f5cd3988ec28"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7483599925789cf944fbe8bc261e30de9fcb688b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fb01ca4db9b3ef76f6632ed190382a06757a8e58b5985036f70c86dfd4d7f613"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be614283061ccf2f0134406f4c59414b95937996"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "79eb5f65074ce5e7b13555167c0279c386d795311451dcf2025a5e4a11ee534b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4926a858e6df7d83c8c63976ade3d8f1f28d6fb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d253c6e18f415ecf8cc9222ad27e15108e947dd4fbb551f2694c07bb1b013b5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "f27f1e3c6baf3ef8b9fc0072da578a7a30aefa79"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "ffd61b0c700d5a55e33fa387de59a294176fef851cfda9c24d4d3c873a4f5e1c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "733cefab948d69f2672b163385edc5b22663c021"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "57ad653b4018cc73b5e3f10aa327fa153c86826aefb56d2f89888681dca0cbe1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "651dc074c68ada48cb79ab12afbe4162f7cb31ea"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "02fcbc025bf02689cbfb552146cbe857fe8733c507b9db63cd9ad08c870ac6bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.2+2/LLVM_full.v20.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
