[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "413f94e0be866c1982ce8c52054114d11553aa3b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9f8eca2d56ae0b0f87e01e56c809d0fc92d3ddd0902852507474839a15684677"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87f494f3a8a23da8cd7f1fe0d791e44f6796f8cb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c555f4848ba0cafa32c77bf2a9facb7c644af012cf2b073ec96002e0c0750a37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "492c80e44667ecc564352d676ba72b1ccdfa6945"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "efe358cadec1898b0dc97d48675b159b90a01051249452d3ce843340e4b19e6f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1ef07a843c87a1667012f51b78c037e3a2666d8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1c988032de5f60900319477a834b58c86b7209d9f8cf26df672d22516c43909d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bd75c0024429385bf630883e1b1028e81d2ee19"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b21670a484dce3d699d67866e3a40f6d07a9174818ee4d70920fa6ae8f0208d8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "33c8e03f5763f756a93f01d7d59974022b963351"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "196fc450a044f83b2337eb994d95120f4f968001b11b27022224da12342a8f7b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da774f0c87fed1bb45a4703ce7a40a4869be6688"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "05d90138561912bd659344bfd7b692227180617a4b55c503f9fc9ababa9b5c89"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b1174162dd71856bcd63a1dc02ad9ebe474c315"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fd822628dc759b549d7f47952449d6679f284d1b4978f7470e628e334dfe3e05"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48b4de022b1813013e7a90153314a3bf56ab0260"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d1e18a3385197196e89ea3779ea9c822159e54fd96df8f4c00cb22a4ed3772a2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "831b44ea883d36b71f9ed560745e6f0cda40ead3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "87b6e4c927439b9f0ed592439be7369b26101b9788980f3fe800347081b3dfc6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ed112b8f6e5062895e464e49a4ef43116767b95"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "298095cf8bc9f21c759d25ec75c130784204a4bc512ec2697446b49e33b6d757"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85f852f60d09d9485ac5822ae6b865687e46500c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8050c6042654c80ce823e7cdaa941e85a85c4010e459acdce891c29868a11156"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f30bdb552803999332ee178e61a89c33a868afc7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a43a07fe0a528ddc4ae25f92f08f577fe13b77ee871e65d1f5c17c75f1f314ed"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e7e0689c04045bbf4574481423a697edb5c0719"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2c537775a53d3f4be38e52c604abe2f213d59ca4e39d5e6225e98333f3cd3d14"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcca173ff67d87f7b50a5b99d5f069ef15ad8940"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "19f5603afaa19987c2079b9ecefcb06cf19b21abd65a0a5fd6f364e654dc8c7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75dc26c1db95df8d0f4a98602c22119faf953fab"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "47a6d67a44e1463c2b422545a4b30ece2e7792aa3e78abce97d51c57593b866d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba26ad42f8765309f899946817518ef104b9afc4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "33428006ef6d05e9976a924b538d8a60f53f10ee96fb0bfcc16c3daba7283891"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc7a70df2cd1d279a2a4207c519b5915d18a1915"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "788a0814dbb954949b8269370aa025b7f7b3ae3236e1d407edf49b05e51bcca4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5829db1b39aaad512982927bed4efad0b1dd39d6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "710aef4dd5866527fcc752a62a50dfe244a69ba5f72d74c0dc1137a4c5c3c6a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "560b6257d3dffb65f2c8127d4e746e408fec123e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d413f1796cdd96545afc0203f8e071e7250150b23aebead57d672ea48f439c2a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "cce9592cee2b1fa56a02e05c4710783142fb1866"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "e91b42a49cdf1f60b7c9fe155ff68c9f57539a1a73cd75a41890dd3dcaa75d85"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b2a2a0e350e0a6f34876e9a50347d7b1a988f7e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6e0e85d5519a5a4faeddf83e92d2e88a7414245317a3a03fba51c1835aa8dad2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac072715669546f5282d0a7913eae1f206b7b269"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c6ec94b8070cf241c3df87babe232324590b389110c6ad4db961b7a5a11c7bcf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a7b209873d959179b9b8e3f28a7c59182d88d86"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "acca132650a3a013850aa158e2bf963f767eae881ff9d08f2e3bc25f4948312e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c704566f8059a5327192598f5661ff6f97bb7c8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4909107d46273a6759c40748bc69dc28114c3d1bab7f9d2bded2c3a261ded367"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "113fb31b15bbcec58e53e0af19d8d304f8c4e3b4"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "2b2db165ca4fab431299a5c1b1047b66437f11afea44efedf4f20125904554da"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a2b9446553b95cf063092fcbaba9b273a61ec3b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a819528f16d903a648a718a52a352be5906d8fefd9c6357bce21c7fc1c1d2d8e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e829ef8a2a57c5a834502e7e89dedb8e536a3b0f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8ff62afba3d2d2b930a97f10fb11f09ee1b1a89584347d7305948ae911107170"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+0/LLVM_full.v19.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
