[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "8073d26681313e3bc6911514633c69424de161e4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "f2a1d6bf4cb5677d540c7d197d9fbe9b9a9774df7dcbb1045b66518e87aa6f03"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68114b5e4a01e69c514c55ae7c85ce13bab8c974"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0fea901f284f461f59f92aa0ece2f35a325c17c73441af7ff485b919aa18d0bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "733be75566ab5dbe36113867e5713b7cb538c110"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "551fbd3fb114219cb6a1febe1999c2e7f2bbed88e32da82054c6177908cedc02"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48d2edf495d502defa033ede952b61737c24e40c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "584b4d28d7dd9673a65d72b7ecf81e5596331cef700b36bec993ac09eca57f44"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f675d4b75943d063592a3d88a1e8395f2fd2e0b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "06ffc7f8b4ec1bdf01992667786707367a8f86946287520862c8806a067f60e6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "464cbbab38a1ac523b3a877670d01a71f1a83ecd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7c82f2653b502e7d788ddcd1951be2a1f0d1527b7f9af51fa920bd8db29de769"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aab2aca35eca49de6b6cbc36cd280fabdf9ad01"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "11faf3eb4c5690fe13449b49b5300f7bd851644b445ca4fbbf6abe24e43753de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a20d3d2a5e5df7dff9dc0dd6663ec6a082bc67e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5de995c6bddcba56ee84817c880bff8de2f3a9d5cf855a28e48cbb9b1e0cd3a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c77420c1e43668e743348c9e0af8e11e68eb10b9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e49c82ccfa143026514866c2501623b7dc9ffbe562d8717da57f5bba2c0a272c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8836abf05c68b95996bf453fa223cc7a4d5be57c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d2cbbc87f46042f911d80751caa8f54a776d80ac16ede76d7da358e9f81c8aa5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c82bb81b1ccfa0b9d0a1a55d73369d3adef9185"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "efac7f39e7b876f5b616f513bfddd8b0a9c7b2d4021b0cd9eaf094bdcd9df23b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d59950836ba928662115c75b570f29da60d688f2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3ff5a284706ffbabc3069832826043c74d8eaf2a7ef98c98129537603ac67a5c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41d2fa8c2b392f5a39c6a6e4b933bde8cfcf79fb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0d1bd94a4d7648fa961d1f0d4dcb3de0ceffa505c7183639a46f05e2e1920897"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bca5c31c1fe64695a143cd506cc023e992db0d8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "04debc9aff030e90fdb21204cc15a395f020c38fc915f18d507098573ec740e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d11c82e4408c1053b232b70f7051b650340dac27"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9532c273d0528df5232d388b14783c06081403ac6dc64f052b658bbcc75f977a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77f71dd71514a94a7cfcdcc9a0bcd479f421281c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b2a8bf3e22372ae260a240012cdba19c096172fdda46d85238c3d3b8ff440bf9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bb6a0062b514ea2ab42548371957a9b0cfcef77"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "17073baba064578ff119d1e7ae65e111a592ecf4465c2032aefca060c25f2d56"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94c53d086fb05b89d9ed1bd9f6b31b6837fac117"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cbe87b04cf84e3e8adbd785e6c6efbca2a7ffb04f2b5a62434712919963a5a33"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "570a69e63b2f3e4687816dd41e6a0bf6e7c97ae6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "73d9955c4688eeafa4ade625b924d4d3701184f4881ee5d1fce764b0204d816e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "86b098e0a12a39a740b132580e463b34cc27f563"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7b171ded326bb4b3c76ed2ed40f00537c6eebb68acd17db7bb8b2ae382ca14ff"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6aa880233d64ad201d0713c05c74d570dca3b13"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dd2ed575cca160b8fb4c9c1b60eed5643b53fc68859f7a0b6a978e1c2a05eb77"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "047f53dc3545ffe9e78d96bf09b2fc1f415afca0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b18aacb4b6e440fe4ac774bb5ce60aa97397497f0f7202863c74b48002d1900c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27240deb4e4be4a91403de2700fca43e6c380ca5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e39de84790cd91c831caa26bcd8d8f898865f6091407820132899bb87f72bc25"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "437220233af06eb281a792d0915f084319b08b52"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0ce0039d17b2a91c3a3ad952fc7d0f7f94fdd23bb89f2fa15aa55b3f0c746011"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "a3bb6559a4b80249ce57b08794f1b07b06842d39"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "4b130da38fe548052a7697ba468f060c89aa698b704ea6a3eb4057cbaad3de79"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "925c252f1091d99d06eef8902958c71f09ec20db"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "4c92279097bf790d2c0dde714396c1de336fbdbb5520714abe4ce4ad35229f75"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f938400e03f4f35c10435328b3b301ac8f139bfb"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "be74717f98bbeb742835464d14cc06f8f5639c9dd984bf8d2308df9743c198de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+3/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
