[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45fe9250e679f66e34cff04ea830566649fec909"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "94d70fcba321cac0832b03b6af8bac96e7b04f9be1725c8ccc6afebc607dd01a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6322cce539784f19bc66f356f09d8c8dd473c842"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5a1b6ea896394551da85f7f06bdafc88042a8d82a3d71cb902581c9c7038d87f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42316532c2104ece5f34a60b0f7e038a0ee778d2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a6a32cce909fcdbf9f8f4581fc932bff34bebd30683c419d69a0b637144927e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9a01704ad4586983c7c5caa355dd93c4fc3bae8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "72b1e977fa8dcd422de8f6e181ac30e61e0844a34357aa2277b55aed81848389"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f87aab6e241fa905fb9dde8c44c6d3cb2b30130"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "159c6bdb10f9ceb15100b64c4d22808f5cc50af93dc04d0ba36333f0d40ea9d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9cc20344295f252a10b360474146802528e1e31"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3d017a02062a9edd5ec3a787fed3ec8ea65154967d0305deac6dc3937579c789"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d099f8ff60b42ada74b150d0f2d481a00e2c061f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b8f0e6a827ea11bb75065fc6bb5e8ce10c23aa73f2435249e5d05ae294051907"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07373693438ed65a89948c41149654a9767507fb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "120ba60ad39b8b107f4674ac8eb3beede24610a8491e959127f76bd64bd4a442"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae5d0d44562f1decfa08bf628f6bdb9084a601df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e1f66827c168274ef4af08f26d6a08fe3a35499944927894b5cf0824763a65de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3480abf2a7709eaa005b0770b45bc1ddb01ae7bc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "603176d44958782f2dcc75116b5301f94b4b29a844f69f2993c1e593d8f7c812"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77103d883d81e7c102803a99298ffd738d4f8e32"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5fa8e5141136d5cd166e68d98f7647cbd927b761a7f056708b2ebabc8357c89f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ace38ec9f0bb1714e7a4c68669a16f9212daf24e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "57360dd885c2d3fd07d4957974ad39b08adc6564ce171f14e04149ae7ddb12b9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "717789eb31c0e91c2bda464c824c21c0fc52e671"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "94cf2de3bbea754933716b6b68a04af13aa99c979a123ce7a56640050ed73ffa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e90a67bce768798a7c2e663a49dfc44adaab5b4d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f1906e81e79cfe20fecc0e65a69f671249c1a0ca278e22301fe56678ea66d08f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9545bafddd12e194abc5b56b0cff447980db7677"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d2cb2eccdd8fa6451295048f994b3a4fdbd391f109229ccfaf081e4c6a75fbf0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46e2dcb74c0eea894360c279461773fac472ff91"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "81a8cb09fb34371080d96b04a92607f92422014f3cd3d472d8acb5370eb67d59"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8814555cd688a7453f59e861ef3c0d912eaab5e9"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "13e81c39ab02c1a072ffbc299735da351ce8e1dadc0ab96533c718e709d86cb6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ae5e3c5d41990d9b265d7f77bafa240caf46543"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "0f1f7affe9327bc4b041636baa4017851ee4935e1d76b2c0785c658adb2782bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ef45327a03a17f5a6fb5f3b40e4806101ebffb8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3c6b50dcb3a9d593d6dcc99d412c7c56da429927dd459a879730e6b6a5e098f3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c824bcc715a8d71546689b38f37fe59ea64c04b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "af01a487e9306b7e0378e5e2893a19e66dfabda9dd6d44b03b5902cdf3205766"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25caf321827ac4371aa3aeba0d30af454d8aeb87"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f0c8b53434adf2287f77241cf8c1b0cc52965dcf27aa97d0ed668c7dc534d817"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85f7f049b64eee1fce8265ac11356f43ef91e9ec"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "37fcdf1af5cfa9ae5ad08e94cde50be5b5a9bfc204cf393040360a2459074ea6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "101d5e44889a7c6d7ff42f8c8d787e8ddceeb06a"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "03501fdc23479d0ba8d5dbee3e441932c5f1043837fdf26e32a5d8e8d39c073b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a30330fa8dfbfda88b7ea42cec0de7af0599566"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "bea010f44692f41804497f3215858a6f4cfb653f2dfddaf640f26dfc149094ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51bf87e5886394b2793c943eca05a0c90c26653c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "fbea41416f1e8ee1092b85be942e62b20bc2f4b511fc9c549ec451ed8275d96b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a41b6e6f11278e2c3a4043a6ee1f83e0cac14e6"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0919a96d38e1a711577dac065ebe57274599a434ab98e251c40ebbfd3d5c53c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+0/LLVM_full.v10.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
