[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "3b0642f09a045382a90dc674888a61b2fbc1dc9b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "ca02f3a354e9e736e3c769fd62ee7974332ee21ee756a453d0d1ced6ec343143"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc7fabec69e0aa2c661522f274e9c33e4c6c3fcc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "40d24fdc16902a6f6c7c5bbe64e97d27d904d826c108a9c6fae843aa59908fb5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7d56ffe4979c32ddfa17e70d25344df47c6342c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "49168b9bb1cd2e95fba748e27eb6252e1429749d1a04cfeb153a6ba1de99f7d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b922524f8301ec004e1e470770eafe36c81590d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "89c988cf7bc7f88cffd18ba726b292ad8dd14709cddc3ca6406dd4191b44d97b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f1c8c1ccdfed23b298e9693413dc4ce3bd24414"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "892551dbf524fa347080c64bce39bf56c7ca9f36f879dacfb2b82d7851e4488d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3cadf2c99e82c84898384644cce01c3ef04b461"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "820be375294d5108fd782043c9a877596db5d1179c32653c685eb1e9e0c48dd3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb5fa32ffd33b5444a5dd0e22932bb24572711cb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0f584a52581a3e35657bb9f0cc938ab5c22f7a010dd20b8bdde9d44e6453aad5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e09e75b0aed51bf2028229ece5d5a41807e07d9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e02b29f00cd2b20519506892dda49c5033c8e89030a1b4a3a7c136a67e6fef4c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94981e1f8818ef1eef8fc4af75cbdf7a10142a3d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "23f334132e5272d42d8d86ee365e6da77c5b8858f973dc3fbfd3d83ffc5fa456"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68fb644f3413145885862e8f2872757329a5d60a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d3c3f85476a7ce63067c5db6c2f0a2bd4d48d91065f6888f0aed618d7cb0ec37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1f87ce5021c7c6bb1d7fa71c5dcc085771abbd4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "89b6ec53af00392e0eb1ab9ad03996e344cb3e51bd30b4e7da0bf009c84c1570"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60d31f4bec2fbb6407b0b16389c0f1cacbe9d3c0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1f75360721dc3aa3864772a7c0906394c856a2db217d3b9849901f45cb1e49be"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0baecaec674bfcdfc0c23216e44040c2829c603"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4c026b482a3167f0ecb4bc9496946f7ec13242a7490631ded46338fcbe03dd6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c403f541e64e1b9aeeda5163d4d6019642dae604"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3c84bb65885cd04e7b5b3271344d9cd3846272f728df0aaf4e1a3f7338b3d53f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "236db2938bca9ab66379571b560b757737bae12e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2c4440eaf45e9cb2e3c5c842dc376b29fec589746520142fb4874c4567ac5dc8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5781369c491d8462ca16f4289896dbda8429fca"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "40b54a187ea357a843deff3728384391d09103a5b04e241318a77def3768abad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bae36ad5fc5da39be6158153ed4a3b4bb56626a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9b6974002d542f03c773a2d533489514e98400e8e1f5a53f19d569447a2346ab"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74800163d179a10f4e8368b8b0cbf6c51730eab7"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f8aa4390dd2fc2ed8764a5f9ee6c075639b282335713a48eb4620eca2d1a3012"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1484cc8aeb3f1579e00db74b908460181e50821a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b052635769e5027ab0171cad66e9c204d8af85884155a4d174ce34233ca5dbbb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "152d2ddcd15885d4791471ecd6d63b93bf7f8ebd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2829eb8736fdadf81b3eee17277266038c8fe5d24c1a4a71e01b59944728d5dc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aecf5dfc3b61921d06e51c0ef59fd4ca77493f37"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ec79af37548017d449be0f4438a8ea172b539dabaeb416a3c250c796e71f9324"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "a78d02f9ac5d0e831ce7d10c16bb92dcc1d2d1d9"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "16676e2ccce4007aaacf60ae2c5e10d1d607487cd272671e21b26a8674d33f5c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c59404783f67dff6afdc7d2ac69eba97d5854810"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "afae19253e620f4f9c3de3bd8551e729d10044d28b7d3202fc4a5e80e666b4e7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "095fe872a772d5619f1c769297301b5697d77242"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0fcbc9504606077c4ff1c8488d7210383b42117c4ea84f78e7f276d4e516f3a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78298fca6e7821f5fd093369f707f10e3be8b800"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5d17d6df71439946709c813c3f20946a745561d44422770fba3ddd73e37da456"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2aa3fcc2fb7387205ef03cf5fb1bff2d98642c9d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "47cd2585b7a67a67513364812081336d4234bf9475e78af6e63b4307427c703a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "b3e7970bcb4660bcfcf1c7837615ee91e4a4cf21"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "52462b6caeb83579c7883e4b66c796d6de34072b04a8743a21e12471970189af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d992171ab05efed58a870555a0e4c7ae1b92e8dd"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9b1c2002289d7066d5ae8092fac521cf4b1970f60787510973960f84d29f9e76"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01acf7c1f9b9b7fb492ea25917ef9029b5c1e4f0"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "39242ab3eb0a22bad06e7a868da6104f5f8deec20511a1574ea9562121375b95"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+1/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
