[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37b941a322e9e5c4f1cca873c3ddbd540b93b4e8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "66dfa138c29124e2cf69968090543bbc8ee7b379a1f55d1def81b88f73eed7e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69c39acfc4d1cd9c83d280607180d88c6ab4d51b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4349429b760b136cff7766fca73b831ab0e476282542422357fbf74adfc57306"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71424457da2348390329c002f60a0146a7b87622"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "178f6484c87a9e68cae549c980699bc144fbda72c29eac3c8217ecbb202dd1c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf435d094318d9ebd6b39cee0b66862e6456169a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9a3c337a954a05827f8c399ed7d6bbb94162b0f4f0066e7241345b48c5b3753a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4dc1aa8f6bb36f3ef87ffd8a19c83610ed04d6b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4878521d6441c28cf46085f29c530534cfa71e201ec82308618bc7fc4a52484e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a3a7bfa43b94c5e798b6e9af129e7153b8b3a01"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2bceccdd28bfc2493cef51039f00bf7fd7a11356a7d4d1931d2a08cc7825ab27"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20c4c5234665f441932e94d643cbe8ecc47b69d5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c8d03a684eb77f1d5ce9c71a4492515ffbec8c873e5119542f754df8f16b53c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3731a8b513970d8094c8c46359eac3d1fe1705fa"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "97615bc15044a49b42ae344a26e88d3b3ecddb834758d471b5dd82e38827eb92"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc5652b284a237dae322a0db13c768e60bc96e94"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "538743110d976525eb2992c8f14eadecd927a9013a54205996e87c594c517a29"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70b7e542a8fcc9251651c71b2a99f0e33816d39b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2046ab714fafbb6c6e7aa9527dd13ccbfc2630cbeead865b1d5a595e4a95df6f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c54cf2f743cc426e53ef4f07edb0f7d5d1fcb7e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "13dee75312e7327935064cd3a0178c47a92e07a4dba7db557e6f979ade5b8304"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a7b719816210c00046f6c19aad1a821749e5409"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8591071c92db57432b7f5e93d239954b255ed533f4bf240e8e68157b04aff10e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba371ca2178b679176afbb4d1584facd25df32d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "41cf069a63d990961b31674ea2a959fe9f39673d068b1cd8a3cd400ad509d85c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff8b37afecef7fb3f8e26dbeb27cb2bbb37b817b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6087b08296db8593209d6f86a40414044d7d1539d5b1be9e85f9c5fb0168bbb9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26535cbc04d05ee7ea2fa1ee5f9be868fc0fbbd2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c21583da3953870dd5ff8b2d2813f721dccff83fba0f812f04c0217a9676fd6f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee02d8dfa451950578650b9af6baae900557fb8c"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "270564683568940c2ba2deb5110ccfbb1089b4b20ca040053f3b8b8579f53165"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5d7f3c0c2fb8847e30896b1eb49aedfbe62fcf5"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "1c5e9632cd76f3965170db3bbf63ba908c0849161868418bfbfb4e83791e99a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2e88caf1ed4c8c4599e09564038a5229bf244a9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "64f9dbb82ac7b38b0fb7e781c4cc51faea90fe43a75f97952d385db0292843ce"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93e8fb9168ae980637b81c8101a467ed5bf38151"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "1f5b0e933541974aafadf559d28b74ae2c8a899bc2b094311cea7ad85e6c1ab9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44ef804e8828b4b396a1034e26e74727f363e890"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "95dd1274c4496e503fa22f6b908b1c0e2b77e114966818d5516d36ca05f99a20"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75183e64011ff28c41d5ade4dee5f0d630a53639"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c30d0d598c4ae7362f53c5b9e67f8b34a700734bea9a97fd005e3b2555c604a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f131d222ee3138cd2e0ec8fc4f0dd15e7c76293"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f78cdb5c6bac264a347160cbb7b0fcb57d020a234d3c5702c55f07f341d25c53"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66ad6cfc08473d0d12e6a64a7d9a7c074ec30698"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8ec6386451eeceff90874549719605abafcad645def5bf3ee10eef2731b0b57c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "337a66cada1ae2389a3d47d7dbd1a6eae1c45600"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "85c4d4c2b1d47c9ed90da22ffe6b2e65f4b5bd5b44d117701fa09678f09f2788"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be51f2408745cb3ccffa8b269d1886b1dfac3d8b"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "7022cd91c222792c31d445ae918fcdb14e88eb47da557471b69130161a558816"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "235c9585152b6731f42b90222221c642532ed49e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "62efd14196b217cf460097199118857ddc347a8b103838012758a92888d8fe32"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+2/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
