[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "661c25217956c6e4cd06bf794e6db84cbdac3113"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "841cca45750a419c2ba7b0a7d2c519726cb28aaf8ea067acdbb3a03fe2248ad7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "300d859ef1f891ea6416b3b16ce0332735b391ff"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f10203b06eb7f0ed3891c4871ba3fdd8c5e6f73ca6f492b26a5776d0492630cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20c0795591add48b3e2be69c3677bdcd69ca3ec1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a2135ae20129c5add259907e44db769c4b0b41521bdc279cd2a81adf2b6bec21"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a83cc7aac002569508ac7d460cac52488d1f3be3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b122267b35488e8737f64db1651b09108a423139f6828af9a690121d116e0cc2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6800c1abce704475e3b6f380f8512d906eb37251"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "de66d67b43675650896a6d43f9135cb09e7f30115288ff564a953480f2b46842"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f87d875ebfc6f88af652f120c6b18ba420f09ae"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d5453ac08cf030de9b7a0532e68845bc4f59e119f2344e2fc071d36dec5bf2fb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba3dd871320f6e3a9667f74bc3823363d0406b5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0449a74c37c0322fb19be6147f048ec525aa3e2b455a041c5a837f73be84531a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc2edaa566cb096ebf755422b3a7dea5fcf6bdfa"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ec3dd50693aa668c1026b90a346ac411cae6e609f36b5b31e8ff943443f6d530"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f30c56759ed4861946efd7c88fd8927c8e2a5cb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "69207611ad76119ca31e5ddde9e0f89337aa912298a58892f7987d96efec2ae6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad8229811eb7b0f8ee628ed2e33c1cf876cb5957"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fff81a410d73051a0ea55ac15578b9113f8fb5f01232eb545671e26f678ae3e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47f7806df1dbec102a09a2ccde83c93247ceeae0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2bed8c91001d0837437a5949119c0c9d8e164fa2abc3833eddead07c771e0e51"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12cf70a88d32c22cae94d5bec1a350876e13f102"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "209d898079ceb4cf5031451e4d64f4a1757426e4b8e24aa377e1a0aa788e0dfb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc178552b54a94c442201b1bb3b8989e12849ea5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7527b0eb4f9f5bf8c41e8b8e2d15209376dcb5ca1f1da92556aca1a9a4f4a873"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ad62cbf46b9048f7f516059beee48c0efbedf0a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c6a9401b15190740a9e681c5d35d367728bfb36fc6dea0a3e7eb8814dc152cb6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebab643d2d42d8483709ea1cccf7d9e47874d9a3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ef0bc7432a01df1414714ca5645687ac9828a619ea0dcf264c33fc5bdf105c0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b517cd4438c3c57a01648867778764610d0f4136"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ab40b3b0654894a8de638b0784de361c44e46fe82f7518aa30b8efc2605253eb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba42a2b4c0a2210fbea1314ab2d23caf5fcb49b3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "602d36832665beb05720b070f43b4301c96f4ee15dde982713a8757f503442d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eca42008341e2a14a1c0362eea80930cc1c4d094"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "36544251ab26d8cb0c433f5e2e0ee384e46ae4e687575d14cbda49b3f330bc46"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca1fbc6c647fd4f80927de1d5dc4ebbc3c783dab"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "19ca632dc904f62539139955c9399bfb708599a583541963bf6963c73b83d3cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78c3e172e3eae8448b054be747ef5d11c659a460"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "89fe94a7e9fa250e194315e3242cb0341fc2f200e8fd9532b047563936616ba9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45f838791b6af85e4371fca4b1ebaf963a0d18bf"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e84639b37abe0bf64ed5098c74f53a2eaba1305a1cb604dfa97822be346c6a6a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "dfe291f6ee95d887385446211f8219610c699bb4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "e093e9454c0c58ff94b7f5703640bd476dc7464feca5d49b340879cde63bfac6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20857dede03dd6fcd5b2d4b087aadd07a3ba1304"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d80b988826fedae4fca75568b2960a834235dd6e38f85c60b1e8f770dcaab26a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e9c9290c2c22585ea0397617d7db1c4d32f116a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ad77149b492f36e5a10c81acd6ac6887431df6398f099af0673f90369ec0eab4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f699e1e96596e4962a2994360baee0efc44be56b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3340784ae50be76d6433a30a35fe45aa386ba4355e53dc281fce686acbed6e17"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "decb64ae60b34978cfb024931f8da3b30d0486aa"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7869f9b8b32fd51f307c8ca2701a098d305e12695965cea137eac6caf7724cca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "86beb4a30627fc272e65c778d185c0527ede534a"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "7e1bf99f39097ffccb331eba5472e48715928fdf1e7f5463780bdd8a38990a6a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cab63333f2be0f126dbe7e821b474154ff2bec39"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "74ffa366c208bd2afc63b7f8f00b8d4c17ea85cea677ddd9d6ebce95eabbf20d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dba1ba388a0048a24be4228f681f245c4aebbe71"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0ae2f102ea930bd8dc407fd4e1b9163f8fb297b1688f14a6a1c6f411f70af531"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
