[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "73cf77095beacd1ad04534c8e39b4503bdc5b046"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "fac775fe908ba1581de5092989c93dd159e883f1bd346841159c67b79b679227"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef2410457ac1f618217b9b0c554589bb660b8df5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1d2d1c8f65771ffcab04887d665fe0122efea913d0a3729b30df146ea7173c69"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02d17a77b8c21f0da5e770b5273f3e768065bde5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b2b49ea18a1194420697a426b38e4d5747b9b0d2369c40b7e6a8d00d70691ee3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66fda2c9472ba6505e01b336ba4173c186762abd"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3a31a0cccb22daa07269d4516aeabf404e6e390c90e9068e00fa7610139deb7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d27dfcbba04607a0506946b8456e29da87924160"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a12ec0f70bf526d8535b14d9ee74ffa04a55e647c2c8524677205ff475cd5c64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5b54d4cf41fcd415304e6e951578d7fbd77a49f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cdf8781d20ca89f8d80b780a6825a70481556a6e8a50f8e71665281d135330bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f719b41fb4a627062b2def058f0f8934cbe69237"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c51794f7f5febd8da6ce8c819d7a68ea729e58d0f535ad023121b8cb64aa1269"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7988d60c75eee596040d39981420afe33798e61"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "29efd696f80cd0015f0a5ede63c6f985ca2d59b8bf8255f3e3e176df067143d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0baa67d7e45618bafffce65411222c42eb9407b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1f744d2e8bfef7fb896a1ea5b7f8f52aae0ff6d14fc92cf160cc842ac7e3a34d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9880a67bb803a44cb4cc463226c79c068f401c1b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cb9aecca2282fe55d9763157ab7d8330cca9836f6a80a7e4d558fe9f2ee907cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1265fd0443dbfc87e4f270214b8e4864d4bffb22"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "883f1c093896a87e78d79ebfdc0a96ead8ccee7bc3ffd3cf87cdab3dd1ffd692"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "089d998cf6ef418799ad99a2cf39708b3bdde4c6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a2a94c920dc3fb1b0eb30798eca7aa77ef6cfc3d6b212591f88595b83e05ef23"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8431dfe79e0dde42e71e7894b397696c71427e8b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "27c6ebb96cf198caaff8ceef581c957fb7486890d25e8f108f3e1f605ebc0d1a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3782e4a5a58f8328316d06f0043a417cf887b332"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e1d54cfd163c2a442f351847624179699179eaee45a2a9d174222e477c3c6be6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba665fafb5220f5344f4870d2d8c65f9ee10c856"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ee4999f90736e08997e01a1fa5de68e3e1724132ae73f0a7befe8b119865d578"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "399970ce23e00ca95579fb27530c21a409b96885"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9c36283af7a2f15053f54cf54be78db04fd2a54d01c0130f3945021fedaa92dc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52e99931fd352798f7bffe351e67b6c207de7a7e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "187519fcc9d977a45e5b2adafc3a9d59d54a43f05e43c7d0f7012b077e8ce385"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68961ed515210bb8ab813b66123b4e76eb44cac2"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "bbeea820e6b1042153211900cdd5c0421cf3a856069a2432aad492b8b01a1d2d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efe0b512f006062e144f1e3033a01535c170bcb8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8cede99d2b3418657f4b0208541bc9e1779da29ff61168957f50a13ee49148b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71b593cfc3e8620a2aafa0655e689d8a13e4cee7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b9868b2abd60859eced061c2cc95b0009cd989a76bc4f1b08d3e0cc081cee85a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13e80397e9fd1cd52ca11fbdee9ff7447a3eb88b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "81c23631471932c0d718b79634f96f79b317882886c2a28753f9c58d71862e76"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "43c5f915b23163ac6d25e7754f68cfc1ff50d375"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "db6106e6a5e6debe6ff366da137baa71954a26361a0008183533b5757f05db57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26628801de601abb9d9782d7d134cd5d32e1a63b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c3aa12479236b0a9bc4c81a4520dadf470a883fbbda193551b6228b3e5eea29"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f2360be2c9c10c33d49eebc75d61a874d4ed029"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "95320655ee88b5f0ed8b341dea6402d8db981aafa9811f40ad03ef5bf083dbaa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5fa475a599e999cc211e7ceb73f8b2b9d6bd2b3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f03deb5b342f6bb0abd955476f896fa62d898631c2ee45550050f5c857bba826"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a414f313d09c28c048e3e3082e77ebc2087fb305"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c4b0f8cd66cb2a97c0147d77a7d93d8e21c64fc4fbff5932ae8dcc515bb3b749"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "5c81f68d9daca8976b42f108a8c9c6cf5a85382c"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "02a531ed839ebadda86ce8a88a330ab3112afef9c7d4388560c01ae94b7fba52"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f5a7624193488ca1e538cc0fa4ca8a3656232a1"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "2321d91e22016833391f484f2cecc0f3629c3af818556bf79a79390bf4cfaa01"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6132ea3ecd5a32c650709a7bfd5d57f007b53fcf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8b341a3283c8e5f6e5b8919e766c1da3fe48e21e3becda45bbc631fb31752056"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+4/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
