[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "d5e898d8101742037e8b7d8051da9f3fd1bf6f06"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "0d1c310c4dcfb6373a9e4a497da114bc7f9952dca4ebcc621300a63e91529f9e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1df5b4b74180484a242430a6d6037578b8244f65"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fd7720fb5080be81367456cda42e907036fa9781061b158290de803f0698475a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "894f9cffa17bcec9fa58f25eda876c0ed65fb73e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4176bcfb2d39daeece9b5ff2c5e9cee4a7fad6ad72e6b12352eeb583d7b1ab08"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20b4fb5ddc6f8c2062357552fd6723f56468f9e5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fbe0a47aa0e0570180662e8fb931d3e52971e7b5eb615cfcc52ddfe0d998b80f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10dd0d51037aaf321ec79293a7b9db9be8b93c9c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c2569cf6eb60f85d37ed6806a6af4911e4fea0168d1c5c90ca7af5b93511654b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "309cd054bf05cf29b2dfdc061710e80bf49bc424"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "45a113975c6091ae54577d30c33867039c0bee198b2de505795e1015a0e71400"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de72cba17347a351dd05c3918d71af8387fdaf4e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7eccd4059d1bde7082326e36559dcb6f9e9a07b8aea59b48cff8d6018c52c62e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed99159e8b1a1c286b51f1f0c8e775028eddd3c7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "872197045eacbdd33d54d49d42b95a2f078d255719592af89f894b032a529683"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a384d90700597763f5b37c61c3de2a452bd26070"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a52b22682cca78c7b089205607b93598a139ce754def54d65b8a43cd862e9c05"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "503fe779d77f474f548940d5558be4a6a38e319e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "19647d0c4d10b5fd34fe66a9361efdb67cbf40596c6aaec27b972cdd3996bfb7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a3d6961bd2b4ea996ea05a42f334db06753e17d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "abe31ee1f47b5fc72e777560c968547641f9bf1e57f138223e4db8eee625d6f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93fe5c6bf621a0c4db7f629550f63f993f25164d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d5bdeb7273af56db3aa327ccfe0eb6321fb50db0354946b6f1aa99e61142c0fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f806bff9fbbdaaa10dfcb7f222da878482351886"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9e7deebcff09ea7eb2f2232b09e49d018a69b43869bf168cbfd119854ebbf3dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e58fd330fa5d5173dc35641659a6fde245ff25fd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b319398c0113cbdc92d4e4b3988c8bce3f59025c74614b90e3f6bbbcc69be0d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c24186612b432ed1df1ac079faab40d4b23ecff"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c0ab56d9503db769f15718cdab662b1390ca0ed6c83596ace6959d4d3bc042af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35e5383ac66a67aac65d082b39eeda641e631922"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "414855da0d8730e6c384a6bc587c619043af203fa4e34086d3b100d85fe17339"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93e475b6e58bea3a09c68d4c1266aa426a3c9e5c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7306afe62b7de54cbbd7cc8ba778a2595540d5db81181a34c3d93d3990fae43f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c0454afb1863640cd87d0f93b971c891a596dd5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f1e28fd93db4174bf3dd524544f2086a6329b27580294f04bcbfd526b9420f91"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "820a828cd2bbd7ce2ef9d1ad92b0321525408e92"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8d531f326b15ed4f0fa7b48e2cbfccf423ee4f6079ebfed9fea434f92db19347"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "559462e27f21a40be42f758045b3a54c05e487e4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "91af6fcdee3625d2bd8e87538e1a225a5b857c66f65811ec66cb612949efe0af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a691f6edb216ad633aeeaeab447585da8e0b16fe"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aab7348cda32f739abe0411c02c3f712f6f044a84464cef94d2364dddddc6521"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3068ef66a3608877e74cc0d0f15fbd75ba7c3b23"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "974be387c31f60136a01082fff69974c012ca9ca5cf099488d5e60c98b422cad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6064c9c26cdfa1c65917190a95c2ffb0526c4661"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "019b4821fc34c425dad33e3674c0ab51441369cf88e46dd137befab0300cd9b4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27e27a1f2674796477cef6f0d1360b0a4d752bd3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9cfaafbfa51d80010f86dec66b90552f80919a5dfd4c8b3f4e225f2e91f46e3a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "7af505fa75ea50310bbf1d50e80d134f19046ab5"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "d00d4d7f63c578370ffa41e5914a598c53d5b5f390483b47497516e0cacd2875"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e842fba3859afad7535d12af0c45c8ed12915361"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0d88092255463c82124bfed4443272b03b5851fb61512b9000329a6e49d2bf9d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1187db0b0c337349df1685fea2afaebd44e402cf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b9c9eceef29e493e9864c188c12bd2e7d674618733d3b946358c49d949e4bf67"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+2/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
