[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "d0d876671b4b30c34a6d03d70c3ef156264ce793"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a67e299a6c0ac45af372427d5762903b5890d6c1f0ef9ca34c0054a95b06855e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bca2524775600aaa9c7b46bd31108e8019b1cae"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "23e979de69cac498429e06895592e5c3b536fc5f7129f1aa66df45e6dcfa9f16"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1ca5ea38f0d5288562ba6e576ac5197a762fc64"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "957d90d02aa69e0d21950f0eefd11f7dd6037c705e735d7bc1d25d77619d33fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04f0b7931b7e3aac509052292d3fb374c077b52c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "92c48aa311d6d3f76aa59765522f3c67713ed63ee003711893425bd40820defa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42931d9a851ae84611b3a4e581a720523ec100fa"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c81a5c600484a706cf26f9c7549651af173aa64a20b1f3369573dda236d2d043"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32dc6a86938adce6964e98e75c248daa28560d27"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d6fcd94eb5adfa260fdf4c4e4d9d6197d30ec245ce0254ac525b33070fac208a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c94570f53187501a66da6031af4401c3b5ddeea8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "df771d13159ea31aec8be5195a4bf52e29cb997eea007c776f0330100e20b7f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d8a46650dc14955d59c9ee4a18897519716566a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9756a1f1e37f6776691fe6298abd6865b9c9aa7a4a762f9d204b764fdbe9b756"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14872326944d8c5a39380fadc3901a92739639cf"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5fc54443b2901fdec0603e5c7d06a3aee33442e7ff78b855413d11944f9f4bdd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27712262855c562e716598664ff702e60297bd69"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9be51fa032a9a18257c63bb24f75572642d0b25ea96f6e9526c5f304d31ac9e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "497bf7501e030ae31a29adaf84cb8b0515cd1adb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9333a27ef18d416ed6b30a0afa3d5b29ea206439cb8e07b492de101a6c6c85e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "696a209582d6fa77fbaa9b4b8d5905b59ed34151"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f5b1771c048f7648d75b0f5c52f897a52e65d7a485d8acf6240ff9e5ffe50a4e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e7592b9dd14954cb7a7498843721fa111434486"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e9a205d66aca9ac0a7e288a3980b14dab718f48cd08d00dc572ff0cb667c486f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a1c61e2dfe91e8344584be983746d746cdb9e0b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c336fb1c7ca254fc6794c165a795bc8459f9b085ee2a077a803e60c573220ad2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f36197a274406436971a0230a443f1d66f22545"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b0641daf5b526f7ad0da733d9c1de4928e683bc654f4a60792870ab4734c23d6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "359c7202e3adfcf653e0616afb707c2ecc3cb8e1"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a4a5954d59a967a606e950cfaf96dd51ff096d1ddb1d0df4919751697934704d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e63bdde9f723376aee663bb9ff66c55be04329ea"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "186d5ad7d25325af12f92f6c237e96f9f31aff48ec40e3258ef4724fb7857247"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7699446fcadbfef15158c0ef69598ea5f42ab678"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6b637f4636df20458b8972e29da39b68e41ce0c650318e6c7aa4b4fd0f1d72ea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40f7a23bda33608f031e9c25ef21a53fa6052336"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "66342ada4d3e2b5263c998e72969f349428699446ab7e6dba58e3792668d409f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "046bee10a817d715be1e96a78c08135eeefdd411"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "053f01b01ac37fb113fe4a912fa03f0be977330e057063c0b001d72fc8f58fc5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fb8f6a94697724ee841cfe3d3d5bd8f6ed7fee5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "50fe3e1170f0b75f8faddb9b065d5c4588dc270ad963ce4c8b542732ad4dabd2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61453e9cc5fe95ff8b5d01b46ee803c9f65e1ccc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b5fead448f9ee9d14f67a93ea4e5d8a4a7117966d1c723abf5dc94dd4408438d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7263a97536c39cfd2deaa02c090485544a15b5c3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0a83af01172740875bbff9014b2b49aaa031ceca83401d2667e17537c38d5251"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fa3c11d4e5c67263fb008ae4434b2a0349ac45f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0b4d31099406339e534dd4a720e284a84d3a7f47d6f7e69257b9b3048c403da1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "25fa5a9e9b88828a263932830a0eab4eeab1e63c"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "35a6280bde1e75acaeb8a103f76b4f2ab7f8eb8dd52c50c8fabfd175394a5a6d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "527c2d507b541e8eda618d522510d76aecc4763f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6a7a9c31a5a77138f0792a3f2beef1107f120df0681645f129f07b7f5da61a07"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9163a0364bc7f36510e16e4bf8d9363c9327528e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7067c9be10769d6621267bcf0b080e4d45d11c1f840ea687cdbeb5e7afeb6cf5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+6/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
