[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "d8b3a19bd058c1fe50aa891fd251de572c87f69f"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "86b70581ba6716d0527f6d5f5e44bd6dc06f4efe13093976f024f36a4dc2d0f7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b303739fbc836d3aba91b020c68a0f028ad2405"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "be9e161047d503c569ab4fe28a1b4a7ba1a5f5b3dd92f418b1e1a278f565b749"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "780e2024c1b542d9939d328eb6c63166fb9df708"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "65be111e85b81717121689f7fdf312be755946ec06ca50187e59c6a0fc7dd04f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4dc25c5896f9ddd9f3b241c450599d3d378aac9f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5882c5b38c3d4a04ea9d2134ebe8a203e3e5ee9891a59ec61888836ce19f03e5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74cc8e540c5d62b49a8f10c2f70afa1875512bbf"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c97452acab48ebeac385e86b99ca3f60755bed704bfc12e5eacd033825552551"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e70c4d4fd22a8ebc4dca820857923500c7a19393"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6a814c0f7e4eb6d299ca568ee720bf18d72b369f63bfeda3d76cbadc492fba21"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bb53b5c2f14e1f83c2d042ff9d5c961f69aa4ba"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "60082dbb3e37eec7c2d80ea4da66f0a510bb51fe3e48f0336c910933f812f057"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c24504a1eb02a0e988aba2330ed9c9ea67d1ad5f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c483d907d1c1c3a33176d7c0dcd4e4b2d61a03721b20f0d6adba246e66736551"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97b4ed3fa0d8184f0688b3a4437f092fac86f1b0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8ad70e8e2b10705cca8789d51a001b79dd8d3fd0f9ddb3c6a5e09707b1c40482"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "477e76f837f0b4c3f82e36c72707d5f803194759"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9a1f2389bb3e7384fb32a03d9e8e2fcbe0e5b17263542a416ca9379f67e7ebb6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9692eb763e279cea62ce231ecf5b807d492b5678"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "643aaa3b011aa3f72db88fb49a207738d631520bcf7b353471a853eb4c2def33"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4893e2a16377460cc3ea669438a26480ed3deab"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3aeaa984fee5f3ca0214e98b0948b8795c9fd7fa40fba980a8bae71c717976b4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98f94f97c65c10ca60f212c9991e192e4094137b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f15f3573f6839d030e275e9b45936d056b6569b48906d4a97d995b7f9ad96690"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0126e0f0e325f73b34f35d0f2b8eae6c233a8ee9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eb36ee93a59f031f28962652a28ef65354ca483b8e6fea9a5aa4e76ff0610ce4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "688c549917800c4f9ad9a36a2be2690dde426df1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ff09217c07052049846b7202b78e1ed11743a05c033bf70558ef93ecd86b07fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45456e680e196fecc45c3b4ca482483f7725af71"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b53d2717af6d9a5fc75bdcf805b9120716e2f3652542d5eb63db12fb6158c17a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "280645d59ea8879f065f67da36e94ae31c413072"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "99218dbe01b11f4dee1e4d5c15418670ac4ebc6f0e672fd648e7f5d5e6705234"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ef344d6b120089a11962c13770c9b2b1678dddf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b2bf2ffa540e686a7941c7da97b9f2ccd58c3329418d3bf06abb5f33583f1513"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c83724d360612feacbe66b349d23dffcabea9e7a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "4981f18c68a47f40a588a8c6f9b8c7cbced1c2a701f7cfa603c9c42bd9f659e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2001db156693d308f47a9eb7951e29f865d6f4ce"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d793976febf8413306400002b4f166ae2fe6f98c1cf5b21331e147ff4cece71a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2966f9932e8089c511ada6386a3aee844b62eb97"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ef608d08cddb1c103b2c0c813dd5c2c7847b52e7588d51fbb85d7b66404550a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "e00c4bff230ddc7a1e9b560627952f19592343bb"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "3fd0cacaadb4dcf9894a79d0497ceb376039e2befe62f4361491203aac197dc8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1d77525a365851049825e45fe95f3828dfe330a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ece3f3b7a39c0ae457156d0f8d12ae96eed2a0a2a119c7de8da0645b6f028d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7aadb6053051b8e17b64204aafef899083e0182"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "970a82bf1f12775edb6a1153de7b0f4ced1e0ea7c3366d8260007b315743af10"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f7a9a188bcdb3fdf5a188dd7c95a6b0158cf557"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3309e13dcc179ac274fb05703c1fb928c21075f8155fb6abb73d134e8461c369"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24f0dad48476b8f71eabd8e93ed67094ad16a411"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b58d627a773070b03f8e7a6b5ee47b60f7eba1d72b0669ebd32a436e266234ab"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "843c966cf126348fecc80db574346db2002fa2b9"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "958b300ee2efcb0561d46ece179c92ce2bd063733057740ccf579b6971107d26"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a85622c15d52d0405765193f85b92c5d8fd62b3f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "5f9ed8fdb7cacd1068d6a23fa5708fb4974d3202b74a6bb484cb6e353fd3aae1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c9f6a180dd40f9cc5e19c3b6bdb2af1603addca"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b08d40d7ee8466863f178d49a0b3dbf134f4f5dd1e4c55570fa06977f0296e3c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.0+0/LLVM_full.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
