[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "ea7964e0b18b3b99b2d179cf38a20aa5bd9a94da"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "0c4b2e862e1bdad21520871f58e12bf8eb45345d3f1b99804cfc04771890ad27"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11a5a8d7a8c1e9ccf501a3910fed802b68cb3276"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "697c419988f4758b586e1a277d38cfbfe8a01009e5bfde7b3bf532323a92237a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d35214b441567c30fd5aaf88a2cd9609d81b6d5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4d86d0fcca29f9cd5b89e18d798a436c30c2374d1d94e253e2ddbb3db11b2367"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf7cfb76739f4f87d41afb5694383f908c7131c2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a5e440cbb9370b9910cf55caad157e1aaf2eee51ec878c0efd7c1f21d825ec4f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bdf43031b0c4f11c438a238be79500ee04a1c41"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "10b54c38016179adf5478949c92f9d7a57dcd2dfbba173046548950c915f44fb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56ddce5e0694fa31f29f297058bcd3138193d4f3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6923982a6ba7ae18b807c5228cbf963d362ef2c0d5f92a49478ffaca97e40cd2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac72760facebf44774fe7d929d65cff371d82ad7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c89472928fb929957bee33d839e4678da8adf85f1d8202b347c2b0803fda2ff7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b91298cb8f203a758b338b4d2bcd4ac6562c2d26"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fd92a1dd55ae66195d7afd2261b508dc95ef7f03dd7ce088d5e18ec8c00b0207"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82ff15b400e3ac169c1ba88cdb6ce44a2af9e5db"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0b5ddebdaaebb4a211752d4429fa7b2a60071203447911d3490ca29542dc81b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1e7b6a1ad6cd2f56df77da5ed021adeb7fbc1b2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "52f4eadb7dc33f99b42375c3ecb199d3920f6cfcf25dda35c38c3063ef005a2e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8eaaa44a83feba1325673dbdda113d9d27b18e54"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "48aa61a365f8614f43756dc1e2938d49cd238d7a8f2de4a89ebf17f0f899e93d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f2379e2ec0c466a03366d2a8b90586ebc81df74"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "46b5e8fb7293aecb19c7e0cef596f288868d7411c050e7ca2f7c123c8eb11acd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94ef0454d6170ae2c32227432363569188bc15f3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "07c7bdf810e6473009f1cdfb850c9b9fe7c9792294c44b170222ef56158d39bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "360e75281e56e8bb8199df116b90f6bb8999f4c8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e2933575faef36603e1cafe213e9e9b797be4a4911bdc573f85b6c8b1e2babd1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26e60fa2b8d37d692a7d4ae72c1df57774481b15"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a4fff30c844227ceb1fb5a4ed6e13f51d80de779be5245b42fdbdec43620f2c4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5981a65435ec66539dd3edcde338ca5faf5de0bb"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9df1e3bd6f9c97dde3188ca01038692c1e0a6e7e0d9c46ecac6af8b601a61ae7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e286b636df68273606d30e5008430f5d51bfd686"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9a6c93eaa34add9beb612fa65d38c31c9e541e205c3aa7ca556089bbe55f5172"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14481a62ea422a7f00d6b5cd90f6150f4395d8c1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e1d74600505b7cb94ae9a8187c5bc95ab784d9625cbfae0cd5a65e38d132d6e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69ee6b4152761f2670a09ee1a079c7d6f9662757"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4c6a6b4edf094abd1eb04373e18f22ac5fe0e66d2b8ddd7f2531517279e7c6d5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "13e6b0f16b2c3ca4f9d4092140780c5402b8aac7"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "156a41d6aa018791263c7e6d319bfc6e83597a78dce0d782949d9f0195428c06"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66a6b585ccbadea203ff0219ca37afbdeb372956"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a022714877a5f0513b8919e24d914c5878e5c34a0dbedd041282d879549c6f3a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "479d94d51f26a574c39863dc33876be285509395"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fedb7e508e8a6176152bfee46512dcfce84e381b65617c4e50581d5ca9dfc597"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b02f4fd90225df98705981197af79b9db86fcbf7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8520f4bfd6212910fa9ac75f92172d012fdce56b8587b8b3fb5904c3bcad26b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71561761ae3423ee9dce17c3d81358e2d85192e4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2efd5d1ad46dbc82d1f395d687c2a2795b4f6b88ba02e8dc3c4b5a24504ddfdb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "b68440472715a4cb61d5a97ec9b7779b01f6b78a"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "506ddb039a35b87f5b0fb666a1691cafa6ccc32fb423770be9cf1f2253bf7a71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d1fa776dd8898f00425e8725a312bdf9eb1796c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "4ac3e382b30f540f56d00acccfa9c1f2e9c3e67fc7f07359fbb56bb68127aff0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0820c1c43ba24baddeedebd2723a89828f798bc8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "647eca87a7c97d2deb10bac1f1a0b86686e9c4362067d182b712557f5a20f016"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+5/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
