[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a36d5942810a91095ddc5dc2587fa28077403b66"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "80a5a95856b7673d1baaacc884f66773bcb0158a4e49518510c1e8a72c8d93b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cbb1e030ca30d2fd856c03445ae33fcc58e4eab"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "27345e5073eb953d012d29ed4e32d1ac4b9569b5e3646de9f93cdc8979d7ed29"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3a8d97dc04026187b5188ac24c2b4f662586c27"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "02f0d353e25c0b92a4d33b9cfcd9b7b98d832ff399cdf4f1b0fc01d09afea767"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ed3d3d460f3b9cc72dd4668e4c682e32e3d642c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3976bc532e4bbb8862215d0c83434996733bbb74016ac12e653ae1c43f7a9bf3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32488b2cdda27e845aac1ffc29fe294a02837ee9"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "bc614a3097d991fb3e3baf8776b27e776d14b1502c70192da2fd734c36ec3d57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90f59c787c5dc631dd359b0e774f61ce51b4c91b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "81dc527d136dcb87bf9842b3a5d52601473dd1f7c27e6bd21481443aaf1c03b9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64fc7ce8fefd5f7632d7ffaf9df13dac52508c0b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d502777ef3e23ab8853b9c84fcd6ceb4ff01ed826f8abc6802d65ead4f93793f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e7c04ce5c4ef51fe9ec95cf2d5e656990bacf8b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ac7412a4daf462544014f75db29a68ea40ca7cb23f183e7290fab02be9f27a6d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd0bca55b809a85155916767ae61e3d156020800"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1c09b5f427342afd420957dd81e0e670f476944664d0f0af9c9af3ce1cfa9f37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c01a75afc2b6000209660f7b9233e2d987eacff"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "f066b8d9dfbb641410c5ffd16a828fc632f0744ead4a81d26d797793c9dc558c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "772a164496d257391bb42c2861113243254d6414"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "959a04730d4dca086cb1758148e431ffbe1249614defc683b3d7a5a21ed8a46b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9717a0712f7fb6b24f4293158453db0111c9d00a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c776c5106db80d804fe080adab9eee100420fa6ab58ca7ee6261c47c728adf84"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65fd1cb027453676bcd24293cf46e3d82ae3b8fb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "120f23a4d7c514fd66a00694b469ded6d3deea40e04edebc1c181e6dfa5548a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba8e7da5590505bcf02fd1fc8d5dc992e177ec9c"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "81a9e11beec208f7a688148b8ad8964a8f10853f4f5c20615fa75e599f2bac6a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1c2418c7671aef29eb7628862052e0dbf460fa7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2966aea5a0199b1eb260326df6cd37c50773fa6d516e1fbdf91df3ee50f77349"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e375560d6a31116dec02b687ef02080184976bd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "372fecd6d09c6996c24462be0a6262ec128cb4788eb91f8083f645c2c98cfa3a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0823c4930bf8a10f9202b2c941c4c75a487cb96b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d0b0baaa22f8d9b06508174162186b2574e8e90cf054827caa4f4ff093175b8c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5af9ee67b9a3b2a0f059a0820f42097f78268af"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c1f6ad7005bcefe83860c8b79291558b8a4b20424501264baca61ad6f15fcec9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "026aa4adb47cb05505bb7a3a325335b178d3f3ae"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4e1b298b5a5265ff6d92995b22ab1de5e7dc2e0622b70cbf0fb08b20b8ccd06a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c00567475ae8473e43433c8b907b292c629dfe5c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "abc8c50404c4645ea0c30b748616f05734710c779d136666f5dc1e6f0992e443"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4f5d5819c3b6f01ae968bde8667180fb6788f6c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a3a9167a3f1ac09d90f03e99e0222cad5f2801696b565e29be8ef9f3507beb44"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "953f00800a5c41addf6036aaaac0781d10acd8b3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b76100c11993a287954d85fe9faed31551dfcc7554d3cf2c7df719bb4ef9aa42"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5549bbe791edb5a99b2a8c6784ad5685b6b0e5dc"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "2cf7e66c812f2f9e3f5596c378efab5b2f09bfc2915afdc0ba35c0956e0c2097"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef2f4c03a63e1ee435dd121fe768d04bdfad7968"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d36213ddea7adbfc3e183efaad921adcacc3575cfd282a7d4f16f40088b20671"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6594412bcddb3ab2151b3fa95f3002a3d1e38704"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6a277a1fb5077ea91b3495448916bc3679fa08fc5f86ec45806671239d05eff2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e1e11e241d30b36b48a0af4e0c80f267a51f08a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "efb7238c079efbd989a3698af9faba54e1eda8e4f1736fa4613b5c49d5105c56"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+1/LLVM_full.v8.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
