[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "88e0366dd8cdb44319a152158deab7c732dd37be"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "bf8453ad0a5f71f9a7c5100d4d38fd562f103d804dd143dbfbdbf8203df45032"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef2559450b8457a628474436daf1a8ab227f246d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4ac472681dcaf57611754ea94e6568a123102e7a03c81c12f58f709ce29b30ba"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6d36ba0a139e21625077cc979c47ee2b8ff62a0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a0c1eef683fb53a84bac43f184e4961ea63730e4d14c6b16d848f4799d273c44"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f303cb7ca1122a918be4207dadbfde14dc90ba3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b2233e15b58b73ce0ef8a10991c5472223ffdd07fa2b72f82ee7a1a1deca64e2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "741e10845dea554754ad8b0333849f0b89046009"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6970514a16a28fb45dc48dcfb9acdd10e85003428f538c915804fe89cf56572b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac3723cf5ba8db55f27d17408a514f85d7cfd6ef"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ab6b8bebf17402bbaf687db0249c6a3de83de634bd4c2aaf667f4c0496d8dc3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b076d70438952d4432f27b3a5f1e52e57232bd0a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "720935089eee0f6271fe1652ac0589732ea698b9d17cb6bfec71c90d1e6440a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "485e5f45f499824269508edb787364745d689ed5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cba1a626c7c40fc772e81de60234305563de196e004feff20aa30f913beab603"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16c975616954d58f32d5f3158e7ea862ba7aa757"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "42fcdd90d7353494d51e6caff9a4961c0535aee9b127234603ea62d2d129b056"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40f18f47f9046ec2ca4b7a916d8656a5d0e9877b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "580c6a739c80d0d840e5c74d1051887ebce2f1862075eb00a9c830e806552f3e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccf7e801253193e7eca452c060291dfe62cf17c1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f4ecf8d4cb75af053d3be11d49e9055ea70718df36dce4e7df791e54432914ae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25d21eb987268c2aefb8fb71084383720864e96d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "db6ff8fbc054ddafd67540de7b30a0839653552573b8049e66301afe03300357"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b96e5984cc02e8a12af1602e2bba0f593081bf4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d4b70ef314b99940207679239657573b4e5467644a5fc01f7c1580ecac407922"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65e42a2fbca8bbe3e6033410296cc64d14d821df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "693624efe9ed38bb036823891e0cc83a8468c9c18ebf7147cb27a21b70d149a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4501c210981c4f3c728eaf4a9d6aaf593ab557ad"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b5d60b84e46a474c0f45c16d5f1048f871982be2fbb6fd4d0eb9854b9037f0b2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29e32ca218b385dfa55b7a3284673ee8df61e51b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f187b2e781953865fd67f9047ef0e6a147c3019406aac32bbfdaa206a20992df"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "337c61b8b6374679b8633f21a029f125bd94ade9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6bcc009223cdc9bf4ae5f156bf0b718720ef55104fab9775656eea6b9f3fc4f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bee20705a7e1dfc99a956598beabae3cc1159911"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "dc5779804cdfb20e7dccba6cef9d92dbb3602854d18d50a6dffed247fe4ef17d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e6a69f48cb18e01e770dfa6a0944bfc7d915b59"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a324b36eff4b8eabe7f038ab85fffb0484027fa0ab9f54ed12e83e0782dafa46"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e46d5227f0f70f27a3f3642da9b77be98e2370e7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2cf92ad0123567ce0bbcee0506a84c77cf39835c5b044fd4bbaef63ca08e1024"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e7267ef3ecfc25947972e866a0b16f31373ef49"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fdb1cc308bfe7b2924d3e0bc67a1255909e63a8261e38c8e448e4a33e2abac06"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "b0596e8e6b4dee89aa30c585b380a2b08011b0d2"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "eb29de290c093acb0d44c765b0ca34bc630bd6028dfb80e5b0602f8122d8e30e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52461a9411bf4368a782fc47af4cdc89c6946e8e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "07f476f6e0139d4852f1f4f5835e7ffa888017493c97d3d2ac02cf53fefa30e2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1de344a1db0b11aa1cdc0c0a764e648b15398355"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8ea37166c3fb766bb81014ec0bd225ef09c4cbd69f82c70db85dbab73f0aa266"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "167eebb3c3066c0d8ca0b6abea1e0e228496301c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8ba1a18261d6a7a1177523a3a8e86a64b2f73ff0474d043de50073566e502b8d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ec754ebedd01de1a8c61e0ac692da6033423e89"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "739ed5f32a6a293f12a2595d9809a03929f07ebb34431da6bcfc21a0af4bf80b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "51dd35dd00d4913e10a82e6c819e6eeb42cb8a10"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "7a1b3bdf12193b4439360ec4c8cfee56a31a9aab8b06a9840ea1ac6246c84b7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22ddddbc3036b879ab06955dc8a037f8b5cfeb12"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "682198d0213dff5fec9e5f5cf4a6e722eac1600599fc672f0aad1732579251d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db9f5219a5bbb8fcf3da19ffc1dcfff800bb89b9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a4989bd595d275782163dbef8d5902335d25f5130697ce9ab8301926844bad41"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+1/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
