[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "9ecea4df6f0a23e2d8f1fd610b8ae6a5a0cd52cc"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "8d3cb91599f7cdb42b0f6731afb28e49a0c308bab50a3205cc328785e9a8e2ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91e53047ab59ee5ccb744a40224509966a076769"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b54eddf7b99964bf9ffc48f98f2b8777326985ea6537bdec35d4838a1a36a168"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5da53596ae85ec64531a4c58da72e59d97e17f65"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "504a5364e1f35be7c3e756f2ce92a56281430077c88147b2cf053e099afd8c50"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a534a81b8b16c28d6aa887ede60a59c5ef2bae04"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eeacb578ae3eb9f0e02446b72bfa66c0872a4184d71a4eb655c53e2661be9914"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66b88b74741d3d69b533aad54f8f260aefc92604"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c7089917e80ad7c9eb5199e3bbea03a60b2bc7af7b2e2a9b2076d71376040953"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "569006f737eed18a7103f3f154a889a577f5fbe6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "81ac4e0722f6f9a94620ad8a768c8ecafab85fabff3c341bbfa8072f6cc532c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5948835265aa4caf8ced8b7d4e2bbe2b6550cce5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ed40fa4e8842892bcb2ee96aefe885cc26e6cf1d89a6aea4e67c85b4c5f41680"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5309faefcb72806c3dda1fd85dc9981c67995535"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "721b4c66ae8c189fc9fca7132d576550b04a14cc8f1dde891ff8425bd67700d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83f354250e843389677daf636a18ee50b08fbc6a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c4602b2f0f7b017fdaf8cd66b8bf4414467c7afd7035d7b3ad880c276506eca7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3549cf1753d03e89effe1535792f4cfe62d061b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c3dd4fcebaf263a2421771d25201bf8cdcb9f954040771fd404c572fa96eea3a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f303b99dd52c3c9e4a77edac41787c4095b518df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "08c3d0adcc605b29eb86a1237ff5107c49c3235bf3f22fcd83e10cf6577564cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5d22750d2e5596a0d4df37820eb8dd213725283"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6b9fabaee9794d11705568d95cf79f72befeb9a7df565dcda8df62f54f5f5f21"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "607b81d3c655b332677040ce11243d3abef2bcae"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "871802e8d4bde3db1618329028a8c427fa2853ccdf17dabf6cd34c57d4d1a76b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69fd7025940cfcc2179afe5ae28cf8ff4b4aee42"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bc5d31f950202ed6c19b6b37d98646761ccc673967983491a120953e11cb18ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45b3e9d4fe23def162b4028a93b093de3287602b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4d0eb1f4c793dbe70ddca65c87b6e6f54e60b431f6aaa4f05784f4365dc4402a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1010ac4b31b08a510b22bbd0f95678e5a976a04"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "734dc4d43e0712d929bc0866ac9183cfd88715838f333467d8582e6bf2113895"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b595983caf908d2329d8c37c76e54b0aa4de02a7"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e270c08ad70c3b290998bc9f89d81f2b79d1d8534c86b8a8b670988a4bfb8846"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bc993bc0b50955c636caa1f19469f70cfe6f075"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "472890eeafe26bf5a218c88c28855199f5e8099845a993e97fad58a2cc7a7b71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "988911cfddcc6a973bcf095aee55617e516bc5d5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3441e95b446dd0f1c7306ac843789ca4953e1f8fe2eb8e464fe49ba258f6e04f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "a987a4f7d058ae9256c60f23ecf193590f8682a0"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "cf78ad7e3e69c99c6cef2248dfc0e127027be6418d453b983bd6c5f71df0fbef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75d35c94c6bbd175c8ccc2fc1a854004152711d3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "070f697fe55346ac9f6c6b23706eb0995de1271f24bd10cb2bd674f7a97fbcbe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1efa5212f4908e8cc59332cbb8c774ad286d3774"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7da19f7f2a70c5ba84b906ca158abcd16cb24f300e05594bac3d38e73500c168"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99e779441e8a5c12b7938c7c094c971b3c84bde9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e9a8b0c9cbc27b6ef184a2de8e9e8e7a54831b4b8f5b59b39fea33750c085969"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58cabc2e966f20f33831b08cf19bff08eb812fd4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "66b4b226f3a9cb614b223da9a6dc958b6e19776a3953f294e1dc11622cec8051"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "43fe39f70badb4bed2dc47eb2bd870a383521db8"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "61d92a89f1b65a2ba9bf4cc43110f9a6837a0a68788dba8eb733c289d917f858"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6769aeb36e785e1210c5784a3ac62472df38539d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "1db261639c297436aa53b6ffa53a3a34358c0cc0fd54fd51347d2545c3fa250a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68b54e53cfe5174506c3f813d2349ae101634b3e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8e151d8e0d3f2564bb3f0ba7fbbd054b6e7c634df3553178a2af2ec6d5553809"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+1/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
