[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "40af5f793309746f3f96bcafd196fe0364f064fa"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "f32e856f2d554537b8b10f89df26874e102faf9326a9094bf34a091cb9a21779"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d050f2ed6f3d2cd9e55bcf5269a8a4d853a8db24"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "da800bc2e522f72873242bfa4979cc9d5576e8c63a1a64b7381c131371c297cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14933b8dd5b479a40bb325be1db4170d20074aff"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3006dc2b0be10a05c57ddacea46b055a91448386e36a05b1e136a95e2251b070"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "68a70edd809f8f0db79c7d7592cf3af5a57d0c8b"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "1bfb0b66da77144b622e5eb843a7cc4a001ef9bb6faf42640a3e465a977e38a5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ea8186ad01132a8d705ede4fb9f819fa71d73ee"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5b8ad36ff05eaba287d1db90ab87f04081d1989e7e7a4a4879881e3b6cf684a5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d90f315e6f8693f2bdfbc83633cab24102dd1c7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c24c80ff86e8cd3ca3769251903bed59cc00818f7859d565d9f463b80f779727"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7782ea3f9c8e84327ba1eb8744b51a22b12abe33"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d3b833bf98aefb616fccae951f68110f29d2b21eb981db78afe3cf080b6af07e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e95458b0731370436f64ed65825680aa1ce7899f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ad701e2a491e4e49c08a26c624c263ed98e50e23de0507017ce06734008e923a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8265ece13213b2561e89713d515de8d5cec60665"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7322246e991419de7cc65eeed1e9868b07baef2b85251ae9186b414365f9f447"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cd944cb033e55d5f747ae322fffacd1aee3095e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c6b8a63663a32785bf27efe95614564f4fc8c100462a90255b04c1b04e88c4b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87db4675d83a1c6ce73ed50c3079aa10c2a162f5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "259e5a06721495b90434712079c2c0d4de36738dfd893650a547b4a361c38a2c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "125dcafb0eff89b576c7c0c864f5f030086a2590"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fe4bef511b5af24e17fc7727e799b287d8dd02149cc0eb580f12bb737efcb75d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "8871ff62f9d1808479e945de4e6f3c26853c62e0"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "09493f0d0ed7e67c3a490cc12927072d1dc1a969e5ddb6c4248521a06c9683bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a55bee37abd3dc49b9f8c57f330a74065181c75"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "466209c4e514bc8350ab78a0d14b295f40855f853d4c4c7a6c425bad8367e5ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42a6542173696464d82e736b56d549e59da575da"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "196c32fbf7b5fbc9cbd3e3519e3b4df6e04420aa22bbd506adeef3289ef24ecb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "09585c0d7ae51d0ed40b40e66189265882511cd9"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "2ca56a3a33ed51999ef46acbeaaad22de58d13404ecbc181953a1bc6ecd1d196"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3582dd440d8e4c8a5a40c02529004ee1b1af8356"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "17088d358e53d2a424a3237933169068685e3c712c8250f3db783a3f6c1ad129"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+12/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
