[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "c23fc869c3a5815b8bb7422447ad5488ec64393a"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d1991949fa55da9169abce29b282a3fab198dbdbefe6170e9476d8de68beed28"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eef524142ec331bc4e8176325d4ed1984e2d4d57"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "de6956a18d186439434a3a9ddffc75832d4bb0b9f19814a6009f0e7910975c6f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9b1bda1aed1a76871b87ed12ab857944404d59b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9aeb0a11144f3417cbe6b0eb43912e60346d07569091690a4d150cff92f29a43"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4068e6c1f37d2b348afb984d4178ce15116019fb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0db4db9f17fca8b9bdb8a8627c6f3e93b6181493f73c89cbbed8a9ceded19a0d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d9805b7f02b07619279eb81c75676847c7800bd"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf6e365d07fdbc7b3a6e58e0ed1f5b525d2b0716fd242cb0bdc8651b1cfda2de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ce83f44b37955794fe266cf9f5da118cf8a9964"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c643e67750a559c49c91a7cf5028d669bc7f2ad3fbf8c35fd2d8285f1a58a1d3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69d3877a329806001d06f0dca1cd21c2b90d86a6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e5386b871e35499c70dc4e0fc59eb2d856bfdd611cf4ec7d888693090d2bfcf1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f57688fc167f1c090e458a77526159d20509f244"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "74c18ed3a667192d03d5dd22bc760e62072e65acdbeaf4534e7ea18d9812d0a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47d093a0bec023c04402476b13a66d4b001842ef"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8b878a68500269b632b0b18f3fb53b6ba0fd3241f986c95f52612f9d95021ee0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ea555785fcac5f6e3c8462a750c2692e02cf566"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "579f465ec8b522ff7c7a4e783e02560c856e236ccb572f1bf20fe7b282f00db8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ca0ff80e12a25972c84b6f545c528d60a563886"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d5fa8b577898fda46005edb9e005fea0137ac7fed702623dc101ca69d605a1bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f881fbdad0b3161c64c86b60acf0bbd5b9fc5e01"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aa231e9b3eb2950addf0877a26afb4594b5aa5834a80f35dcded9c0551ddadf5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "221b310d652cdf9a90d5efa73df293f7e54b47b0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c4f7c9835d06a5de956053b492dfc11c9749f8328bcdfa8d031ef2ad66b47b2e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9633fc1a26a43d32017ffc2158750486f5e27734"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9eb3a4aefe95dad8a1546cc7d888a61ca9d617bb001fc5242c7b42a90eedfcb2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdaa4df773ca4df4836cee635f3d67150a83add6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bef62500605ae1286680c67318be24a311d80bc361651cd45c7befe932d1a30e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8b607decb5ac0316f0768c70250f8805c1e78fd"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "2dbca7c908b3deb0283b3edff7b3c02c19c9b4744154ef070d685ae93b68a8f6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b80e668164518a6876a8a908c5106f0353677627"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "2ac186edb12b1be9c0562dc581559c776ac87e72bc92d476087fa36c3edfc37d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dafbaa626fc4505767c53c8637240286878d6e01"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ebff815aad0f124a9fc4e056bd7173c5a82af1fdb6ae7d0000f537c314281e33"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "064044355e5e40cf486b5add4780f9e60165d590"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8f4267cabcd4ca72bf7f2be7c079c774e1dfe3d53e337173949c3678e2c7643b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "5ac07bf267f0f75d5a9b1e675154e013dfead626"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d635452e1f2425de335826452f2c71fcc8c95285e07beeb12df398e09ed51fc8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07abc955fed5b1e73bd90810063f33f2ea354ff3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d375c0e572d5f1f22e0d47f084983fd730714a58c1a650b5c2342aa4b390ed2a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ae9cabb49ae20d41482c563d44dfe7951e3b71f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "58277113294da50cf27d148fc45d089e304093ea49cd0c46bce8fb1015e732ef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67a64d3ac397c731e689a753dd9a3a53f8552571"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "17ef5c02d688b1bc37a86d2edf1761ea48ed27bb92e6d25cdb649982527b2552"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "215f92e1439dd8eeb035fa5cc97bfc672869a7e9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ad1f3bd5d234ff652a249b8eeff263032facd63a588b610a359709699a0aae24"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "e280e40d8b70c714042932828155b576d5e84fe4"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "62542b40dfab88e1ac38a5e3caf40dec39f42531cc4e7e03301a56a8062f7b0c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b63b1ee8e587773ef54fde8507a9386034cda45d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "2b82e30c477e52d24902f8d7e4d768e02e92bbfa1824302df41602ea5b012e74"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41309939fe3a16ee6a7b889aa7bfc89122fb352c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d84bf14304deb1169e32c9700e2bed5d46e93f58817f3c84fa62532d6c192f47"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+0/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
