[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "612a96a70492058cd94be1b48f423448a05f9cbd"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "5af1d3fd00dc2997bf12591e34226fd190f64e32788d66aa07aab4551cc461fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "235feb4aeffa7c46da1514162c5b919cf90305a7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cdc1b97be46cd75715814cce73c5edf1097882139e85cedb4d196588f85f0eb8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cb0a6e8ce92ebf1c90a44be4ed5c4ca30cf3bfc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3243fab0ce39f2ffccac16e265988dab03826cbe922c610e4588e7e7fd811310"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64f85bdc5dcbf51f73fdd73fb461c916ff98d618"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "abbb3cd2e3085dba1ca385afb8bb617959612016865d172a6d743a9c746ed650"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c16814c507864a10c8d8b390f2816e02417fa2b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cbb4302e9c35a1d03a99f5dcb3a7f54cbf35d1db8581aefa99f3ffcc9afc4608"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01cb70824b1622db52b1463ac56f586f3e5466ae"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fac2427c73aa3d5e920fb30583e667f9904c711dc51c75bf08d170a2f13d28ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fc01ee9c0129206a3cb72b7248c12b86c3a927a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f3996d1dc83113403dfbc070f428235b414a43e03aec7445d3cb89bc4bc7007e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce97d36a94bd77803ac9fd27a0a1d0c490598db1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "793f96d4a81c081dc1d75c7ebc638308ae3ae0187aaa6377e4aacddb988f243a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73aa324a3158525f148d6f1a7d255379dcd06ae1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ca4ee18f81289306dc87b4d7cd9ca7eb04bc0b24ea58dcaa0c8d821b7cb373b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1740f19b5de65cbb7bc4378dab4925b6ae88216e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ddca5c40bf624f6bc9d13825eafaa54d2b546be45fad0e4cbcab423d2b6f0ff0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba3a0c69047526cda73c39e9ed9d6d917a18a422"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b0ffff533a1c27686a279966d8f3244e5c0ae4d6e941fb69c432d4fc3c41f16"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c019c93ab2f7c754a0976f139f79285e837a9e0e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6620e23e1f6af1853ebc09963dd35ccaa3b8f17a70ee383fbd573a10c08352cd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7dfdf4d2e509d27a2fc8b0c6f5699a37206deff"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2ebcb595d5e135f942efe47be6f4041318bfd8c387145fce6ba478dc96429b44"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c47beff00fd074a9541b6e1985ca088eafbd712"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d8f70774159cae8a8a20b7e0befdadcf76b9f39af8c14c4b088f595c16857ae4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33939b2b697a9c601940822203a4cf0f336ed4c6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ba1837ccb590f271e9e8d90fbfa64a32753877b34f1881d293de8b1c30836707"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f1ea07cde9baf91eba1c89781955fd8081ee663"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "5a3c8a75665a85f5f6ceccbbdac598b9a6763648af4f760133f2fc6902c392c2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "782d63a606c631981c15f511a531f864c70be383"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "cc678922f3fb048aec850e73e5a7c9dbeeec4ce7f030a6a74a7abb241a288514"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "657f7ef20ddf8d409fc6696b1b28277d2cadd073"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7a618a69bf54acf2eef00af5ac6f2dff8e7e1d71f0757008cfe08bd0930038cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0efc3cfd929af21fa166a7e2443f44c4dda157ae"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7b718df3083ff3fe4e08d196e6d331247520f4f74a58b14990066323e44a3e62"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "aadd559735f578a66e6bdb3103149c521fa14ca4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a918596a0592e6de7a70d0886fcf7b1400e757fe2b0b61f074eac077a4cf61f9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b673b06aa9bd1861fde18362d9819e3317bd391f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "10f03a164ed786bf1fbade68e29293b23b5ec1884846bb276035a390305c92fa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56f55812c06106ad0fc0c5bd9c396d5d8c9e73d4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9868b318b2495f19dba8dc6ddce9b06bbecba5aa40abb0eed050974e47b142fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d75fe76c96641fae60f30277237ee702266a72df"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bf232e186b5ebe6478a8cdb7ebfc1d6a5bea72581815a815c9364270d9024b06"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53273e365122180ff822cb358536ff158b86b6f5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1a375191508531d81a554eae569da379546355276de0d9b41617f496dbf4ca40"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "6ebbd587f46bc2d0896df7ec884f12b6d1b23996"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "67ca492f6e1dc2d1576cf9ed349cadffd2500d03e427a8878f1c3511c417cb38"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8a7587a688c90146894f1a40df1002c1b328b64"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f0e968ee58023f2fdba8ea49e2a2fffbdc62fcd5216aa695cf4f1a2ac019b266"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2188a23e03d8f187832ff3607185e7914ec24ca"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0eb2c6122b592a18c29478444a99da1709e3b955da176fd33548ed885f1e4d64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+0/LLVM_full.v18.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
