[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "bbbffe0fb0c8ccc189f620639fba6ff6f833c8ea"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "af9dd0ffa6558fac7ffd6cf3589ec3a7004e40d5deddb25d5d40e525cf8eabf3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd3a222adb82ef800fefa2260aa63601f0ab1a4a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0b5307f2a1d46b6f871ffaada4bfebe44aa173ef87d844d4c34480003b6f00ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f35c7ff4f546ad3aa1b910e25d33ba262913d18"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f79e03e6a3db1dc30be30ca1b8389db09f4b98750690286641bf44507063be7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49ab307e836b023c22b22cdaecae289375f21dc3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b0f0fbcc09181d33c205fce1ff8d9293a5bf0c36c4f8cb02f08bec577e1993c0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9549c323cb7e47c009074f28ad16fe46fdb11e55"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fed5575ba9cd3311cda4a0b936bbbeacda8076659091d08176dc35af703c820b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a929974dd22604a69a58c2c535df4c3621ef917f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4ab14eaf1882b3b79ed02b499c130117b617cdb24e434301e581b39145adf3c6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "616b059e99e1e659a63d7d4949ea8367c626fc55"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8144cd64a387bd9afba1120f6671baac77643b4d774eab0cf4a5a6e31dfb7d20"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "132d60ed47a3985d8511574810bf9a387cb20e87"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0eb8729d38aff5a843ed682852884a5f6b8b34831fb14188ae4e06e9dd93d77a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c866bb10333d409e55f5da62a51fbb673c3c8c5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e129f0165769ce0c2d78738a398e71f11c2a3f3b1a9ac8020ff9c48b8d96fc3f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7991bead7268f147b1dcdb640005edeaa3741bb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf0e39ffc247d862e52448e4f1d02dee2646f26a7eacece70a568fe17e0d704a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15547ddafd3d2fde5b980193917b858593b4c95b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fca40d20efc5cbb5923eaa34be8f80389df724363691785def7886da2716ac04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48c18bdada296818d526ad80d05368d1540c2d4e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "daa8540950c02dda6b9e197866ff6ded31858bbeba715bd4422568fc1c02642c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfce69ae5f96aa47a206593122135c3a47901396"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b6f948f2cee753afa88df01d70574a754c24e291a32394f9020b1292880b51bd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71cd0fbf2124d16fd576724eab94e57de2ca0a8a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dcd5bce8f46182e8aa341cca903df9922193d110eb9a7e493ef3e04b186fd5d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f96389a33dfe75b220c97ee7d85260dc4d8ac3e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6d6b569d0bbaf01418439a6bc367cadad582dbb3440587479730ec8fcade326e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf7c41996e301dae71c4ec948505734bebc9c506"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6ece7a46e7394fe3bf70387a8bf91750468eb54a368acef2668ce6fc4202b2d6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6baca407ab7f86383dc617a9d0b75d1671505d5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4d9ae41d0cd1f7d04c585eb454db37833d7e11fbdc63df81929b238614041077"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3087f0b4137c6c2bc7ca63b92b77e4c41751bb18"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "91717beef74c20e13eaf6d2daee633948daa6f49758f1a6534a4443f7bbb76b4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c6c5345e410ea84bfa02e177b91e57a7b15aa3b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3fcb4247bed8a8d05c746fd4b9e98409549533f152e400c053465b277e1a7a45"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a1639d533f936d2745ceb48c78406e515041e6f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ffc27b90434d446b66f2f553c54ad05d8f9c8e14e3387d5e0033eee47f499686"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edd3d3ad54a8c43d039513aad337899ef1eee345"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7e27ec7464f03ca9f68f9efbdc1f31ddfdd9989d3d89bff05e177ac65d2a5786"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "ff597e7db27fad681e74c7b57ee8fac6397d0213"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7896f104b789ff5155f82eff5ba18ef35f95ea925466d6e604f0190583bd0e22"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7e40df5f89b72f187da79d201342275304f389c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9ab380616bb4bcd6187a8c3a4072f8843836246053731e4dbfef6fa66e2d618d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6e1585c9ced7ffb516b708606d8fb216f2ae4bd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9865b57ed798bf8825603065edd3533cebf987294fcd38bc903eb0537838621c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0132bcaeecc8007eb437a45467b04c39ecd1ce0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e1e9fd3b621f9ac4239304299f224b0266bea597025b208963a8dd742ad96c29"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fbe4a55d0cfa6a3f1c996fdd8aa0f3dd3100910"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9b45042e4eb95fa656291a5a64606a8557900963170cc7bc77215df07a356a06"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "271fd627127eba49d36406bea8c8b1a5b3c834d3"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "63b66b1bdb5d4836302cda587d39c910285e3bb7de467a155e64bc90eb851d90"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e96efec2ae9546e2d08c4a5d1778d08100ba861a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "048c01c7d233a987db2f25f17951ba8372388f973b7e460e55a79d5151595280"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d9d700abfa41a4ddf1325b9229a0bc3c756fb38"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "2a36963cfbb38c29f1d2df5c1caa8441fdb3606ff2048e97fe4a500650d153dc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+2/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
