[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "ef03372f9531df98fc197e9416f5b1c072b64be4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "8fa79747dbc8e006dba94fa7b5e7b94d1335a262b70617e967217a9c4d8e49e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b143dc98c63c11f1e9178a766723711f05e0f3e9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ca4d5c6896dbee643959fdb33feeb9bb97f4c73f57d7287758fe2d9604c1549"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48eaef0475a6f9fb0eb6c8e74a6c4cacbd519fa7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6a4461b653690c8f1775fbfd57669f349c125ac423e9e7f51a114f5cf6e07565"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a048ac2afdd6fa39c26f37bfbf024ff3d77bfd49"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e706fcb2ef97f2d59d56e4a25d592a0304535445ce65dc1ecb76e0c28bbde643"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "285b0076bc0472e4974b62a45d06706c875c2dc7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "830836cc7438e3812d98a69f441499c34f8e02746d29b4f402d978b346c4a9a2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "fa4beda488e60d53f07c4e215d5d3befa06522f2"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "1b37d170765aeaad5b255682d252b2b6c87e8ae07be5b6478dfa144870955b72"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ba7f189bb6472a2c85d40bc750f41c65c284ecc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "69701fff7a31940432b3cb4941083c6b7bd0646598a6036fff0f839a8a49ae24"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6624cac0115baa44932fb5f877afde0e81d4199b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "358911ea1333c977ea390ac38da5b33056cf948704ab656fbb913f261ef070ef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6d992948f58f77be35f778f4af0e5ff20be349a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d990551780d39c05204d60d822c1c4994290ac29f529637cd9317b87854d9801"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b97dc4150b1190947c88f22b70f2c2d63355f41"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "79718b6b10bf5627fc713fa2c6e5449bf289bfbf5c519e6b04547dc9d709de3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4f6d4dbef2bbb1946e951b512f46b3852a72881"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "af12a3588341e12da2eecd32b30314014c5fe2cb7952e8236667b1850a4a1c9e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1891a69b4e06c37029fe696a6185594d4617129a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b312a025aafde4b6ddd95a263939d3e7a23d118d469a3be41629ff9ffe9ea438"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5dc365008ff4c7f1708170e569dea85c0b0f71bd"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "02824788a66e02c29fe747adf377b311bbf52ba2d75c463044c9d9a6e30fb9d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04e0fb64b956e9f976c8bad21befbb95f684946d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d4a9193f63f00f98f51a34c01f3c4ce88823cdc789d3bfbbfd83282e5bd1d937"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af3ecb620cb5d4a5f833fb95931105fbea85ce6f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b35bcc4969bc050ef6196ffa1083efe50834f10512bc44c390c242c23bd3b77b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d26f066bba2305a3b294628a5f12272374dedfc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "177e19b02903dad7696d34a126cfdf9711769a62fdefacba382ff1f8cccd619b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e23d59c03113358cee4e0d00605c1bd949761a70"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "314f465dd071af0d551acde7601858f73335cc90e765151554b9a7844a75ae46"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de3cf872619255849c7c1fabfa1718e5720712c0"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a2b9dd3e39214e83a6e424bb759b790500743b670acd166236d1d38437c893ef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69089479ee1afb63fbc9985c42efca84022c483c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a8c6fed4757b92c8b59e89a628cd9e897491aaed6cf886bf2359bd674233a008"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f53c55c135fed682f927ae0a9689c39a1b400a91"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2fe69a3ce2e2384c35c38aafe928597ef84afe210e7bb0870747eaade5e4794d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56189631174716b9d7fb256f6bf475704e7ffc70"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0225f34df9774472dac31b906a5fbfd872d2990928638402c0450caa718e2447"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.riscv64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff339525bdc21f6dbcd6c8b47191f88ea28b61b6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "79e15078bdf50374f13bf40308dd73defbd365dbc047e2d2ceb28a658d46a40d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c214513808467abae2f73eed8c7b2b849cd90f48"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "335817e3289a389c80d40a351c368c9e853b6176910bc222297ee820b648d407"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8914070e4e079230faaa6758d38170d0abc60767"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a81110a407392721110cd723b63c09d462079763a3a9079cc302e8c254beb209"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7433a07dd771775b5b5a3b65e6a952db27ca6378"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "99ac4d5ac9009b9e1e550b25de2db9e8caf289d8bcfd58d98c8d89a345965e07"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6b0443071a365ff337167e4234697bd351c51a7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "21d757b8e055ceda4e4cfa05c0aea87716f42c1d6f465b0528bcccdcf9ad8e43"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1fe649605213c3c572e59e962fe7e3a41ad037f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9fb37dd3607d2a7e26335ff2222eb73247b9b37ae62f04761fcac859957806a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "d19d9aaf46e1cf6894dacaaa65e9cd130b54c598"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "1a5ee7fe24b4045587d3bce9af1e14f2b9540c96cb986a10908be624e78dfcf4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df6d37506698f796434e8a8526cc4ff662666a56"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d247b769cb0332afb97e9335757cab82d41583eba59e15975c4a40848bb5cfa3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71980939cd31359a341c097a9f1d2420fea78a22"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "dca57c587d512f14cb13630ea6bddb10c370d85e3382a26000821ec6004bd79c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+1/LLVM_full.v19.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
