[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "a217e92beeb42b3849467ebf9546f844afe138dd"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "642e7587312543ce0ad6faa087b48b44258d9bca65fbddfac489c14e448172d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3868c145bc22583ba2600a0573111406bee7769a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c48f96c1aed3fbba91de9fceb8d92320456520cf42e1dda4622109afe311cb00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fc13ba368a0927d91cb646b3fae4fa2e9279e18"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7f7570e56b47544d3a4b3333a768355ab608bc17b40296d38500c9e32dfdd393"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "195bfbe24ec23108c8b0a5baffdc4232f7ea4715"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "30395f785528233001d58b1b215db02c3cfe81090bf7f09a227b81374b9bbd07"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac5b61f617f9e00a49ad7d5696c2ef0f54f38251"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3804bbe61229a4366c9a2e06f8954674c4c421b31be35e12914a4aae088225f9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "15940e9185be4fa8d340d57d0ec75703954dc355"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "3050997d973e9502938c6120fdf6ef65b41c842547940a84450bccf7ef7eaf00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de15f11f12bcd16968e0a39725b8e419e3079d7b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3b07a0da61c37f81dca5e5fb82a5f38887038923c5d8b20b7e3386af2bc76863"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bb40e63dbc1221f7f766aa3dbaee911fdb140ec"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "106557f21403f83d147f5586c7673806682c3c4446a1e7552f846d5dc7e27a59"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c77c162264ecc364189695e44891ddf435d8f51"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3577ae3af2a8800c7a769df8a890007b7fc258094b566506679aac39052a4151"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fc6a52c2e6eb1f3c69b0ae809692680fb0d39df"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "07ff6258024d7fbfb435cff9528957a9f9350997aced88364577bd389501fb37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9e072cfeede6818a1f882ee3e407c2e5a72024d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "986846860f1e1bde08a6527102b1c29788b8407665fd12f51f88b585b3f58138"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "720d1d920b590f603ee607b25f7d26a806edda18"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6402cf7cff033ca592a3334ab2017da36a82d8e4ca4f7e534c60ff392c955241"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07a27b1d1f72e4692bf11a69a959bac71832704e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8fd90669705ffdc53942343b8faf3b566a7937e06c10994effc033b48d2bb904"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b26e1b90cd551e11807fbd21fa8320f17cfcf382"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e320721495f110694dd1687d35836bfe9412068267d5a092170685ac2e47b307"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15afc5e492200fef1ab1bddfe5c0c8667b2842bd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3e789d41c54ec684f8323e007ba20a6ad020df81fc7089bb621b98aaa2030abe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e1ac743ce799c7b90c7bb66cbf31bdcb295dec3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5112eae5875957449910e501877dda9aa0f4b73f4a949e86d9b5352592371139"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ddfe98f8020583b95963c654370a0f012ca6363"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d0c02dc242ab652230ec4863fe330186444ce9b8906461516430f3ab39b4e859"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "508d6d465ef334aeba98a6ab6e69a9f3d6ec40fe"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3d81349f3efe848a6122ca709caf4089be482d36e9ffe3105ff8d24f1c72108e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcb75e5dd70be6da219e727f8c91cd094ff1b4cd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "070fe858e7c251af07872f9bf14b19dec95eb09b766e6ffb4e4e6e09fa2879e8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b34786c295dd44e6845c09eecafe6bcff198558d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "54b27f0ab14e7eb0ff7625777a50a88e390ddacfea05ed9cf50e35626e333fac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "cf5c82382c5a8fe7f55615984693fc92b8e77968"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7a124bd14988d1063fb9908b234c333a7f27ea520c8dc78f0bababd7b3cc80dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1836e16fc404ee74404e301bf7ffd282f3b272e4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "262084acf32973f22ada0e78463afb48584c0fca258b8ba4b20913e263e39966"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba466cff8e239cb1883d48b5d1b876776acd26af"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1a5b3db6ea28e16bf19cdfbef7298428816450294407814ffbff5176866bcfb7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0857700e75789cef98fe02e2bb198d7214ebc5b6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "964d8689a7a449402db708ae4a99318162c517fd9a3566226bdd07be63b0951f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d2cc4b42a328898a31a3c3fb7d8da442609f986"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7d025d9cdffdc0b8b8077ee5628db394ca14e4cae66348b84fb11f5bc712402e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "502d05e166efafb2ca21072b65c89e76e9c79015"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "e9d8bbe859d6eb6050a51466c40a0ab3ca93eb8b63d401b06edf0932e0175447"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d217d501c4bbba98551846fc02076821c74f1c2c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a648f0f8bfc9951cbe6163b1269c3357143de08cdf6a403ba7f972ebb2955458"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "770e5cd72f9cc215187c413f6bacfdea557d8e0e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e3dd83dfbccc1c07bb01ea9b9ad2ee78b287fb81d3852de564fa4004ee6fa18a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+1/LLVM_full.v19.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
