[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "f420f26ebbb070745f008b058624815a39ad989b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "84876c7745b31132edcae1a6fc2ec651c510f8fd9c3115f5cab7838760102f37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cc9ef53d1113f3b7b258ba60ecafbebb5cb7d3a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3a748a5cb15a4630a09b2dced4ad2f16cab35899f76e166ad0ff74731bff06e7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2516482705160b144ab7bc5aa8a57ff1c3de94a9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "73288ea71cf79831761f3dc0353b25f751ca21d2a34464c5231f52fb8b110abf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "799a3c33d6fafaf306ee72867f47160a902acf8f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ddaa539dd5e6ef5b3daa575711e3751bb7da562ae70c722c3e71352de038294f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "604ee69fa76c7558a1cecbced68996b6f7bc3db1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "848af7697c249b61d3b46d8c80529c8df2c40c48227d0965a07570a9b0b9d499"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0894d6e96f75111f7c0e5cfbc0b25afd9bb20b89"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "34eaaa507067ef5e8e5940092bc9c047928427dee3ea5ffa97f7eeed1fcb1176"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2b24113cc12761ad2d357d513459c809a0895e3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "be89184ab4f83b8738d5df8c6fe6b6b59d7d9c88f8c4327a208cd16b65d59f9a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c80c2c9f24dfbc8dcbe4c129206f3029037d40e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b03ce7f3956adc968322b6fff0e0463b5d49843bdc6fcc96ddfe972aab808a18"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca04283dc7d2db69dfc4fe8f92c6fc4889725d65"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c1d5d26d7483f2e838186c0f9ca4a08d633d0be4114d00ed06e59546d959fcb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07d82547b47b2141cdd40a25d8e435df096720d0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "87dbe8539dd8b0dd6eb8ef53471352d2c6083d7cc12ace3e6a0d811cb1a66766"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbe84de7b4a3716b31a86a6b67fc16ef5adb5ebe"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "df9633596d923b819ae9eac3f184396c50dbea813c2ac80adb2175bc5724e13b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "585bb9b37ad2c6f91ce583c76708ee75d2b44b40"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4240ddf581bb994944c586bb78bc1545666e56b80569c98545036828cce2216c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80da71daddc9c169d9e135d0b0f8c89c8e9750a0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b15180b9902111751e6d35c507f322fef601f7393784eafac511a90959fb2a6c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dddfba13bf69df1f53a263b357ad59fc845dd4c7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a37b585cb158075a7847860e549c1e0f3d3e834764b9ff3fe6a983e827332135"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50c330e9970ee16c02e7639ef9898b9052d22bf9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d7da63e7fb88c28c20ee0375c8cfa57c53269214707b75f4face275592df3387"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a4c9dede77b588975ba6d8ca1b01132bab4c1ec"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a46bd609ce265f96659d1f1fa7591372572d87e96961c801925162b33fbed315"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "411e75ccd5f35ab91386433a7f2d9b3d96551de9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6f085904a7956645d47dd3dbf33b8a681b72c88230247c7db980d13b21668977"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70d4d95c8d8da3361225b005c40c6e7f45cc8d9e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "aff05d84aa8f7288b79eab9f9624eb4977152da6f1235356d14a2edb96ba4a63"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6c85a008c17c708e27530d5b6aa2defd97a9e14"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "53d30931fd1a2a96ab989239acbd4cf83ef87788d6907874ea680a2b90c08b26"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c3a377d52955262ea9c1e044c27c5f3aace3cb6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "27cdcae8fade458806192af20e605e076ed92011b7d48605c9ffe6c87bbf795f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2230dd1916eb7c7e069c345f6b962fddd71a0a93"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5110d2baeeb71c985a15266117bb1539ac6d11ac36dddf42934ab79de253972c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c532269d54d8fe1d06ca73bd07683b5595f36250"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "6f3446ca41d8cc3c49913a3d201140d8e5382157a894aad4529f7c474cc7a1bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "566415103f5d7e4d42660252763aedd88145c61c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4a3b328d16afb4366e2bb1c40e0502eb91d0ac18e27778cd0d1a996e850c0e0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7da85bd51491041d573e49b4a9937b103c9862e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "847db278a986fb294023c9f5ce23907e5aa034d104a686e662c50053e22af9ea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42cfe9cd6a8a606386015fbf7baa00a593587a7f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6c452a1d79f4f33fca41cfaa5bf94d564d71342a7926ccc814445681c13e80c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c2713a144b4d3ea8de4c834227b71812dda4cf1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d4fdff9b8110dde7fc0828edb6300de4d9effb0d23d137341e326717841b08bd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "fbe9e1a3049aaef5dc569660c4894746aac31623"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "7e26449c97c6cf535b3262e0ef018c32343ba7ed8cb8cfab54fddbc6b8af5f69"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0073ec301e31b852a357f890f32877c5f5d29591"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7d7a31d85007b635b0478f59e724dcb164dd3e85a40d36208a0387c8d393cb2b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d8fd24d827e254fdfef85ca1818a4a0305d4ea2"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "1a40927a72932d66c4914719053d8ba03258c6136033d46cf8c3987541d37e81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+2/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
