[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "02c7347612d22e0d4996a1e21175943156241529"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9b4594a06b8cc9c3bab8d24410d1729ff1454ba6b565d273888a543934b68c55"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84e4bfc230d29a95abe25893ff32bd1012401076"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e2ad9b87523cc6b832f15ac699620836527d3b96aae3bd8194db96545d29fbd4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a5dbcf204bf1d063a370307bca1ea9f79db1e56"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9b5903fe379a21787def6dea90f5392edfa67de8ffc1d7eccdf01cb8a417447a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e745801b5e9c19d478d016bef6461c6b945b927"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "983aab20b20a16de1e3dbaa2799adfe4f3a6c9320f9003ce9e26cf9d80fe6cf9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d8253b29473970a392692b392e9d26543e5439c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b4d71ab15e3ca6e5c77080f44f7e0e7d2fb2149c396fcd2706b1a461c0db960b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "357af9d05eacac09822ad8a2594c4cd45d6e4404"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "54a263fba38f81b699f7becb0004ce61f2442f7d34490dd2944dea6d929a2677"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11bc01321378007d458f0ff8a19fb7a4e28f7acd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "820d023cee019bedccf5ae252372aa19a5312833420ffa705db14b87606d3859"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7aa9e17c7ef15a67a61d79fa5b9c7dbfa8fa081"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "001bc21cf02e10fb73c9620337356c083affe4f8aa677941151e915adcd5f1cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5749dae7aaf9164406b56722d2bc4ea9425b6845"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eae1454aaa237cee2e8272bece1e885fbf058a43d464008c0be87e7bb736d4c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0299ee26dd8fe0b23be06574397c8e19d1f8ccff"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9150c737d9870608a2babd501aab2db98956fef5ffe32bbf05b19be29e608662"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3b1e4c14fae2f708a66bd0b85577ab135d3649a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "504b3ddb746f858ab03d25a83b9baa458658afe56685d0c62ac661e72666addc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bc6eb93dcf2aff8c771f9bd62e6d028e4aa637c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f68f90272d470dd7e3cf91a32448945369d918f73f6ecf18f9b33da7ff533805"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0edbc147f6a556c9f6a0e33d8a7821719eff819"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "537c8a0730f47aafed3ede3a7200deb85e1768c7ebb8d59b41c3f6681eba6758"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de14cafbb03cf4f4530b28980306d94cc00395df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8517decf2c03b80dd9bb525ab4351a6934896efb3eea4eb5a848f0f174fd7f52"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2652a0ebed072dd54791a7ecd19f17456f2f4204"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "13036d128ba201fe6554a0771bf7ee0c77ece694ee2784e6dcd004d464610bb4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43a96331f2001b60b00591c574993198e425bccf"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "67980f1fc150400a63b991437991e57a79bde1cf326b073b7d3a7211e672f466"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79649de0a59168eb502f0968bfcd3e74f0807d3c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0897cee67c0c921c533edcc3a79767996e8b2c4b53e08981ac2d91deef5d1436"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba6a09ef7b0676113dff0df31eabec6da518abc8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "22eec44c84f3d9cac25f1de98440c61b527ce787ddf5b655def6ded63cf3b729"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d7441cb7fa9fe97a5fb9ec2b25c422b0f4f8660"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9105fd63176953f45f3eace2f212e69c3464beb4f213916d1190421275d381ce"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59868d602fee295cb04744ebd0c840bb8cf7f0ab"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0d2b37503264ed6efc11c761a5862dc7e25472250997f604f7121ee659913539"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce2f5a2a60554b42c005ba483085e1c4272cf482"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "decd68e8e8551c61ecfe931914a9c86114948640fb3c47f310c843c1d3bfc9cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "f6d6745ba7b9a40d6fc800ca21c9ce93a453fc87"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "ad084caa4d5d474b11e496299ee80a5d39c4db76206117195749183cf62a4bd0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c07ae03a70ef017e8ee2e8524903570a8d4b26a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "449048e0b1614bd72fcb5e16f35159c9f58755dcb17f17261c80a4b6195bad81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ea33d2375173a0654f6881cbbe867e953647a86"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2e6230187d6c887bb15953652f0cd93505444fe8c49ccfccc261b5060cc393c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94a6b4351fbe01081e3ec14ae337aaccaf5db824"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "00b48cc489450c7426a00cecd39690f38ff69735c5ab2807921dbd2259574acf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12accd110739892637fe6f85864ab255fcfd4157"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ab3e44b43453dd2fcec26e349eda2ba6e57cdaf3f637d1cdfbe049664e9ca1b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "b8cbdcc721320156a4223e65dd9d00c9ed1902f0"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "4ed4bdd51ceba78a1ffd6c882d1a7144852507c30a18a8257d70432a143ef096"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd7221b2af4b5151f6d6ba576091471e235ec158"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ca9a3618a51e539e20db6d3a139a66a633b9ac3943d0be2ccf812aca05788ec6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a32d19a17db17d7a00f66f8958ba59007410900"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b6e2f4849a3c04e54302720ab075f996a98180c95b57d848d4160a9264c603b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0+7/LLVM_full.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
