[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "3c97c6b68ba3fc7ef78749c4e0ee710184b88aa0"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b510ddc3e1778c8e3cf396726b509aa460a55012820fe12fb7d2a9392c000866"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8edcb349c66e00b51b33921044abf1c3646d026"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d2feb3e48025b2485db5c530b740e3ecf448859ef73b0a55a65f9e9788e80bed"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c966a56c5e5c88ae7e6fd5732520634a4ecd79d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b057ec4d388e4b2a055041392e3ca0c065cdb3debb622169a6d902d30ead3891"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c2ba23db4f2f7991a60350fe8951268ee0f6636"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "16add36c549a4382ab375348fa8e9d44edac86673351b50d0b6461aa80311fb5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8630a5e0dd7389eb67edc509d60a3e1846508b8c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5b904aa22f4e83b2678741939dcf0ada7e54ad55f9d359bdd1f76dbb91411ed4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84941e6d0de56495c4fab8faa1347e902d28bbd7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "098e10e015766d831ef62bafc6ed810905972dd0306bd41fe0104f585b74b987"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a89e1c2f0a00466eee911f75a5971cc8b67783ce"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d624798cbc6a4145350a0763422518b6411eb0b437ba7aba88506e1131f163a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dff04b68f302c38bb7ca1745c8fd71bce1a36bd8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b6c9c2c8a66bfb384240b061aef28db1281831655bc671eb103129f1f6f8d563"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c9e97bbfbbe3f7221c0b0c703befd8b8bb2f3d3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e1a368052e701cb2ad1a558b67e51abd9ab51863900784d88a702e55711cefef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48704b84ff5f041117bc433afccf8d8d7fd722fc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c181f05ecdafdcdd2f011f4c3d706ca303e9ff848caa83de33b650c37ecd3a13"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09caf518787672e330ec50a41f9dac37d06410ad"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ccb15bb3c15b11fdfb190b37c096258f66ec539a71ec5e84d553e729b445af20"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "864360ab62c0eb80437fc281ad208212b793a40e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d836e33a7bfc39bd73466b3061ea599e59717796250fb6fc38d6d33a0047cb3e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82c9e5a8a5a67fceefab3cc1e3d64c329efe53d3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8b169b75cf7ed883c16cca1a4f9a76dc5a39ea9cb03499ef5dbde0beb8863ab6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c990508c7cd2873eb6834b20203409985fcb9f78"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "91fbd22902f8091c21c3d0cd7596961c465ac4c586b077944e30f94174977de7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a9097bd6a5d9f262a1bc8091eed0a3912d348e8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6d5734a71caaf645970c8a2f7580587ef337e7f5dfa558541973ec75da0e3225"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "303f051ad0af9f82fb953170ee752fee8a173edf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3d88a8a5d8d45618ccc4aff6613d518f33925011bdc963fd9dd6dbb1491f2e5a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11fd7d66155bd263252ee45324a7de100d98b748"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9ff871ddf820a0c6c17985b128e685b3d220584bfb1ef2b1a1d644134e1e4d87"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "202870ac123ab75221e28a2ee39b1a99c89eee3e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f1a843f10b9c8a238872361441edbd11a70692e21b2064b8f8299a1ea6d104f0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e74e484573c90ece0e921b2a57e1e3412b808a4f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1bc26bc2e0393f28fa55a8d863e03ab6256afd4aeba4a7ede512f088fa9b50c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "b139817a1bf388478d0eb248ed4460dafd59f575"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "e5233416719f4f3a6aa6b0c53f12781fb6b01519d738666060c7869de73a0e3e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56f63378ac3f2182bef3a3877249bef5365edcd8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b2611df2f6fa538679b6ae8bee40edd4dfb234a220e0e75784041a8b1a4e7306"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4a1526b228d4c6d02ee8c6c9fc3a06da072969c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "83fb6aa1fa60689627eb87ffda643f41d3e705e336f6468dafd0b346dff85655"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "925a3a0e3d0540aaecb794328aaa43ddf5cad06e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fc76989d3d921a6a49bcbee8bd454b98c955cd9304bf4713d3cdd0257a237340"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1624d1a8faa98150972b2ea0e11b7822e124abb9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "376ddd17965d5934d7c048c2ad3c3fbc8b6ebe2a8b5173a2111afaba392eea9a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c1fd0ccf7e82c0fe3b742a02d797ac0185a1d64a"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "11d5ee8e8efc88ea0742c895372bd31cb2654da1d2ee573f472848e49b5adb82"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3123d27703f91d9c960cdf04a5e60527c21b4c65"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a9434dbf2f6999b65d940c4203f85bc8b73314030fae833847f0319039da10c2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec7e780c41a76de10c6cb2538e03b76c8de6189d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e62d034f421b0f90e3c4767b809fd04681577c7b7d98c5c2ebe80c38153dddfa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+9/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
