[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "8654d47fde9c15545f32e0b4ed73e045e063626b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a50887a96429739c5f3b0fb8de494b9f7d1dc94371267a504cf2836f696a041a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b5a600578c495a861c736b1868d88e7b9cb6912"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "440b671ea2aa10cbdd53c8b701bebf80e71bb3bdafdb9da47a71eee07d9dd369"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24e5448638bf4792b2f74aae758c991b04c07375"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "793586edfe9b1e6d5812bc65f187a2ec8f427c02e022ee4579979df4fa6bdedd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79170fe5b3826291c2d7bdd3e52e63fd7d5d7869"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9341d87da49e5234593dc754fa682b4944043c74a21e8c583787170f9d8a9121"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "507cdd3872f08d564a74bf661cefa999a132f542"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a592f1aec3919178c0a3f01f4694892835d791ce684b3da5a98f4a225d1f1f98"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d76c1ce3e11bd26ce4e0a4d4d19128efc9485d31"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c850effe2d2175e9f17edf91493fd446c6931fd4e7e0655b319486157b0220a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0d8a94063bdfa95bc5c6b473abb23a30daf81bb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "15bc0db81b40ff131190db620a6df07d40ea69eae2785c3969e675612c2b8821"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb4e59f92f2ca7a06890762202ef92ceb4213557"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c2b829eda72947ad5d6ef0e8bd29a537e2ab311fada800fc5f752343d049c5b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab347125945d89305d399155f8bcdd39d47a2047"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5fe66e331beeb484c277a5ca399fa8fc179c56f96aba09e7f694b5fdfb273814"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c45af5fbc41c346583158b885fbea9b8caa4bdd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0d0287b9e62adf8864f2359d1f27429464f36736e78afb1e00faa628832c782a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "579a1b41cd7130ac388ea480f1be1e5db6d1f874"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9e462702e5f8b91af86a032a73c7d04fdcb445f4569fdb79dd9f877807c74e45"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90a34a7ed24395803e5da99e6dadbdd17f5d56d9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "68426044419fc1e15239720818b1f4e273187874e291ba03487e70b733552e02"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6686096f8f31febcc8e5700beb999f96bd54674"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "159995883d5d99bc0aa8d8de90f76ee9a22288343ad3492ebd6c7e68538adbce"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "755906c97a4a4c0f4c784ccf12595839ee5efd38"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "da2ec7dfd5de9e5a9157da9f45b254fb889a21c79971bd779da285a160b522d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fab63e149df5cdea986302e736baa55ab5deaf5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "127f0fe95aa35ebb9a9b8723bc4746f2ded4b30b43903c6c8955fa2e5d3c9a35"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "723a48cd7fc56e8adea2da502e72a5d8cd85cb88"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7193d50559b48001cdce8e6c4d09d3c03f05b6ea8587020b5b2683b340f8bf1e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcba96a041fdd6c6dcb984d2ba019df671caa828"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7fd34f5e30add78f6eba8d00eeac2432d833450522cb4427b71fd49472a4c0da"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21319a3230bfe18226def31f842009d5e8554e45"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d3a55d19b650d2b6003a82257ed18ef5977be642984c7969715d7938eb19429c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0d266430c7dbbc805b8bf284f53d523514ef759"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fa0c5f93414f969fdf8ded510917e62a86986c17413ea527a200911f4b6505e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "045f46944921c2f775f9f1e3a82de3a3680d255d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "2015be801f940929a1b6aca0aca699ec14432aedd36e1cd188ae99f9379c9213"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "567f4da4a007444c1576a6d1c2f84a3a2f23650c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "74b6b932c94140f5d2c8e4b07389f36aa5cc4951af018260124da536a3abd4d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdca50d83c9cff9abc42bf291fb271f657243b38"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "65d06cec1258328200dea29bee81dd94201f8d0c967f42636fe34d7f2940da66"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0df325207d27571a2106bd87442eca5e4c2ad3ff"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ae45aaaab407419175b24d970811e98bca61ee64a1f2465ca192291768c81f53"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd5a54b2a3187be54d74f931659e8935f728a702"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cd11a3df97db4a8f3e622f01eadf7affc9e1839a2e825aa18e06860ec1a83c93"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "3451cdbe85cde26ac4984d93274c9340d1e29d83"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "7eeaaf2bb110718ca0ed69bbe6ae9fbfc63eda40a3b1a03bc7749030786ea258"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f311a0cdb9eb2e1ad6af88526402e9b39248b666"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ce0052d5070c2df55e70deaf364e6f4be3125261c2b59e88ed37e4f297b29e15"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07bda7d69bd3a03ac106f7266104c0ae2dbfa58b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "154f7fa0b27d60e87d7f3146e7955a6cdfae731ec82e4e762fab68b91baa78fc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+2/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
