[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19adffdf36669a418a772dff1d4e737de7724310"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8b01e3bad348b442f86a4cce8e4872328a661c7ea7517d47932e57198b2d34de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be941b522833a6e59f2ec88bbfbd916b92f9820c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2cd2b53747fa4d7c4a6a5975c881b7687d9e1aa2523fcaee43a6113deaa8251d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91e8444f797c621f00d98795da5ff603999ae983"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4c9d637cbd16240997ead423638f83c376a8404833d261af7f880740fc4d9020"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "692d0e19d9ed67f85f9ef4eb89fb2b6921bb824d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "56e512fef330eee94118ee63b166f369db4199293dfaba8fbaee8875e12f9395"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1ba03abd3943c355306e415593152a5298c338a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0739bcbe58a6f4830b181595042042229e22981d52eb000eb541400a30253ec8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dded26ccd07aa38cbd1fef8d58e8daba80f7997"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a4797739819874228310bd2bd9e7421b5c5779d99597dd820c8635e3870b5b65"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "889c7f2464a804c15e6efbb1aff7b49e125c1c05"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "33c7dfff305669d9137896b7875bb3284bc7ffc6d0984def2963cdee4e3f4070"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41cf80ba04f60415e409f3c5c5da91d4fecadfe1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6e3c6cfb206259d1d072cca7ed973d2bcff3fd827ea1994bbec7935d55f940bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64ffa7c8c66f181dd28bda127801766206c6205d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a8fd1c37eb210a810dbcff043081d7175b7725d66bff842ac8a008242f385a06"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43bd3899ba650a9b5f1a02ced4d17ac36c72bd03"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "faf32ce1b94997c0e09fa5e1a290b505b60902a5fe99df817acd20490495a1df"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d68f7ab7d9f1af883fd7656b5d0a2a694418387b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "35e62bc33071dd9587f351ada73c390031336e0a3689c35616d3ce5f29690243"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37778ac89aa1fc49fd38c2c19c167d4bd2465f0e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "519bc0ed9e452a04111829eb66589acce31dade34d6a92f2ca96d8e63e477ad7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d5077c6e6c8dca778d89d05a4353747995ee2f5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ef58b0ace250f4816dd15d634112d822e6bd1d26aca8947a528b960a4ac14445"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f49d480a2caf5cd7ffb35e96f37f1ee4da26cd8a"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "ea91a19bc655780f3c6e7ddf6f043f57de5524425eb35fa8088aeb4b8b0cb7f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f67e9dfacd90160976d42cccaa754d1311e0ca9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7eda22a2f51c9272aeef26937821738a50d8aff691173aeaeca044887c63d7a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34c0339b17b1e20e1b9d1c03b9611b2eead2475d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "adefe9eb02b98cf887245def9d994bcf4e7ce7c648ebf3a478edb0cac4fca1e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffef164fb72ec937db353df8c531ad8e4419c2cd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b0d73fabf1f73ed2a986843bcd3971979b11aa222d2b6af74b984113a01cbe90"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60738d7b0d8faafe29c1afa5e4355836f4b0064e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "703d7cf2311141aa843ea0e050721b8d7946d6a4037c50f08037712b0e49d5a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7956f2f4544b03d2fd103c16e8b24b3bd3ed1399"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c13976f26c12f8ac6cf6e5a3643b3aeaf331b19f4b529f87c897b772c84a2a58"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "affe9445da7e12bf4023d6cbf2acb2c5d15908e3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "682eae5f3b427db9aeae53fdb7a7525e69cbdac5a0142acd1178112dbacc08d7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1b770d1bdc9b8ee7a9db07fa971cc58c7a27959"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b25ae5f6bf9f8ce2d9f372a6b6e24137c08763023322d9d9056a03477545b331"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599da7c9111c5255eb3e15d00c9e13de4158bea3"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "bd92d94b12e9c8c6024a0dc7288f78eba83de34b01b2b18feb493ee11c74c90e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e13374cb3c59e8eb1e0cb8844540a8d9ba009372"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "53aee7ac9a190a08404dbccbf6700c025d04532b7bda01da273dda254173571e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7193002baaf394052556a219ff2f3fd284cf02a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "afe102d231360ce373ca55788edfa59c63c7976af8b8ab143026b54e11e5a357"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbf2072afa201a20c11f7ef3110ec23791870e6a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7ef47ccdc9cc66a9cdbc3c09c06aa353b1c8a4557506029a693e9b049e53fed3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bca65005cadfb8a1ccc1833ed1e3675bd2aeba55"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "35f3b3a0cbb5747af77ef8aa48ec09381b5421c79c3dc646982f0a907ec4fa3f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+0/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
