[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "3f8816479d825603ae261d88b4e4c618b96dccfa"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "6fd55d3e3d595415d3e4f7ec158da0177b33103cf6bf54a29f7d09fbab0c572c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbe87077986baf9766fecebee4a5f1f59f9f6a96"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3dee0735df0b026f3dd60a48caa1bfa6ed96c1442d4a06e9a71d4e2909d4b5f6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5fbc0ca5edba6319175d80d07e4567cdcd73d57"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "848c290dce0eca4d6bbf28ea340cb1f06125ca5c0f44453ac362deea8684b7bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2da52a3e0d72750667a59fea1f929bbda0b918f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1c686653e11e8d41fa7a673e18cd78f07c2b3d8240fb1e676878c66b186e1d74"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4074dad60b6f7d940162ae156bf8d72b8e69d09f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "82291ae5f1c20ee14417d3450264a4a236cdaff8aec67bca9b9df7b00326abee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "780f94c53be071d4e55cff2cd2a3f68ddbd1cda6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ec1577691d903bc39eef950d8982eeb09d7c9d5678a52c45283c51afe466af04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba92dec9a365752c62344e715a28bad19862d28e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a548d99669d6e26d6eb12dbd0887e0e667417da8728e1f7a6328eac08fda563d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c4d9ac630fb94be26899941991a653ce70b6f05"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3662304010e5866fc7d04d4477f108cb8b9dc61217a1a8871da716123b2466c9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a02c8dcd7ca0c4ec036439b24cdee30953df07a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8e52db9c4e0d5507612ffe623ce828033e32617b5ebf56045514bed4990bb116"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef01b9f2f98cb22f8d591145632a9ef5f19dbcc8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "411cbda045ac3dad39729d6551f217179053c77bb349859a7ec8cd36f8a08d0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f89c32d6c49cde1d4299757aa411114f2934b2c1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dcfc59ffc0ab439dba89155d2b54775e19adccc58db444129738a0540f02754f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd21924f7abda27543610ab25caab49e15edf601"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d67541ba308115f772ffac284c51a5d76fc78a18f6d9e10c2c4df29e89ca4f8b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca0c2c4404a0a19d5ce05ab62a41aab88a3a8d9d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4d1af2384e6bfa88f82fa60a1d57173b03a356b7535963637a6166ceae9d1e03"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13a56cc4a1bedaf09fbc0950b1b0df05454cc9e8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5bc0902776771b4a50e8ce74bb1a3f0cba9490ae329e1ec644a50f8f81a274ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22dfa041b2cb5e5c71a70862dd8d2185fa765291"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9de0d5ad3ed8ffd1b6f55ad20691221378a1ebbd5f01d6123a425f4fdd2583d8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27757c99567f4f43ff2bcaee4f09895a7c568614"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c63ea1b9fdb29afe459766f866e989b4f2bf19666a537a06b9003850e16517c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0daddc7418603dd3c33afd430c18634efcb7726a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "07566c51c6911e56312bf4672163753bb4bc82d540e3bfceda5283401cb8c9a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2381f82854ba3237e5e01106c8c18ff595f79b0e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "deb0fa5944479295fe2d109479cc3c69ce55414dc9e3bea7290cfc2e9f637ae2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cf01ebfa9dde9b6ee5d9e994e20f98c4ba03901"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a9c42442fac9f373ab61bbbec397b99bffbbd27ed4ca1cd0ca219a25847ddcde"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "7795fb943bcde799e4fd92283836c9eaac192a19"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "92d4f282e08d6fda59427a15f3f10418ad4172474491a35126009fba71e11fa7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c2ce038100ca2e9a847fedf1412738f67455b4c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "da76c39d14a3c1ff851eeae9a1691438f14c421043e73dafc7c1a9a6e47bc4b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "facd1563d06ddeb50c5c993009e8ab1e97827655"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e365e9fcd91ea8aba0ca5f11f5d37f909a23c59256049fe32824ef76a3e5c3b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "543b273ed90e2d22f14e5ec1599cba6f75b0717a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3bd4f15d73e4bee7dc3aa58a789a3c8bcdafd64c40c105b0fffaed4a767ae27c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2858525a9eccd6c55a31446f2c8c03d1b200880a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c17ec52cba619d4b9832beb96705847e22dd4873a4734fc0fee443b0feb78513"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "87423b04bd8e61b0b9dc35751c990e7031598601"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "af7ad038e543dd0ff5f9d9566259b1e17f48bab61709ab3622f2d4f0472437f4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87063abf049dbcb94135ab262341efdd768b24e5"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0c93357286be41f0617254f927678ec325e632f325491806343acdfbd689229d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15c3690dc18a85814b37a24429cfe39d528d915e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "01a5b185ac03f32e24776cd447b4ea376b46833c49fe28c5d1cd15f484cfcf7a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+3/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
