[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "775bd3e2056989db6c585652016cd1dbd27f880d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "91e0fd95e2d11aa71d0227dbee30271abd2deede8c647fc63e8d2e21c1912570"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8224d15d1d16fa8642309ade563008ed70ffda6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "187bd2d60c40ca8f110294207740bc2e71e6612f488b59eb7806d8729ce0f8d7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c6d7488dea525ed1665543c8f0b219191dbf749"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b2168300045f668d39212fe90e7eb6d4bbb889d78639bb2c9bbd14e44372cccb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fe4def0697078269b9a471e34354a5642bc1b45"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "09cd804a02c8bfb76054be99377e8379cfb7c08b1d76f7540d6da8c2e9c7fcc5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b71d136f90480071621d9fbb7e6adcf4fe275718"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fc61fae0836c9522eac01e6cf66437c9cc951251e4e16854aa6bd4d111d971c6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73e9961db42924ccaa6624699af5335376b457b6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf7a05d09a2726c6cdbfb24eb0a0938c162ee3bda0f29267ae907569d97d372c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2484b966c71db1a6d2a9057d189bc391b314d480"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1e21bbc7ef83dd6b33e954ef2dc2b2daf873b674a5dc845d3757f44d34d77f84"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4104d7d4df2bd3674238f3dc118fab2968813aa6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "808ead7e5d05f7cd07ad68237b541112b1dc4fd8d0b483c8d43cb6075178eee6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70ada01081d32d7c2f4b0c94bf59b607d642b4a8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4b276d386a5e8e37ae0cc18ccb265d90018a430947c8c55eb9b8baaa1ff1b928"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99608b906800a3de1eb8f02c7187ce94c94f538f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6038a69e4c149f1e737c6d96cd76ea6186e8a95ca6d1a3b3cfe41d3a4e393b17"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bcba42932555043b8ac8d037aa24f7cdf31d5c7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "72c57ecb2d63c3a860e748b2355871a4a2669a8616669746c8aeb57c3dc795ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c5d9dd442dafe56f51efb572860c235441594c9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "601518e6d9ec184b79ae57289bc7d80e6494452db4948dcecff643706edf589c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb25c9e4cafbcc2537ed92a638950073437f060d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "20cc1028739ce78772332f5254cc2ba60c2494f17e6cbb3f10f7f7afa1b5dd8b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "716dbd324149edcc3077996127ca546ceff0b9c1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "504cf2af55549f28f6bf72ffbabbcedef20d3f9c2edbb7e7a6f8f40dec4e588a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7471563a4e6e17416057fa10ec3403dfd53e3466"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4043af73a0285bb662ee850797723190014e9ba35012b0708c65e7d1efc00203"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "528183f214f1dfb6437d6d34c37eb536625a0693"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "29e3d6884320a98e67a4b9f452847ca0e047115a2e51fe616d7b04c3d48ea2be"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f23595491074c4b56b785d9ce9686d3bbe9b3c13"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "fede1a99b5e4f46c8bf961ecdea1974f74fb8e5df22f6cbae36ca5d76839e23e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5de1397e71f1d21f2bcca7f5c451ffff0f81a0c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0fad6f2c242199aa9d58e94a2c60521765157ed5ac2c50280868c6c7a708297c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ae29bc8664c86f0ad0cf440df4d44e4473d6e73"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "88139e007090d73d98f3aa3a3938a5840f3032d5a874805681e00b4dc46ac0b9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "fb30e4db4cbe86900525bf39310b36549d2248ee"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "e891addffb344bd38459b632bdcffe1e95f4a21c98c6d59b2e35875ccf8d7416"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c23715169105e98d6033fdbbaff2e36b5e5f051"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aea8a00596c51d87e68119b0991668aa5bf8cca3e1b68aad4f32c773fd1e2d2d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c699f9bc783d456bff001564917fb78e4ac051b3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3681758c9445a1e462d007c7dddd91948a2f3e2bb892c3ed2320bc6f1d54817a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d415cf5c8e71f88073998ff1da219f05d68518b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6c584a8b8e07e953661f2981b0cdb90fae447588d85e3b6313d7eac0343ebb64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aec3ceb46982dafcbff27087e32a6e66b5749d9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1510136ddf344f3fb0776113415da92c9e88177e1256dfb06b024847855cbc12"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "4c089942fca0bb848ecb89b466227d212b94c441"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "bc15e83b819f635366e6ee85f3823dfed82e9accc0c1378c6584234dd35c07d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "798ea1f4b9ba3591dede60228f7f5630966b3aa3"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8c85b7880b83096ec4b43b144fc48c461f1cd69cedf7bfd9f1f75cc045617d57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a01d12be0b448210a8f16eeefaa4628917b5582"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "4c34e412e41aa8fcd213c9a3a8a354eb27b8b76f117ff2cc57984567cccd453a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+2/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
