[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "3e3e2bb47b1097bfb6c66314f32a0b8a6c169402"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "be2225b6c3186177cf58b4b71f812de916bf7577ea0d58a79fa0c331a8a589e3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47cf4a375b4a0638a74dd2529118d5186bb0fb4f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e22a848eee22cb05f07c9ed7f56de9dbea9da20dc72a8e8ae77566fcff0d37a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05ca1e1c7bf599567ef87708d537213d4ec09eb4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a5ea9279054906dc87cb7d32342ac94fefad9fe92c9e48939a2c042a017b5116"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "953052088a5aea4fd5825df0901e79043a22a60f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f96a3fc11b82b0ab07f691e60458f39fa01dbf401feeec1a0bd05987261ab83e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33a4f6cb6c81549bd4f81895a791dec13f91d281"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "733ad4e0ef05578232298d65c55aa0013884176c055e2b9861d3123ed35d3646"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "490dba7f77afe8176176d33bf8eef4ddc1423575"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cee9165deb59c028f68cf71eb717e8ff64278548eea4ebd22da45664460b87b9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ae2c727c1cbb4428af7c3d8dada699b548be086"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "345b870d319e1a58fee9c9c9cd1392e777bd660929facbab9b56285074a43c74"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b58395e8600c4dbcb336128021ff58333c26f986"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ec600ae652a6523aea4845ea319fbf3f158ed5e92376a0c0bb727d6472a07d54"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "256b3bf90d58c7836cf70f6516bc59223985d632"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6be9146dba80caf46569b3321d7d4dc2f7dbe0b489052979e20bc8c7004deb93"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e034849c8a4c34b35e06eafd8e76fb7697d0ed7a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "10802c0063431f8a57993f0899c1dcd60a10da7595f0319298e24fc840538f83"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a01ced9c2840835627c0067ad877ed764388d5d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d6ccb4db23bc2e64fc40a8eb623696671e8ab6e8ef120feff214b7b96985160a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5eb3ab4fbebd7fb05fb1540d07e69c4aa221b4df"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cbd183d1a86f10cf489ca431d01d99e2321f2e086800c287bf02f1e7234b7612"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fde5e17f4c023f77e0d58246b3c39c5427836616"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a7b320c9649bc7000352aa175653aef62e85c87bf8618a60c68492fec4b9ee25"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e4965f163cc2e36d2d26103df39483f9b4ae031"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "70d462ae8ffed420bd1df2db464444dd3c5b7cd5efd25500a83417e2b9b8a8e5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa0a196693547c1261a627d583917a7bc0c06dc0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4519d26c0ed2be503c6265e1f581168e142dea1531c29c76458b0395873c8a7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1f7a7fffd68a4e9a51080d8811d7c5f4f7cd414"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fc1766e98144d37edff535ef073c051bbd3e6f4c4be7a4c59e176c8cb02acb26"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fea903d95e7d4c8b6ffad33330f42d9cfe2f5b90"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "272f2fba1393478ce0f2bb4ace3da5547bb0430d61df02621c5eec76e807b5d6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af61dd4cbe497d985ad4712955391140f241aee9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "437641198bbecbad9571309f37635a36a34592e71243902bd25cb5b02084025c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2f5862462d2e4fa231a74502804d625a95d0003"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f564389afbc2d547e02e93f0270b75913f8c0a13743a014604d7abc9dc38acfd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "990213e0bcd480a53c568f74fa4e179fa9f39a7d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "62806fa5f97394906b33d40db0a895cf953232954d6fc7d4d084280830e762ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ec5b6151056331d62af7c3a49380b81dede52db"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "39146fb5ad92f8032d65ebef8b541163905eb876ddcd3c1210fe1a8d0bb933e6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "a7712e6515148f4adfc37757050c340909162419"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b7b530f000f3a0ab8312837467b73573aa0b347602fb6e568a94800ec2fde6cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0681055ac239399a27de93b11298c8affe94e111"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "675cbfc74ed61aa720879ea6e71d6ef414e0685cbc370db3cfc05bdce22eedc3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f786d06048799ceec04e8e6f903bd13ea7c4f0d0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c01ab6c840f00c7a780422aa4b34c26ca11702125af398de826375ceae328999"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22b3b0ea7e8115ac02b05cf5485c093e3bab70b8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b321fff0bb5df7e35640fec2076c7d2027e00e57dccec9e491494bc0864434b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b531510d686e50ecb777f4837fd7a052d172a6f0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8de4a7fd8dc1c20e946bed6c83768ad83249bc2ddea8e6cc07afbc6038bfe126"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "905e6dd948283b0c3dabc7c5a8fd7854b4132920"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "44903326940aaba91581a91cb2996cc2789a41ce8b7857023cf8db9adc243ead"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15d9afa2cb82fb59f756c69aa94ce3322c347cfb"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6ec46fd773cf995464cf9410f4548c01b13c67866083ea7a53f5a5196cf68ae4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf2b91bbe787a6db1c950371716767e55598d033"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "37a104929aaa5c4c86a727704924d6cb6b8e42193827066dd825c8fd3daefb1f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+2/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
