[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "c0f7fa1088c5ba07bb1dabb70ec331d1761b72a7"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "756ba9339673b4ed12370958a7d2a3601a9431b28aa308bce6130257c5d3fa31"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef143bf675adaea2853ae2973df05e9d046cc992"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3f51bafc01a16b992957ef735ef8473b93fdd3761fd0d6a440d1b0227fb5e167"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "301dc8d59b07c9a7d5f917de25006bb7eb09a94c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bcd5d7451bccc21374c8ed2f6dc88d4721fefc80d2b622a18803eab15b119719"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "885e17cd2ef474ebb5eb06488ed3ef6d76194c8d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d60b11d910848d304be04449d7b72c8a14820a93bfdadec7716c78da6c08182"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "867be49c10d1420ec50fd9e6a9891600cd1df36e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2e5c6b78baa20c440223e096028efbc2cba8459789391dc19c0400d85b4d04c4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "9164226a3162fed971e97a6953c4a85742be6214"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "15e8e4401d0fdf9774e1000488a819ad389a24bef31d8af50d1bbb25f48a6738"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c92d0b945ed337714027cc9bb9a32ab5e112af62"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "307f195e87db2e88b27a7027868e0a06d62a0163a83c0cf98b09a1e893bfe067"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2836614b5dc73152d949c221bec92f72b74156a7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "77ca1c0a36be8d0049c03d4d60a24f0cc6a491f3eb545ba3615ad6215da0da08"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6da5fd26ab0a55a7f0210f88b3b0eed8a2b1e75c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "03e3488d0019795c2cd3906517ab5b557d1d3cb1818743041829e808a3db08da"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "532ff4efc0ad45ec314fddb4e17568e0412537ee"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "57f9fe5465f7fb0aecee30ebcfd223807d5b867b94ea34704c333fd69e3e8e3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c5fffece17be9c2a3795f269340163974585097"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ab17588335bc55f11aff00e91bf0139c4c7b9a45c7bd69cffd305410ea57e296"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e79bf0021b2414ef2026641cdfbb38d459267950"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "930af0f38b27b8bb8962d075afc6ca7c201d598adb975e485b858e0dbabfc91e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6ccbde2d3033faee77a0635ad3a41612b47147a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fb3cbc4911729f97628fb53ddf91f914440ef3d275616c02f0b4a4323d434764"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1af9fc8a27cc75b23d5240279eafb7bb736bea81"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7c505f5c1da40b93e18afbcb97d3634e4302d52087f13b4fdd709a1a5c6ac299"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6bdb94afae63f8411e9a08aa9f105adf2984419"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9a35ad8963bc0cf27b4dffb7a9159e1774bca3c784a530a622dbc594859801d3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b6a267b70b32ebb78f04c1606d8b9eb75ecf0dd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "15ae7ab2cc922fa59c243b91eb5f967a0bf0ad0f04903ddb067e07b723139649"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1add463712b983bc7cabc18da9a19278ad875998"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "aea87317aa707ff83d88fd570670b52b46ec4ecf4b8f82e3995ec6980ca13a1a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b4e46941edb7fd3a4e6b9c9e3f5f52b1314755c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ed024ae38b9fbd25a1b7c19d8e2f1a2a4b24420aa416c43349d7848d6663b372"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ed26d1237daa031e8fdfab1ede189d15a6dc412"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7843ff151d60a368f0495350ef9ce90cbf6c009706c33f1d6b5b7cf86a96b198"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "756e184ac102c83bc69c5f8bf443b674ddca84e5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "32356a18866abe0ceaf723a9f085fd934ca7c9b884505c76fababe76bdac27ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74047abe32e8fc8161376a673c779914af7f3b45"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c6546c043f454a94b1cf4aff08cf0ac62044b084d663cd66dd661ca0d4437d67"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.riscv64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6e3cb4eaf2237e82a004ea833d2cd4f203137c1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8b2f8bc10716d6bad2c7b75c13d6fc6c4c4ccf299f31de97fdd399ae2a0750fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "7310c4a7a5c67c3b22b48c01be4cc0c7b51f52ff"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a33f9e9d96b9a421bf98acbbc1aa4fe6e04fcbb647f701dbca1efba640395481"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b8fd2c854b24d8ff028a31e7e2e4efac15755ba"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f1175a449898fc64b8b5d70525fe2d274816c7789974fbc096d8a0356e9a8400"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4dcdbd63ddce19e5bc4d33cea396ae0a53344d1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "70faffbb810beff8a399a60a20214dca3b2b23db06c6dc54651211264aa3513e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "030f4af70d2f440dcf60ce1936a5edf1ea4146ef"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "486b8eef1b2ed53bccab1e62ce9cce24053768e2e436ecac5b439c89dc7c0a96"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2450725117925bee5a9cffa7f44489689445fcb8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a6b260cd0af18bb31b857ccb8cfdbc54b5f9896c22582c8e242af1d0a21dd4a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "db633b1d6a7d7edc65511d2f4379f8f57209d1ac"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "4a5e76e3ae6bd8306f6462c1e33b81a149e8ebb33dbddc3f63fb5b2139f0a56a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d0b15bd9c422ce292ef36fed235a9f8368307fa"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "30d98db69704eb81d0373e059e99d700ad357bbf25d96b1e4e9f854e69f96f2e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73501ca2e1f728bce7810f9dbdad37d695f3feca"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "dfb5296e4ae37543b5b265fd3aff518d8e7694237d4967936fc9f2852fe99bfc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+6/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
