[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "03178ba795d55ba102446a8eaccae5b1667dcc46"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "c53e865f78fd22ecf98c035a436adf9c47db4156ce04fb103014baca9712c508"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bebd4a3ca8fbb0f690306159d49e8f628c609f83"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "36a56a3168c5951803620b0483bd9f6b5d0b7966660bca53badf55b502bfaf7a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be6ed1efd94e9cbcdf0efe7d65e09b4c3bed4660"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8e8f7e6030dbd55a2d20b722cfcbc1834cc4d106020f1a57ccebf9af76e16746"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0bb9b9889f2f022ab0cc88aee9deeea2083d8713"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "05ab3f303063c9089156a3ab603baa898f1ede204797428536f44535d56dd11f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc925be812285c2e97d80f61100e1e3eb26d997d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dc922914ca7e251d2e958d077754fec0e63a3b02501ee7ebadc081b6156bcab8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "2911edbe778ca48657f0273fc486a598f59ff2ec"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "c650a027f7e007136ee2efb30aed5ac8bd7fbdd5ce72fe4c6c74cd8d06aba005"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0b5e2db252c04191a4a16fa02e6a9ed8d5508f1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ad95dbcd8f62ba98dcd50d6360b2fbdffd30c30142ee4cf16b0db3ff93902b2e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4da4fff1ef16c178dab4f9d86d7af824e1c994c0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b7eb489889235bade9d699564a6d3345a790662d01edae454e13dcf33ff398d5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd992773c034016c1275c6ba2a32b71762c534d1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bf545a27ab32a6758615d9096aa222ee011b352abcc79c65209450b5fa3fb00f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28ca15c21ab84456f36f9a461eddee81e6e3e318"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "687ba71b0ad8c859092348b3ecdf39c6f0c4b372cf68932a6e04a2153a812584"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73783a4fc419d2b543c9a1353dbe88fcce45ffd5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0d649488e9b6ed92dd9a0e229f97501354d461e44a8dd20826c4dd00b4ae9a52"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "036e58ba5df38a32a17aaa02b872fec3a5171f76"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cefc3639fe546133478c5b5b3cd95d15ea9f5917930cef69ae42484e0177533d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3d59ebd20763b66d7c9667250b3a4909cf2fa58"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8df5db20bc5bd576031f416295fd37c627669b25c74e3168f65c9b6c3afade58"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f5b3313c99f0f99e694aa39e81dbd394ea9b2a1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1a89a1b519bc9de1962e0568cbac83ccabf722155e6b124950184ce31bdc476a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9246310ccbd4163d50ddc40dfb9490384557fe8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "54302a02886e53730300606c1b7f12bc41c0a440c5da9df0239ff4a776a50a7a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d94e9fba48b272e6390f18a07a4e9d254d31944"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3121c45d18f6c6329496f478602415879fc88dba48cf9d7001656cc3e8b44dea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebb21f49a643322d8fd720de9c505dca06d78858"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f22b6931e241edf3c6a30ea61f093a755ef3a4216b9863e656bba7589960aa44"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f292ee00c416a65d31fa8c8d2a4d56ff532e350"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "aa1233a5127ea9f816bf65387c726243e9a4e1c1d25fb950ca55a4ffbdbb30ed"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ceb9241dddaf3a2426ec2eb0016f01d8eb820fb0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "58ef3a2465c8a2a3cb3f717bf6a528b31ba50ed53f3d663a68c8b64a97145452"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "936f536a5b46d6a6abcb96af6e1fb3cc194f305e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "049c51cb97b7c1d8bbb75487fdc87168f9b7fd20eb58aee974abf43004e2799e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b01967d6ca00e597131b897c50d539cca7c445a6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b1c9385c4806b1baa303d4a7edfb5d7d6376b6d94b359c1f7b0428c4a4b57a3d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.riscv64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "355456d513d440c864c61d5f4d01c2ad64eb8a04"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0929083e808ee7106999c0c3c11335bd3a97d7d7eb3445a2386a05b335974505"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "8607d7ad7fca4c596d4a472b6e3fca3bcaff2d93"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7f77209cefb586dabd7f6d865798b444fc92f6740d9585060593242fcbb5b090"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c306ff5cd8cee233614a894e3867aadfc174a05e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf351bdc18b8ea8d5fba294766480dc4d7ec38955df9d2f12c2c2c44fab5857a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7598e091c57c92f3145de870a38852d0fcb7d256"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d786677ca53638c09ca80ee27bab2436f3e7dc05ba2a7c8583c7f0556538c90c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed70ca4700749ec81c52010e025f2430f57b0686"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b426e846e27b31c7393854751e440a4d54fea5cb9979afb5280e938a9ad94514"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74af81871451910f91361e1d453036218807eab9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "85dee4be9afa9f75f78b8c383649f4e6aeddea64e8cba2110e39d10ac28879c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "bdceac6c15c371d8490d69375533d3b2f2a3d9f5"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "1051bcbb3f3b0f40f2439fc275f18572da2ea36631230a7bb8f7d407ddb1f8c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57bf10c0382bb2d1f2c68d9be349ad284e02fbbb"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "1b15d5d5940252307d98d6ce3153c726ddcab8788605d0f06bd1bd2e841e8382"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a31fde35ae61c78ae4cd2f5ff2fed153f7297407"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3de5da8b4f4a280c35f12de9a084c090e603054b527224e7d2ff556a219feb6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+5/LLVM_full.v18.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
