[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "91f8f1ecf6ff4df494a02334e0913d3a726998b3"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d62dc94b9c0b6db4046f0a06f4f60af66ada5f598c232aa0c128e8ba166abfa8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42c2a0f8d066734380b4411105cb90c5dd507489"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b882a4c03eeedd70b138e93abb9d7db59859b5920d1e39fcfeb03d0769c4156f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acd5799fdf71b0e249780dc803b5ae52b41dfeba"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0e22b43ada076f51a621f21600a56299f88a66cc8839220c4a4641baee9716af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ca7ecf662e88fa44767785643dcbf5822066983"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1df2b0f5144e2f26f06fc636603cb0d028ab7aa385478320365fd3e93cba46d5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c16d18daf112b5c04cc94ba9c054bb6769ae779c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8feabaacf5cd7b71ef6cdef5da4b2389e7fec90de5bafe1bb6c8f6ed056b05eb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "495fdb00edcd710c80e5b9a4aea46435b9be9a61"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1b67e83d3bc3d72dc5d5b6b2aa9d2b0ccc7b7fab6a83600b642e71ee1c824914"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27e9729f8f1d1081a8f6f33b98bfe722f4673cc1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7723a9004a045a7f4e04bd2f6a5d1de7f73fe47914d37a8cb39d13c9708e5a81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b83164bf4e188f72b5327e6027a7c9883382935"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1da3a52f3a4411e371262779907c7099a02ff95484161de47556c7a0bd68b550"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c47cfcc023c68d53d5cbd64efaaa35317d33d521"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b6e68a815da1d9ec52aef94e45c8d9b5d48d21813b2c33a0cb6db7397be71a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6eacf92d25b7d6a883552c8bab326425fc4806f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "07cfff8690b91c8af50c0f0337c410e31be1496cd15eb49bf743544c933d2f81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b17cd549cb4ec4d0858e4c38191541751d5dd2b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f0bf0e267746f565317625327a8313d8c9f89c74ba86b092a84a671fa31b719a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9239f78c296cd3817bae40edff2acc46bc23fc8a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "812cde79dc4fd8020ac71dcdee677f985deaa9f292059e2c57c9a70417cb755c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "649c99a08c82d77cde27fb773f5d19f165291733"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8a421afa095541fe86bb0c67f70f5158607f192b2252548940c8255fbbb74675"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c417e1878e00c000ac67e4826c3d029899ce12da"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6c27e2a49d7b1185843056e9180ee720b2b18a43bfca351c79a6f0752fd7f135"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d46cf7e2d729cb467fcfcd5c6a0a5f8e4b2c79fb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "da50d8c5c17d52b3fe6b0de7afdbdcc819f283725edc8c8d51ce887c1c3041c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21de23535dec299640237eb2bd01d5ce6e6e2329"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1ff4a710f402448096cfaba473e16e18fa74a8cf8a8a72124c3de66b6be46c9c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "302e8eb050d56527faa468cdf95d4036b939f1b0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8f0d516c16d9701db9cce4318431947cd36c4a8a0be40a69e657b0803241ace6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3258eea2a5c6aef231fed20febf50d409b74bc70"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0e58233dfcd5e96746656c1d5a53940bdb4deec0aeb5f919372b3d38d5af35d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfed3f16da7823695b271ae1908231d299f77a09"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "fe55b4b4eaaf20e1706899d8d61c90ebecff34aafba7447343b69fa304e1ffa1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d21a5dafc1b9c5cc12c2558642fa22ed8308c342"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e4e20637960ca8594cda9801837872a8506a4b57ba7dc5de3a865e55f7402639"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f372e41b41ac632ce1fb7402b3e5d2b0614b86c8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bf81cb690bdc2cf097e10935e3e0a30e74a34443eb7accd9e689562a9f9088f2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "7bf25ad585c8ebfe6ade143a22b38bedd18cef10"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "e84c6175a10299d3df66a6ebfc33ab8235809e8101a64c92f654b127c1c6790f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdefdf498ea5760cd0b44ae060e7a8e650172e71"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "14a00b42ccd496c8a88c8651d1c532d7f840d2c009474becd09f518ddf9ca187"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05408f652eec1d3554623238ee9468608ef4e16c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a62d35330b02dbdc97d0cd2c174dc2a67af630801bf8746b89a06453cf834780"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01b189c3943b4e26cba5b1887bf6ffcaa1b87bdb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ed2851357dca9d219ee8d2c536a858d6c96acafdff1fd2b78fca8727a225bf35"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40dd892eb6110a8586bb0993b5f122b9f119b927"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8acafe74946e3014eca397892bbc215aa4c5d30b25e1878514ffc298694b7031"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "750bd9dbcf7d50a3d917dcb3f7c04413bd26d409"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "d9d648ca6644d806c900fe4b6f71d3ed4f74a0b86e9b0ea022f7a5066b9ee6fc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d579f6d65ac68246dc559ffe9eb673871d12a89"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a8cb5b8215adb39f02ccd1e290cceb1abbd2e6f275d6b5e0476f6566b8fb35b9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be8c5d37ef713f89f28ba49c2190849710771f4b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c28cdd26906871eac2e4c415433e5879588c15f6a2d246f64843d8d1205b0197"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+3/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
