[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "20f7206221831f7b2270fff742d333408ff44f1e"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7e7abf2012a1e0770cdc56d5bc6078b3f3ce91b971678fee1d064b66fc9bf35a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc1dc7f247745e89c8c59abe7953e94bcad9ac9a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5fa44cee937ef060425123136e614e44886cbefe0602734bd8766b87b927603b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "594320f191e451bee81478b4eda84196ea8d8774"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b69fe3336052d1f98e95644b9b8301c006a0318862b0b606a1267b52d3e66c04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b87df05733817fa9846a2c1ec1e63506b5210ed2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b73b901ef3ad3293ca94c12d2d8af659b146f0def13f3085666f1f3124eb7cd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e7f8d00b443fc43dca79b606d42088574f009c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1e84f9a9b1fb7e57ae88c2b2444bfffa9a813cee644e01f737d9ba65ece4cd71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bad3718361fca0ce44a9658c392944164cbcdaa1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1907fc89e492812f86cd90be889a648f2a3ac07e32cbce3ccb40e20089b33f2b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a1be0bccacaf50d235aa82d9e1600b208c0a75f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7b8d30852bccd9fce7bf2935d0a09f715c6c314ec2642d526fd88771ede329a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b966ed8063a94d5df192925210452d5f3453b859"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "65486e334ba55ee1806bcb15ee6278d47913e2859aeed75d28c905f5a4b2f9a7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a077a51715bc777dcaa66554d2859e82c0d9d32"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "569882d456ddf89d25c80db4f62ca23b62f5e0f2a40b890d8a720a694b6ef7c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80c6eab3661e2ed62b58f3ba554547ef43fbfe43"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0b08e8282003b4a90ef1310588e87438f8174bc8fdc773a6397eba21d6e7ed47"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e536dd06ab119338d0d8acd235808fc4b9ee53e9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "80bcb237b6ea4752220e4dd479860b1ca67f76a583cd11307b8b7bc12174fc0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "715c0176bd8afadcb05a6bef4732ef72495e5a17"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3ccdb5bd6358c8ce5d0419991794f1605f3214d29280c5ac882ae66d77e00d11"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "727ab4f8752579c3ff6511287aea3d893b870c2f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b989bde99ac47891f0dbd1a66c62a161fe68cee786d9e02ad85ad4c5d288f961"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3ad86ced678ac3e02eede914e4d318848146f82"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "93db43c424c9ecd6d7dde550a6421819c00406e5919cf6f6c502c78c21ed9853"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f5fe998b4cc46fed86d0c56badc70f795304861"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d04eff77bd9597f9c594f7728b961564d7ecd9885e8c6fdf0f2e832bcef8384e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "863760bcd3e56c6f6cc7dc4b4cd4888eaa708715"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c8e47746ac7ec44474e2e165a40de6e547f1d85f76689c32892e1cb7e8c502c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d978932ef3fa1440c73b2a1f8870a023a37bab5c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d6df312f27b659d16bada61aa8b6c53aed478e2fb6d4b4e9eb5b8d1cb498129b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4b21f418536dfee80875431a8aadbe01471d338"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "dd64610efa3912480dc7d83b70bde51fead8660eeb7bdb769969a06baf7b0784"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90f122945aa3780a5fd15ebf004ffa9d8278ccf5"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a4e95f2e4ea604720354c4c1e0878112a3889747cc574e00e350ff4201b03d7b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58bdb6c91ca0be29cc31d2c4e610b03f8421f0fc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "893a152f650995a982f688938eb134cd70265bdab405109d587ae36f45dfb65f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a5445da0fb989bb0282ce59bd88d251296892fa"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "567d669a463195c359f0fd76d885c2db21857a31a54101ea3bac0bde45baf6c7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "1544283aeecfb1a6e2d10864082f1f991f749394"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "8c9626252a132a8b0b75042b836bd36fc45ec0eb317095dd2ae51649d53d16e5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c340b7e028532ce722be922dc025d3e1412d0e0f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "40ba67acf2c09a47c9f0db4554da5edd599cb56fbf8440f7ea16a73457387f64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69aad9adca4f521d3f129ab6d268295200202dde"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ed66a77e79bcfcccdbd9f9ea005ecf7046da9b1bcf30374ab40576ffbee5aebb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afba966377867570a543fa0cd820029077dd3720"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b8301dd11ecc01780634c4aa314b06a8caea40c4864405056dc2dec9ba88843"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ddb0d87b50f38185b799ac94d9581f77e4fb92e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "684212a5e431132db18269241af9574ef96295282174c33b760f0944b26175e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "0e0ebb222c8cf2ec21525289b620e9ff0261a77b"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "e10d9413c4e61f2ea79b53210c4350d4dec6ce6e10830bbc65b78fde2068f9ad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d334fac8bec02f6b9c9665a71d742950935b1a9c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "335500cb75ca36915b12029cc490bad28aae299d601c3db16fae4c85ae792dc6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47b96555996e80425685dd1a9d93c5d902e179c4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9c0f1609087134556e1006bb3c0c6431435fd4b5d33ec96e4aabef8fa7f76f6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+1/LLVM_full.v14.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
