[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "c7a5fd0c4041d46e7fa3466cbec36df4a9148b85"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "98c22849a30e137c689e04b0fb6645c4e8ec4db8c8a5e7ba63c41a7c2c84288f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3325e9e990ccad5de26a39ef55ae05c7aec35770"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "61826fb3f14543c870a9a7c28c957679be20473357574d47ba0f710243f1d290"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "973df41da6ce56a4b33b2ab943ec01c5dcb3da78"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ac5a1bdd3a57540e13a518c07550f6e24054bcfbb977c0b2168f1ec7e23fe6db"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2c0be9538d6419837dfaa3fcb48f1922da43f33"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d384b5e58f6fdd6f791d0d49d61af6cb8b5766935435e6bb3bf1fe823e728d40"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66c2a1c64ceac7128b51048ac441b4d5dfdd7163"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "de562abf6ecebdf3a9a15452881107513654b7389460cdd168fcab1bd0636979"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8886757c458a0b2f268bdefe6460bc8e459f5941"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "927a7ac2b8ec158664c56dd6b0e87f2b476f95d10f429b3ebe3d6f23716a008e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb7c33c8668e83def927bcc7be0cb88bb67c3c2a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8a80049f7106c15abac8c84905ecc71a740b2ebbb1693af9446d4defadcefe8f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a0e0929fb727cd245be6e33a183792831c7fcd6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8f93c0bbb7f23e8550c8f1fb9c53d4837ef1954a59870310d31a8d76fc088d59"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13de81a0c528432299609a3ad8750395c34f8ee1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "048c1239a3dc35f0284dcf6c483762e566343fa81636591fb6eb5e47a2e8a69e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b179616719a9ff23ceb530d10e2c4892b2e965af"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9ed15f722ece4007773388f3dafd09a146c7eb75166066fce57493353824b528"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1faade45d139d3b79ba8d92a5f10b92fda6f6ec7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b84a3f8c95d6f91a774c373c525ee926bfe4077ebbec465222badbf42bc3d46b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb5629647cb48e4aaed84fa880ee938ca32e1c2c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dbea741913308c94be7191a2430c58ed412050264e054f9a85bb2be83ca40aef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43ef7c488381cc381840a8b89ecb24f70f9338e2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b3fd316c97970914935b48bc86d452d7c1fe30904878758632a5a6cc59613c18"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "063c29d9f66e2da938b4df706dbbfb41299a4406"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b20567cbaa8cd0429ca7a13bb2ddcda58c1bca2a65440d8e6826612f785cb7cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd71cf4d65e3a5dbcf3a43d0098ee214a5a3cdfc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "86db09e57ac128533230ddd11dae35e86c0df0a7560c44a36bb572fd1304e656"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c35649c61900ea6ee640bac9dc939274cb5ec33"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "47f752835f470b46a4097756c27bd34dd64b64a7ddd9fd00387b2f9b1f2ef81f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee9cdfc2c339c19d5b208001c37228cb384d77dd"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "79e1bbde7f9b30c2d4e2759cfd5794e8841cff0ffd960b0b49604c582e4bb538"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce04608dc535e25de85e45a14d71ef0c824b72fc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "666b0b52839eb0d83d40660f294adacd2ba143350786bac606ad8b9880ba201d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0c870f80f3ad4c84df893b55ad8e205304910b8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2a865367d23431c48e94fb5131bbbfc63f9a55de76fc3657f4b5cd2cf5c6340d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "5b07b8801436b326e091ec1ffcec0b73b621eb09"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "f4002b5700e53d352eb8a0f4002931a48d1671913d15ed726bd1f21f241139a7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8eeb8e7b38b29e13fa32e40c7ecedd46bb034d6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "db390b2b6e751ca2466a1fc77a85646c82842002223f8066578f8a4b61b60cd7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dfa845f566fa8a2059ba9fd29052857d3114b8b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "41c68e45483dfe6164743ea7a3e51708a79eddf3071d7ff82016fcf4c1ea0dcc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af07fce5726c1ec89a657448c7e89194d523685e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c97671818bbedb8c32fe53755f40ba3bf4053290d32f5779307ca396b62d5d25"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc7f3b5f3ab792d755574190fed437b788a18b04"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a307185e33defb6b8378b7fab2a302392fcaa55640a831b58a069fc9284044fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "20e4d31965629ccc6b8481dd2e219147172e08a2"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "700da3d480745d21f90581aec947e82a984cdbf9eee932162a0c99c68cd0b0cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27aa61e75c19253975152aea46a2865472e1b7ca"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b7f81309a542dabdb23ac67fbfcdbe863cca0ddf5839c77fa79b9fd4e3e1352b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5a2b9418239a02003bda5567d135e9e28ad1480"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a293661a3cd8ad8cc9f87d78b9f73bb0ed294051889075291b3487926e728615"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+5/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
