[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70acd1b7da06181bb92a2d8481877bf3ab83689a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dd14443a971d03d35804340ca7e6ebba458ffb29711fb142647826666a8635dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aab602115ef576b4c5bc17b3e9af4990e8e621e9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f330a0a3c295ef8d3f5729f9608aab3bb42781d96cc52fddf211ed9d13d58718"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b1998eefc326b9bbd653a4232c1cb2b2c555c90"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3fd9829a1acbd6b635562518ab4a399228f4d860a68e0d2aeccbf1db75400643"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4c3345256961a69a026b5ad429c650dcf802294"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8c8b4fec3326be0d03660c44b8e7daf039c6c6d20a8f6b05dc76ccb3676e9521"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb030c0e54036fcb4bf870a38886c5b44bf31c19"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "53408a74b1e07bb3727a42f43fabca4ce8442670725b72b07923c8e4f6cf59f0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f79a6eb76890b5ef863f6fc19e1be745288f20e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ae7c44b920c5b96804e994edc4a1d9171cef89b1976375bef32217008fdc4ee8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fdb26e3542183257b87d0bd7a7995a759914c4f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7faf48b9db12c67e2787a6bbbfc9c19f8b9c4164f4e903122015637e5a005cef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06e87af5bc0fc1af3379d2d8b7c084ab35aac1a4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "afc2917ce4f538da1ede6d0b079203af040f2e24da8187e8963b03d69b87cbc4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ce261924ba933c2d9dcc0ee9d24238396a7b905"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "ef2612fad0a92a50d87dcaa88db721fe6ab52ceea64225d205ed18ac81344c94"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac19c9058bde53499a13da4e26a5d7c5e122616e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "42c16a2b6f2324681338699de644b8595d9dd62546fc33c5ad7fb227a6977b79"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1710ba4d4d51067c70a47f353eaa82acf052d47"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6067af78f80849f552bd06da363d176a5b133701f489c270e9c2fb8eed91ce61"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00d8c878aca79744ad18d465c4d7953fc031c8d9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e3385ea38730f2b0b692f9acb925c5e35a0373bb9ded90ec85b1d568725df434"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5984beb8a3d527017634bbbeb6550f04d5cd268"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "427a6d2401dc266a3abe03779254cae361d24d04704a12a9fa9687300a978301"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1632bcf33e6e2b94c392641e3d3eebaf985ad1d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "745a46a4733b27cc16c4a8219ce92e820ab95a9fcf4e39fa2e3e39dca8408e2c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0aa61c9902dee6c80151e71cb1d7e67db23629c2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf816c4be3b00cb0ada745c9b21fc2de5f3275326d7a7b5b5f640cc6127f6523"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dac0d6cec636051dc8c29de5f9298421a03b1f4b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "58667a355cc257d206537432e94353f9b97c9d58684fb714b1eef83473e19097"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53a59b9aa3f8c4a9f20c95395b494bfc1c04d505"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "b7e46498636c55354ad8eefd1309ed2c4dd2d145b0e687257ee211e0a9f26c0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "439a544e24cd046e5837362d5bc3247ca7900f59"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2c6c584bcf1cd62b5bebcde9914f9c5dddf5f11f6d6c5a3943f54ca18689a7d4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f17a4ff543f89ef8c30a4f710aaa46204b664b8c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "69b2e2d1bbd61d027f7187a200cccbb38bb9556615ec2f4555b64ccbf5cd12ee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "988f1a813fdb1b0aeabee9695fe974d739db9c07"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a5578896984e15402bda7df1f6ff02a51722ac9206d787a68c0c55f4bd628676"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd444cba2d1b2c1d67888445661bc6138b780ebd"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a04f5d5c99ef78566c16b4ae7a0677557d5ba78e8a65cf4145d9bdbfb0f79f22"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c64e96df63ff713753194b1ad1704676b25499c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f8e1ba11dee9df8d21f303055defa8f1bd635440bc5895a4de2a96e7939d7a71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed129120c04e601a9fb10211d412194e8fc30865"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "064a6a0db517af6672ab2033b4ddfd9b31356ebee1f589a43b80b4766de99b8d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e66bca6631cf51c9ff231eac446eb263c902d8a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "47dd1ca1d4dddcd61c07e53cd14afa449eda1f2a0d17ef501cbe08a67319d403"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "603c41ca2f32df35980a91cafa78182917beacf7"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "af4a07d6a7f54e7d63c19559b9ea4053628d2702a08e9e78228f6d141200b899"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46ddb4a76570ea193469f2c338dcbf62aa89cc0b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5d321d0e5d9a35e730a9910848efa5b76699e87e0a6499c800abf3b5eedc83ad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+5/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
