[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "775bd3e2056989db6c585652016cd1dbd27f880d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "91e0fd95e2d11aa71d0227dbee30271abd2deede8c647fc63e8d2e21c1912570"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8224d15d1d16fa8642309ade563008ed70ffda6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "187bd2d60c40ca8f110294207740bc2e71e6612f488b59eb7806d8729ce0f8d7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c6d7488dea525ed1665543c8f0b219191dbf749"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b2168300045f668d39212fe90e7eb6d4bbb889d78639bb2c9bbd14e44372cccb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fe4def0697078269b9a471e34354a5642bc1b45"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "09cd804a02c8bfb76054be99377e8379cfb7c08b1d76f7540d6da8c2e9c7fcc5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b71d136f90480071621d9fbb7e6adcf4fe275718"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fc61fae0836c9522eac01e6cf66437c9cc951251e4e16854aa6bd4d111d971c6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73e9961db42924ccaa6624699af5335376b457b6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf7a05d09a2726c6cdbfb24eb0a0938c162ee3bda0f29267ae907569d97d372c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2484b966c71db1a6d2a9057d189bc391b314d480"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1e21bbc7ef83dd6b33e954ef2dc2b2daf873b674a5dc845d3757f44d34d77f84"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4104d7d4df2bd3674238f3dc118fab2968813aa6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "808ead7e5d05f7cd07ad68237b541112b1dc4fd8d0b483c8d43cb6075178eee6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70ada01081d32d7c2f4b0c94bf59b607d642b4a8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4b276d386a5e8e37ae0cc18ccb265d90018a430947c8c55eb9b8baaa1ff1b928"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99608b906800a3de1eb8f02c7187ce94c94f538f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6038a69e4c149f1e737c6d96cd76ea6186e8a95ca6d1a3b3cfe41d3a4e393b17"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bcba42932555043b8ac8d037aa24f7cdf31d5c7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "72c57ecb2d63c3a860e748b2355871a4a2669a8616669746c8aeb57c3dc795ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c5d9dd442dafe56f51efb572860c235441594c9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "601518e6d9ec184b79ae57289bc7d80e6494452db4948dcecff643706edf589c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb25c9e4cafbcc2537ed92a638950073437f060d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "20cc1028739ce78772332f5254cc2ba60c2494f17e6cbb3f10f7f7afa1b5dd8b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4201ecfb17df318a7a490453c0e22b694d1b8e21"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "024d3cbdc8621d107ba3df28acc355adb5755c4ecd5b1501afe2e5c1badbc9fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1301ecb01417a94e7df06ff62578d2c0723d1f59"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0c6507cd4734ed2a89ba113f7dab80374b0a9e0e17a1f8f9e166d60957319f40"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "deeb1b619feb74669481b82ab185e3c4431a046d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "32804fda844200c2272980cae3c8b7500f4b8cb9d57945dead6e887a6c3e3e3f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc8cf762f0f8b04f6d273a5539bfd200e0510ed9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "00ebb31ce0468db26679901d519bfef21ac2faf86672fe85213c34875085d12a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "214487de8677334ab7a41c3aa6f5534bd7e86ef7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "74554901cf01f9234e7f0c7483c9eff1b781146039e6396265c4abf055edf914"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60f0919ad3a23aa8bb22242b37d51390e20754c9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7f3658c905d0e8f1289a2b8e5a8424aeb3840ce1f9708d8d1dc3fa652848d88a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "68bf6485558713975d0e5ee1cbdd908d7f28470b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "0df6b037dd50f06797ae10eafccba4138926422a36aac1e6571064df8a15c760"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21c5f097368ebd39e28b53d62ccf7f0d947d1cab"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f7a4d69d9ed535f7d05b6ca7f9db2a86b97ba570023056b946172c9cdf7c1d01"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98632d0b8abc26ec2801765f30409b86fae1beeb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b65fe2743f5e9cfc378eb13ccad566b29e7bfc9395746e5f128ebe686a0c1f65"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2500d75dfda7a3420b07fcfc2cf498b1e89a8183"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "07e3057d4083cd2f47d6b6150fb7342673ba0d08925fe4f707f5d962d5fb39ba"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ae9539ee61a9c5d2974de85cc8faeca3cf58c34"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ea485225112c7ef204cdcdb12329adff4ae06891761e3ca90d4dcb775559bdef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "4c089942fca0bb848ecb89b466227d212b94c441"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "bc15e83b819f635366e6ee85f3823dfed82e9accc0c1378c6584234dd35c07d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87e4ce5ed5d1b12f0beafc7a068b38027a4a6939"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9dc2b953090c0b4c344f5536fa18cd80d0928a365244e823043b335174287461"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe93ace3025ee59d89ae012ca3e0bde109683387"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "fc5677403842d476040649a6766ddfd9749252ee0bf6082416c3cf793cf44756"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+1/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
