[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "bc0ef6f5449e8f49ae78ed6072c3cf51ea2c9dda"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b008a74b1b5611eb7890d82583f86c4bba0a2d30f4068cbfc36e0c05a3ca8cd0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e45073b5e5524cc6918a3e229d7b06d775bf16f2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d66521346d501093383913f2a6fefc812afdb47a2c41120a1954437ff50d26a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bbca8c2138857c532c1550eb90527ad651321df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cae96d73b575916e887c99f65e450c40e6f36b4e9c9d8c39a3e7f3d2ec990b81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fedbbed1b90553600bf1b4311cd6ba2fb8e1132"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b4733b030ec1ba2add73cf7de307ca3c769dcf7cc78eaf0053ce3856d5e55c81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92a9184ac5fdbd458a10e7da0f2730dd4c552d48"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "de278e766efdc37bdb3a4e324d9220c633d69e1c63ba17d01d1183359b7f4cd7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffa6ed9133233d6584fb024352e027fc76eee3c2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0ee2b3cb66e262eb697d34d7de10febda71f4682e7630b8983858c019173f21d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff6253f12cfbb2b765b47223e4dd0eb031cd2fbf"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "20bb3813f5adf8cc618cad331521d5e1a27932c5764c1f90c52dd9322972dc7a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de90d62014089b21fd97421d442ce9a1f3a209f3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b62ef92e203b607be07504cf312e11a8ea10fa67aeb11341a0760a9b791cccd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec31d4ccfcbfd018880b03f6ddf770dc83f1afa8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "75c45fdc1ce5172fde153e9385083cc072bb4d094e38200f8f23106e9684d51c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c76ce14d75aa4ae86b837139ab26ce103ad2bd2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "288619bd3dc6791a01edf778b98aad9a80130fdcc6c21adfd1549f1b41645efa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37b60051a65a101d497dacb46b8de7c15a82be76"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8cd04b67ac8d0c76257142b9f3d3bb27eeeee307674299226072eeb4f2ada15f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25b7e774a586756752963d1dfb39a8d7a7159bcc"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4a2b164070ab6fb8a5a6bf9fac038bdde3f19f01b051eb239e2cebd5b1671d83"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b17c07982eb7433aedc0e5cfea7503d780dd090"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0c42c83fb97762a109475c3c913f865cbaf80d17820f1ae3272306ef91fec497"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1ddb6bcb7def55302cb8453fb0b6b676a17426a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dfeb7a5b1686060a97205c55210933e35f6662faddd53af6d8cbe5cd2fa6b78f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "010741ee6d5da3a604a25a1fbaa3fd2004c4830a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "415549de8fb722809617a65af262f00fbcab3b0072383d0f9fd49e3ac3430424"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df631186ae809d58a2280d8ef5aefe111ced2e6f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c649935fd102718be82f18193d61bb30de213967bc2ec9df3f622af4eaebe83c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2b0bc8b2dfe4a1dba5e7cb27712aabf6e04b87f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "06ad97d4453f42c90e4d5ae620dd593c687e210a6948e9c0564fb165cc006ac6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bc8b015442e2296a8bc106589ba9cf979286961"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ac0ccec757dc29d03fbbcb1a2d2f817e2bec2d7e6dacba00d5226bc02b5cdfc5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ac45086447f62040bf9d8278658526eaaa0eb25"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f233663a26e2b5a550382166a738a1c729ff327c661bb72d4efb2e7f323182b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "1344b3dbe1edda5d63922107ed3d06d2b436d713"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "db2cc8c99203ad82fda3cfda11570bae99aede914e8c17540d40ef1be84f762d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d34870d116dab7ee54137ecdfef3962e0ebf70c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dbe27e1f5c686f89a82d4d98ce86358663190be341d7433448c4e76761fadd0a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "414276a44b10b52ca36eff2db0e9085c785fac9d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "236d1213116138a65eb52703b2e40108bcf8664ae1210861ff8633c918427f7c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2caf92bc3f4501bbad8bf5cf6420d9269e76d847"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "96f26b8219ac6d4f01195b95f65671b2cd30383ca1ef31485cac5d679e680ccb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a27fa2f95691de68bc14252a519145f8444d9dc"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3d77394ba913d3c337c14b988aec096ca96e58998699d45d659b40698d8d5f26"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "6efa07777d9b3582be4569f2a2aea306e164468d"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "2de39d0120ac1e3f5a7d76c4bdfe8184b0308d1941ae156425d19ebb7007189f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99317261dbf02b581129ee929bc8f7a6b76f7aeb"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f11e069f1bc42a3e03cb0a18365daef00310f8282a5470a1e26a10323d6f0249"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56041b2d8101ae5d96c9f4e9e8b4957de1c254b6"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9694503d4b684fbf8d96db6414bfa5cdb48334dce817dbe87344302f229cd028"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+10/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
