[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "4af51e1ff7a7b396fa2dfcf05c4dcc94f4b2cc19"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "ad5467243dc306815146db4c660ca4093ba55d556b98fcff069eb3f6cb1acc07"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97da661f46ee3a03e7dedd6249612075fe204b5c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3b9245bfe95726d60ae5730a66197e186467ea73febf4c2f2874fb55802c6770"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1db055031c5d4a50ce18bc3556e89aae785589a0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d8ac2e793b4eacb795ebe2411459b6f381ca09a2547a96decb4faa0bba5c1b84"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "ab875d766ba8dc104ea22b88afadd83468f365e4"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "e2bd0f97c2192390ba2bed77a0f8f28ac1f5adfe209294502a7d8dce4188dbb2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36e46a56bc1c60875baee2ddfb32d139d4132942"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c296ebf80085fa4715ef3364c468ba3c07a98e06cfdf73d1ec8cdfb88fd16588"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "186aad58c93b58ceb7ee383e69225f42aaff5237"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "87ab21cd094bab7cbd3b62026d90030c2781ad390489312f1378977f39ecee5d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd038ac9a16ac3993e89b4d4ecfc1c4aae705eb3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d94182c3aca52debb00bf1c08b95a4e056ecc49ad5e17912b9a65b9cf1beaf6a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3394e672f370a4894c9426186490e865aa338e8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7ad2a2a7c163f4b501f650a3cfd9947db2f2f97fc5751f9cdbb2ce89cf68b325"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8857b1dd1c7d07f740ee03e8abbbe59b7bb51d6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "da3a887cff1ca791a70b4b060daadd36190cf0e7d8f4cf1e98b7fb2e22987422"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9a02f755ed1ecf74af96f39d4f2dbb2819d9d04"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d6bc1038680209b6879ed9ebed5d6ea10290e6b48b0dfe09a4575903388a13a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fac72b6dd2258ff7190585bf173935d204a2d15"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d6fefffe78433a7b8dc2a55c2f2d4913113ccf0fa06c917c63db67ee907dbee6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b204c4b148a93a383f39dd0e9fb1f86529fe075"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a64b33b0037a75b877f48eb8840047410b93af2ec50b53f15a73044929151810"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "dc783c5b8cd7335b049db8b7d3121b2740209d2d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7ea028ce233c8e829e94ba8775fc058e3e90dfe79321a190cbb7cbb6117f8fb9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21334d62ab8fb1788be32b83ab0373b77916a794"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "176a3910fcbd5525494578f2344b61102eca80de1e81a910513951247c52a271"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "540416399592765acbd1800eaa4850833c8693a2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dd09caef796560ba1ca76a87dbcf5cb3ef930db9e7145886a93af141dfa1ee1f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "99c886e4fec2dbdb2fceebfe7577f74d33340b6a"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "f792f50c557fdd360d51e5d7dd0901027c82ddc173fae09239a0f55b97f0ac0d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52d0ba457f4f1edc15b44cd23d4c2296ff0ea7e5"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "566f89ad8a8728680cd668f4467d5674dbccb1b0aa6e49d7b769c21b154f9410"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v20.1.8+3/LLVM_full.v20.1.8.x86_64-w64-mingw32-cxx11.tar.gz"
