[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "75333a237fef67e5f34cf08b9564fbacc0a01467"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "0bd46680d4ab0be4801e08e3a327a2bce78df52d9160efa4d93166636199f9b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6a3939202a1719dbbdccb3e9d14bebbe76b7c19"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8ee74ecdea4fcc7f379438e76b7a5a94c9d1a641124dcfc6b851e8aaced26232"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e28ac6bd919c6c4099b5eb4b6910076c29de52b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b474e314cf7aec511c258373711b314957fbf6978691cf44b59eb10e9a66c597"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86d34344523b85b86be6197908cac3eaf6b91f09"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "76e5ec3a7a843e6804218e8fa0ccda282a0b5d9d6e070e4733168f268bf31692"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b54ecceb5b990b6e926721b1d498001952c9623d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7aecd7c2ca514a027bf2c78d041fd9878e794da5e93c9103591fc3f50e9add6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da28eccb50006ec175283f9add59cab3cc5d8867"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "61a1a1e119c76a4eec99a405563a61a381ff579b76165a375d17c38851ad303e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc6d58f7068cb08e5398ddd3506d4122ecb150f8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c6d76fa5e823b7aa1006f7d8301841c9ed773cd8d4d31a23f7d3cfa94e0f7e1b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89c0f3ae67779a8e78aa451bfe575582b4e45532"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f893c47dc9d30817c54ef80dbee26dc9e64b2aedfc3dbf05158e8cb1faaa2bae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91a589e1c6d3120b220b4e125b97c189a4627f98"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5d93d81cf0c7f8181263ec02b63d96ef10d90c47646da687c6814b90a7b0203c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a0391128fdd5f9b2ea2345f649b18f1366c5810"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "17e42f26a7cd6b1db3bf61b08e546af3d0e82ae3278258f9a0dfff6b67ac75ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4feebb22b2cc6785408b13486f46bb8271dd17f4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1de5906324501e5d00700b1cfcec5ffb10026d678ef1c0115c13b7e888b4fbef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "697cac8ce2dbb8e5b62cc39b142474f926b9b361"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6ec3f8b76e672cc3afccc95bcc9b15f1494b23adceb14ba092a031e0f10a11b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2267232b8d7d4bb51d8bf2481b0a3589bb044ba"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ead066eac7c86df42fa1e765d5ffa0415f14ce7f92fa0ed8b3a6973deaa2b5b4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97894a9b46c2ce462ffb451ee3fbebb0ff6390a4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3e90c1db032defb6f751639aed3c024cc90c8d02d137b1e0bc58c8e029d699ee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0034750ff5368a2168425c8a0b115aea58e8cbeb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "33d62df500f2061e7aaf63c7749e820d8527435a7ad2980ef22d73074a52b241"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91fad65bf3dff4f47e73e1523059cb0f006fba28"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "57d75b5771ce143a8f5254f29c07643dce446906e9e2e9744de8a68b49f5503f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "201880475c0219389e019a9540f4fdb8fdaccbd9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "13e549bab9a4e1660dd2c9e581b843197d7bf5770887281c77343205b185161a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad8153c2749ff0b3b3be9218c27e6d5cb70626d6"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8d6a1f936eb53986ddb940202d360816a69a7e3ad2157b755600282a0d97ce62"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54551f087003ec65cd7a817c77c85304d9303c2b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "805e95696a26acc0c2424443dd343e5af9a7fdd8a087f354b5ca7c739f7b1e0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b099cfea0a39c9f2e177b429534a4dd382c81ac"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "86fa97b799beeb2e69cb080d59a1391c1adeffcec219b6cb32dc1d74f1ac99b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19542bf63e03618acb90775eb012a7c5d8f74962"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eaa0a2f76bbe303840df544c32d232f6efdae0b600dff50eaf5d5ce1d1482db7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "71f63767acc4b676bd2088876dc50bfd9c120267"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "abc5ae92f5898418447811f55e5c9a6b8a30d3d730febc127710722e080f9103"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bd66c9eeb68e0a439509022c670e23209a77bc3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "603cf81654cbf1b32f14c8c0fd50a20aaeca3a86649272ef1b44c95202ce9bc4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28a1718dcd7797e84486fc8bf65595733ef2b78f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e530a5a05ddad3976332f7923aafcb90c3fd9ac06feb6a8d486f3e9774d758ea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7f6a5403afe795b3d87b3afc1601c7c4db67a49"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "43606376b5aafa21881b3112352ef7e3651a9fe7a9750f925d160fa74b06c3d7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22fb2480a7ee8674d4f4c088f87978e0380f0dfb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "884123e96b84cc6f8094e4ce734d237cbfd3c207bed3efd11c7b48cc5179f277"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "e6b9682a61d0250319c61f23b118f00f3116f8fd"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "1030f1f42a63fd636f4cb9e4af4fe2ccb29f9b3c4ae2b5cfd72df749794eda6a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3dfdebcb535b13e85b6af64adde03443259027f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "2e83d8bdafffbdadcbdedf506d2477e5788fae390f76cbb454f67a9d8847f8df"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8a2cf25015adfa999f8dc64c9d412ecab250ed9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "139340ed1cc5fba5835968180436b76c2f244225b2ccb92b019b5e257bd6ccd8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+3/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
