[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8b1a329b59c18c866abcfde91e1d2e53a2be0eb"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a7a15e4145272510f680bd9dde9e50c53bbce23dd1dc47c6853d6b39df53d7c9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da83e5636adfd67c4f40cfbdbfebace52b827da8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0116f0e1732f5a0d27d8d76f714489c1c062ab381c2f3c359aa57ed0641d0b55"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a1d06755d0b4ad02f72256c608be874c71127ae"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b5041d52014b2afbb80f9b50bab65b8dd45a68ab1ea9f195cd1fdc6af046b4cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8be5c85d6ea60de644bb987b0c81172cfb1e31d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "831e78e71ba6ca1692628a43dc79624fa1cbba4af2c65c4414d390dd2f4a4534"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f82b5ebac350cb10dbe405bb9cc25c7b8b41d045"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c748fa6f135da765f2ed0c3cb4e1b82d8c734db010033834a1c4392d107c411e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5656500126b93790efd935c834fabf8c738523a4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "be845c6df290bc564d8441e94bff4332cd5d4adae5a70500073a08c5b2bd155f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09fd0144f9efefff1205e7dd87ac3a3edb4209f1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "63b608b098926a7a341aae5635690bce4ab1b77220ec39857cf50d59358a7f60"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adceccae75c3ccd53e3f0db8e8f36455ca7fba30"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cffabe46b7d00b7bdb51ebad0ac859ec76285bdf4e64ec5ad235e92479548365"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc314fb5046c452d08660f149efd443207e955b8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "97a1c3ad45e278a5b9384a23b72842bd56a0d4b06ada74787fca29e37f051d7f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0b1d56dbfbd63e1c69d03b753cf6b4473c7b561"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fe908cf92c014bb809538abb8a0000cb2638c2eeac4afbf61c3536266973609d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30cd68446e5e68e85459b086c7f2fa5862913e3d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "36e5dd91d73ccc233ebbac0a7d3bdde86c8c7d58611b65626e2df4dc46b4d685"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b450b8ad1db7cd52bca8acbee36e0813283b62a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d72562f278352c96f4090947901fbe96808e3a6b8ff37bf75428f1248efda203"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05ac68b47a00fa81cbc6dacd8f3c5be72ce96530"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "824d3804e038abfffd348df87fd95e957a4c8ebcac15181b741e300565b7e32f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d3e5a8d067647211ebbb82cb8ca45173bd1f38e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "34c1b6e2f6df4bb05748ea2352429e18789edba16b930c4d15f45c19b15e05ff"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9811ec585b40db53afccd1fa1baf3a668e063907"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1007074944e9326edb303805990167ba2f134dc1f1bed032e6e27b9a1e1b84b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "753b9d657c91218ecb9b6fe6d33f5c239c3d4ee5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "768ac1b7e26b8f89367b8f487b5895a17bb3c5ebc44ba96bd6a45f5054425352"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3386f58f0a0f7880770e02262a75f2337825cf5a"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d8aeb158544d9e0fd2cac84d08fc1af444b117446e7ea31a342471edde0612d5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2d26d75c611c7c94ce320d18a9c6620cb706904"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "34fab4ee98722f25546f5baab71e6429d110fbc8af8a7763fb87efc6cee57101"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29de269f57d79e2b2738d9fff8d81c423ff9ee5f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b695c3393bab421e52cf3f6994cc378c95c087c57992121f6ae4cd2fdf9c19b6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c60e8fec2b637aefb400347b4ae4a9156d54b14d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4cb5e77ef72a61bf80b53fef881b0d796547a6b1454f19389ad47d5f520dcea8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd409fb5462b3a466b56f35b5623751f9d7e06a0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f54538c8b5a6902eb1ca79c5d3b4d95a64bda11d28f39adcea32182ffcebb27f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef1e9e2ab3a655749973f4d256ef493dc26229e7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "200fe08d23ca3722a312a3e162ae4c595f82cca89cfd380b25be82c41b34805d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee3405557878190aeedcc2ef952a98a5de905e53"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "b6c994c423fcbe62ce5c2ed1c63c033cd0ebdd6b53c6c435b3c6525ec9edfd98"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8333726d5afa1a7154bae8ec876c1e67892db9de"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "a3a741f80e87bb49fdace79d8be5e2f2dd093a1974fc5655f2d25a9e235dbda6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6b14e6397b20280603c69bad37ce0af72405c51"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e489029c55a2d9e0ab39b3bb9c58881a8065b56f3c8ad409c16beb3b0f2bb9f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4df94670b8114380c9d9e16969cc7e0559aee653"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d140eccb6b66a4593458a580d69f5c040cd386449fbba8677a291d698977b706"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+8/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
