[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "449d270b1a7d47e0ad28646371a619386d247f73"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9f991ae9d914b7899f1da9539898570742ea6cf9d3bceff88fb1956f9f361aeb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eea85caafb4607884508333a3ddbb0206ea1e931"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "33779f297ed7228eea74e25df5480f5a0495c33512c19567eb8a441f9aaf369c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7a3594f78b7162c84fdb16fe2bd2619c924678d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aa795decb3e6c3983bc5052ab27d10c3ea785ba9465dd00c868e1256a9c5067d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00883ae0ecba9ece74b86979d10d28dcca17c03f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5b42a9eef173b1864ea38aed765d6aee82bd274f58378c3d66054d3b17d103d5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "293ed0600d6ce5a8cedbb543d23eef03604ae431"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4bc7aef14bf63091cba4c836aac17931e869cdf688b8107120ea55be85892f61"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f284462eb585cef76865b3706c29f7b0d755548"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d21a79c13624e0d6e9f5e97c1e606c80e167911b84857a9e33f3f835d1c4af72"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "087a9137c57c6c337184c75a0dc1a0b11716fc20"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3ce7d198b2fa3348c5d44b995a421b9f88a3ee4d03606ead74cdf90c98d5a83b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3351f5e195128db53d09b3f9c6c2ead327b60ef1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fca545b5477092190783ce8dfab934bb90ec918000ec4a4b264a46eab6196ce4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c08a902a53d8df652e9378113f67535fc357b641"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e5530bec43e72e044b5aae24c65381cebd465df6984cf60ff0fa1f0357671dcb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cec4edb00141f427dcbb748b89a44dd9201175bc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d9427ad4aac8980bd8bbe74782b5528cfbb4bfd742bb0d48d78a5a12625441dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79b53bfed8c891e1401fdf032dc7fa1a4ff55580"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e5fd6d4da583bc6eed18dfc295590838464dd34c7c723b4bafd82edf867638bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09127865bc5bb1c5e1a5961d9a3c3d9835639b2a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "16ad7c9aa30107232fc31281e58c24f023198e9affcd186f2765d2f28463405f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f1a49d05632a12cb3c20598b341355dc3bea5b6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e3d3abdaed09d8385e7142f3922846a433b780bb33979630a9cd673ae48f50b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65111d0573178ead2ebabe2e00b94af5e242243b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d008b7ba6fcee03b596aac6f463b38a1fc64ba218616c5302dbe93cc3f6e0e29"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5c86cac1496996a4cf3105e6d6b1c768b2e736b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "562be010a9443f07e3e1bb4fd84dc7dbf2dd7a07f66c76e0cf1cea9a1bdc56f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7eb545162eb4e99b4c8a9aa55329ca5e33f710a8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e26a9406ddd3e3758b637013ee0f5c6f3ab62b2464a8348b5ce7a556e24efebe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8f682d8da2eabf76f8217f7a819ea85661406d8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b1c8ea9b3d61f1ff2e0e0e200a96c98d6f99348a36c328d02533546a33a0078f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6f33c5f136fe2fe4013dcac161110cf0c7c868c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e7ff9f9588e2f003a6d2475672916ad6fefd8ba495979a5600b7377b1faf110d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6c2be5f7af2b47b72eea241188e74fee1f3b359"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "424450d70539c3afaae9e8bb38228c11fdb3c19999e1ba1982715d471f193b87"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "b17805f03b5446e22a7bd05c3c143067bb5abae6"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "ccaefa65bef1d57141ee55f16a4203076470053306acbc85b82ed78ad6691317"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77346f63d2e611148beb9c74368696c76b4bf4f2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c48efb8946a967d63df3e2691f609d36e479cd103e743c068eaed5f9b097a822"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26f7c58c2b934f33fc21f56c5f8cbfb0a01820a6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ec4f7d990b1fdae590de0f18d56fab85909c96e2282c533b206d4e01dd76afa3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04ecda2e7e1bc1e4bbbb2a250e6de100e8b68647"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "416fe85d7a2ba7b463c0885310631ad07356d6841e3ed7a099e3fcc3f548bf85"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d7071bd12e4aafdce11332a0924d34feff88f79"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6a060e663dfbfd60595bcac890a14c2652940450ae64f7e2ceea8f60623f405a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "694d506efd0af454e210c368fdfdb1e70e49e394"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "ef7fe36f638a664d52f8f319689d556113c7b59365579fa037ecc5982f06bb0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fea8c9d8fb438fe106f63ca00917d1deff1b1be"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d696038b9530633b30a5b8222efd20960d360185850d0bcf9caf039de2975a0e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e469356962cb1453c2f1641f8cb021b554d78792"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9ef6f754b445fe80462990eacc7ed6b66bf3aecb7287aaf78cd3e1116a05e5a7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+4/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
