[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "8426301c9bbe86ede67977fbeb42d08ae31759ee"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "179ccd32411d0c2e02e9f4c3faa12aa25ea45aa5ea0db90501711151e5349838"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d0a925994eb373520016ebddfc484d1102bfecc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "afa72c2293cd40ed7a1556780b8401d963b7818c8af3707e59cd82c9279bc7f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6576271b9ee9e38ca9538d7b8ad1dd14a3ca664"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "13c49e8cdc794bcd7fc8a2c3fce5e3f31567a383eca4dd57d626700ebcdf9f1b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "03ae989d66147a030b1d7506460fa5a2a71f4b70"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "c9101a49dc726c50db39046f9259ddfe7521c22d9ed85bc2cbbd92cb075fe816"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e7828d333d1c7db8729fbdcd2f3639f7eee4e2f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "03ce2f78d6e8aa3f69f8172f0b473801dccafb47e43b7a5d5f33f1f30437142b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a80ef409ba87b4315065d13a24489502be0037f4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "507f0d78a234bfae4596f8bf94eb8d0e4c6e42127a65481a78ea3b704cb18a6b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2439594e58cff30cb0fad2a83e55c258f804b24e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e0d2c6f7da763718a44c2c397f1f9d237f4e5e35c445b6d312d4d5d4f9aaf463"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01893753d61104a8b9ba096e67a624afcd72c94"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "337d64fccdf1816c56e167517048681d39ef3c735e9004ca628f30acfd91ede6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d1e8e553b3a284fc76337d4b48e7bebb2c45328"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "445f7945421c6c06fa0d8994dca1327b5ff042222f93e3b5605909effaba9abf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff33d0098635dc8810c4cca4cee53729f641873b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ebc05f03fc299381dfd8e91b64c57dad4cc484fd1aa4d0f41b6e9f98305ba1bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37e3d1cf9b67a2dd5cf868d8d946c20b5ec4ff0c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3e4661684c625fd31a8cb12c1957c985bfbcde7f3e394c5f7a03991a94e599a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d52b261be5609edbaa5de3089f1183b0596a245c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "69443c1118ace5d64b95c3fb04a69dd0659584289ab5840e65971a810927bf5a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "f67cc0a12f574d6607c995c0cf63c0bb07cd9363"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "30d10beaeea31cca39c88d38049529c538bb6a433f0ca5c3968f7edf871c6492"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa5eba1106950736999a22b145183087ddc5acc6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3c473f3400125c165a8d356c72018ebb5d152b0d9d287dca939b37abfe0bf883"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcb8a9f1a99291a48e762088ba3278d68a22e0d5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9a3f6522d8b2e645d313d4a93c7b4f0ca9c4bac4a2359d9768894faa64556732"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "a681f13d19fa2a5e871aea8c171bc78bda5b404f"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "cf28d42ab0e45a6221f41fba17b510591acbf26131fbb29549d0efef6ea5e50e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba8b87177338a49e9f542819881e68ddd6d2ab80"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "31b00ca75adc7c1f8dfffc7949811e20d20dd6a37cdf5a61d53378cdd62ffa7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+13/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
