[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "182bf1376178e7eb4011b46ea445b028b9b3f8b0"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "bb622baa3f555cdc0ec67680ae7cbbaee7ddf29835a114c6ad4e6ad146e23e57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b81e3c249d2717f1845d7140dabd6234aa83ca33"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b6e1155fa7c35e585a8fa386bdb5923d15fd66a039491f09e4352569b49a4850"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bc75119e0f2f0325740a918eef4de4a9d1ada84"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9b1542e7227cd910c27f647fb15118a5f64b22edc9e46490e96c227e6ae07e74"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e85c4b9cee9bb1a11f4e92c7031d3c835bb103db"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0f9c35d304b746019e9b71ba509a03ac3a58013650a4622a7fcf5a891d001820"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "710b126513e332076d4d49b62f8e9d0e881af39f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e171b01f90921c2a0120a14def65061903862db52bae4eeb62639c3905fed565"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef8300acd505e5842dd442b19d3ddf82a88da7f1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "225831fae7dac4ea626de3251e954145d7e0d9aaf30c0789637d282fc4f6c1b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "054bf51d014e28dab192a7fb45064f8f656b9018"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c5fc3a33a92c31b09e4f89867eabbe96c3ddfa0ffda56b206d3a523e0d6ad0c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46bd603d3583c46dd5956233178879a1a40e1032"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d371f3080b36a52a22bfd25ee86fc66314fa2e2d72ad3bfa28747d8ff8479ceb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95b02e53d5188460e878459fa54f0df8f2566be3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1e9a100b20d94e73ad0bd70a07129eb8174c7febec5eee0b09f6c9bf764c0bd8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c270d6565f93409a9db1355240fba5e5fd5c25e7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3bf2b793e9ee114a4ec37088d429481bacb7ea38937988a72d4d6ae8220f7190"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cefbc5f60066c1eddc68fb9b9ecb9ed01134765"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "58d3cbfdfc502af0f0e100a396234a75f751b760b6edb4fdb0958ed8b1807d5b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f558f7494f50024186835d0461d4a9d6bebe24b6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7407b429377c884b10758a8f2f14c681c95f6babbd63269f101aade38eb002cd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a0ef5e5e7efae10a56c2549f3ac878a1010207f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "46c8edece7f9d371d73f2f8fba19653f5fe43e5900d85b6f82db5190feb6229d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cbc35369db39e9d599a56ad91dc88413228846c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d949d52622fec42503812691f501a81bfa14f0310ef8ce3df1083c00120d11e6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc20ca1e2fe3a2d3ef568e07489748d5cb081332"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7a6f869083ea0392378c29987a7c900ebd7ed87cacb9233ce656994d5b97d006"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "679b30ed27ee168dabf27e70a4d7dbb2955d9497"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b7e2859fa3bba45634dcacf5af793f5fe36da0a6d1ec065f1282ccb83da5fc87"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9e46675d1f79f79e6744f17055ee3bc921e7e28"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2bac3a4d36006f48bea152e426aabc12f998747202f07d347156c08153334f41"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f925711f86dbd520adc4c7008b11ccec5ab9e147"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e6ed4dd43ee0bbd0220733da6de57bc056471388d13570318950e809f0b6348d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81d3e6ad4c537fcd6ec06fa594bec7fff1e2ac15"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "68781a8c92665176edb4042b841c88af9f89c323fea6393ff4e15bb2ca9d8459"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e043eefd98e687dbe9aa04a9ff2b827c2d1d8b58"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e7daab11799bf7bf325901488b36091128156ee74e4847e8c34f5efc0814107e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05c89cb2250242444c538a1930c82b8bf73264b5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "97edb9f6174b84377594134072b9056229cd4b51d6c6f30deb8e507efc413dee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "3bdae0e137c616364f44eaf8a86a2ded7f8d3bc2"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9d0de5e22e097d62f2b518d42cc1b81d732f17984651fcccfbf9c39bde2e3ac9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f45c15f358e42ddb07d005b761a0e67859bc5f90"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ccd6c62bb9329ddec8336d5c3930a01268fe337b6ed3faeae542d19559a6f9cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "260dcb3ce68843e0aef7a6d0a0586ffcbaf15099"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1a516644b0d6c1aaa8167cb3c1562ce253087a25819108718cafae8fc7bcd40b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f028bef1a4d536e417a368f00c9c54340e9e45a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fddc7f77569ce4c3edc84cde7d7d353ed6f311a9af5ce295fdae443bc6d35a89"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c91f983eb2faf092ce3a58fe666eeeea52c6cd28"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e9fcb73c378b367fbc9b56c1d8430b6e160b971e3e7282c04a0d24dff7f2ae5e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "200e2c6a22a016c9de4b36d9c15d806ad4c94511"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "d987f96490d4301dcda2bbbf6c8b38e673eee0237172549b1489a76060dd28af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29118f62412bfa98f372e3ebc9a89a2f6f0ce36a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d5c12be50d52a1ccfe12d7b77005be2e0aa43407846813207d0e3d4d8d47169a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "293b4e29816098de4e755e941c9cc79cf8f21d1e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a9b62129dee935bdca3f9fc5d0575b79054d2d4ebf213ed421b550b4798d4a53"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+0/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
