[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "86e4c534a47d21f8ebe5032a6595694f443f4cec"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "08ced81d47383db90409150b84145b2e0958626cff48edc220f9f7ce2c9f5cec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "715c92150c26cf95ff60d5a94f6165bdede43a14"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "00c21fc380a775a7ff696e681354ab70a5ce64238b80c8f1fb322a70b964513f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "860f6dacffb90926607b625796ef7b4faf34b3bc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a9c7444629a8d660aa854d0671dc582ae8dffe100f23bc5ec436b80459f27e00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a738fc9b2b2f160efe5d6eb7d69ab6f41530bda"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bdbf433eddc815b9b117e940b74c3d307107b1b6013d37c56a602771d9e7a502"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81b5361f874d5775e39637abcc9678cd1932cc74"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3abbc3e717bc2f9c3b192f03c3e20a15f9b44672ac3e4989ae189bac20596432"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "ea82f8c6881bb28b522aebfce80f76eb877bebd4"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "596f59360038d7ec7b9bdea5bf59505e64c7bc7c6611b90fc215c6453721d2fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "383ed813efc57309245d13bab0ed18a12c406a9e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "424f9d7e58cc53ef09ffd02b7eac577fa9f5762c9b15cd07c755aaa5a801e099"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfae7abb58bcdcf2dcde20c6b03dd1c9f3b3d55b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cd881ab9c2cc1a625d6bb61f0845a7c66f14758f70ae6a3ca089927cef382dea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2772414065ea501dd81f7b196ed76e7f66aadb38"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bb06f61ff109270d14080b273db10955a93c98490951e83ad7711401e641d618"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7bef6d9059734a91771f60a46341ca037672139"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1223a25364e1e84eaf8bf154d981240e309179537022dfc95df225444d4214ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd3a6816404535cd115095b9bb9bbfcfa5994a08"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d54e128cdc6b2050d64a24841e6f7a92887179873fb6261229bd684c65932395"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a0a7c6e3925b18b8137550300749a3c1225d748"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a5345ed2e1585e35a4766cade8fbba1182ecd2127465f33d03b3e1e065b458b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d20d86d61ac786243fab19676adc71f6df39deec"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b3736a02d83a569c11e64c7025574507174d7a91cd53351a86cf16f216168128"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04d359a3cdf190f515ca68d00b58a2dc5217af67"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fcb0d8585d0c2db52f4ec8f4182995286b29f1912c2c5867416320cda3e4cfbb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28990dcf2fe0186e25a6d87128d5186c60cbce9e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ddf7e0bfcd5b4d5703f372647727fe91d337601a3fd9efa597a26b65bb54dbf3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6096dd09483d3461976ae5abd241c2067e272f7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "99a16184f7c8c7619f3408c25b0223ea233d4ea8db24ea3d35a91a440db5b290"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88afa4873ff01d7d3d70723e848e869c12b40325"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6bf7beea7edbeacd668065344ae3a8a07d0062599a309101ab0088870c769ae2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afcaf80a04ef32e458b4da398fd0bdbe7c9dfc89"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f6ea8e0b6bf8354ba4b9e71b3bb421abec52e5a4388a22d1cab5ab05963c1372"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80ae260369881cbbef9ebfc3d179f2f1b81ed337"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "95ed5aa37767619496484f2b53ff04f681749acb3789c934ee7faa4c35d36847"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3af5c9f4dd3997f91810e489a4735f2ac7a6a2f2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fbe08e2f6f1dfa8218c2d479bea89784a37e29ad445a2d620b1f213366252236"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "619ba6195b7bfd73c54a8aa3cade3ec574ef5e87"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7c3bf62ed5238598d1e0b89cd498745620c021775573c11ded3ec7e8b04cbb2d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.riscv64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d73e7581aa8b99054c4e95fa15dba17a52d017dd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "459a068dd034d6713abb67feb7c8ace9838745ed972cec418e15ebafd6f03ec0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "720ecea9d009cde075040086bb75f51b93463527"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "913430d4e17973507fec1d68b1c18a175866b1f0db5bc0cc0a772a46b79e058f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e6f7b4945e706579c0b92e5e4993af275cefef6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a0ece92c5e430c9d6e21bb7ac0fb4fcde55b3ca399ee0c6c4bac351b3e5bec08"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5b0275e292fb20b6e5cb98fdc1e8c1ffe8eda55"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8eace27e6a3096d3c746a51916ebeefc6ba18e818a8a026b63a9d095bcd128ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b86f93612a36b804f87f0a9be6f3ec7842b143fd"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "101f0a83efaeb7b40e70e9b7794d3a75bd40e4b1111a75a9aa6835ff04a242c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "689ca8707114c962414f1c039f7a28bc156d249f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7321132d79d38c065cc1efd9b88f022e728c28ccd7095477ff6e59a227c80851"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "00e499975422a47ce6acee1977333c8c0df7b8e9"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "c1aa3a6542aadd3748248f8e31677e883193dc447656258c6c8b0061aa8d9796"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bb18201d82de8c635d7485e843f620ca5b5cdb0"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d664043819144a5b13d0286c1519030d76c6403f1bf1ab4579ede3d551c44328"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fccaccebf19598252ccceacb231704dcb5e10ba1"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7b6ac6238375540bb5922b5e0b0737806175f693a3cec9e0bbfecada50ded4af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+5/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
