[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "a217e92beeb42b3849467ebf9546f844afe138dd"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "642e7587312543ce0ad6faa087b48b44258d9bca65fbddfac489c14e448172d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1ce9538ab7cff827df7cc0bf7e350270db5dd0c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "68deae8e387adda2fccb268f044fd34684a1c6325c35ae4d6e3671d4694f0194"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37cad8fc8663562ab40e7fa3d9e2e2b563894dc3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2164c0b1ed1da488a01c3e7a08dcd377d0b8709da25df31a72483f6c67c3af20"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d698464dfc74cd0a6ebbf0cd35a986496b8af286"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "010e7f5eda1b5ce445e741657d4acdb7944698b4459861aba82d9014e034bb62"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3cd4e8ee27222689d46ac83a6a5c0f01839bd5c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dae003f72ece59ee66321055ba0b91404fcbc42f71f100937a1570298e58e58c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "15940e9185be4fa8d340d57d0ec75703954dc355"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "3050997d973e9502938c6120fdf6ef65b41c842547940a84450bccf7ef7eaf00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a69c5868848dd2df9bdd1d414195d733243d5746"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "63088bbc81364787b8a9eed223558f61429c3a77db6de88bf10ae8f2d5c40058"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "428b952ce49a9112c742eec763896141321c77f1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7d47cb00f8bf65209d4107585f6e136071bc779d67ca8407f9fce71ab7788045"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ee3c81e1086b824b648e923a732283e90037ca7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2253e3be3ee9fc3e80de86901571bf9776c3e4ee4e520c65abaadbd51906dd40"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "796fc46439a9fa378d380c7e8c99a11638c36c4a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "999e00d1da08807e068f722fe39cb101542a5bae3c2c4ad37b37c442b04e4017"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba07293417e08d1c41999a837c61408f3146992c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e41ec8073f88ffc7a6134013c1d20ea586ccad1406b6effe115bf293c8cc2410"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58671d71540224ba7f1c302a141e9f52d35febd1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0fb39880f91a4ea480b848c5c74ab998ffc5f82a66818e2f1566cf7e0fddda5e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd9312334524f1d278050122b50cc04ad55d337e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fb05381ab2e6ede7a9af7e6757830b1a6d251b28ac10ddd74cd0f5ea1799a6b2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd0b2c448deebde3460207c5d43041e9c154e93a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "df4854c318df8b0de59e2cdea623fcdbe740757572bd96264e7fdcbe0243c19f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88eeb88c62bad07be8c048f080b9671987b61cd4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c6cb6665af3cd7b5adca6fa7a512a16e01f7a12b7cc972ddf486c0bda459cc1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfa0bee76392b953a7e57fa616e0ce56df193c6a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7c4b3aa31fab0653e51fcf78a1c2ba8483abead7982eac0ba8bd8299e36c2c5a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ddfe98f8020583b95963c654370a0f012ca6363"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d0c02dc242ab652230ec4863fe330186444ce9b8906461516430f3ab39b4e859"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "508d6d465ef334aeba98a6ab6e69a9f3d6ec40fe"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3d81349f3efe848a6122ca709caf4089be482d36e9ffe3105ff8d24f1c72108e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4e880f7eed96673699d4dee67f1e3c9a8336a18"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "21d05f675200f61c88f75699635d329c203bd0754bce565b24f07b47b2216c5c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd5e8fc5970b99cc7756c37fe8dfc206bb7c2334"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b0f9f7b05ec9fd6c849466fc33738137a71bc92b40c87694f18ace302e579818"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aafe9e5e25afcd80f6a353518f650a3a33dfc180"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "99676aabe7da3728111ee38e2c8b82c4e7d8e640666284d6b5d77aa5dff624c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.riscv64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4da20ae04c0ca1e29c4596dfcd6fc671b9699d55"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "75840df30d69afb24e5b42c7e86976b4f9c3c6908b6eba42bf0db83a3789f18c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "cf5c82382c5a8fe7f55615984693fc92b8e77968"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7a124bd14988d1063fb9908b234c333a7f27ea520c8dc78f0bababd7b3cc80dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1836e16fc404ee74404e301bf7ffd282f3b272e4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "262084acf32973f22ada0e78463afb48584c0fca258b8ba4b20913e263e39966"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba466cff8e239cb1883d48b5d1b876776acd26af"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1a5b3db6ea28e16bf19cdfbef7298428816450294407814ffbff5176866bcfb7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0857700e75789cef98fe02e2bb198d7214ebc5b6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "964d8689a7a449402db708ae4a99318162c517fd9a3566226bdd07be63b0951f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d2cc4b42a328898a31a3c3fb7d8da442609f986"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7d025d9cdffdc0b8b8077ee5628db394ca14e4cae66348b84fb11f5bc712402e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "502d05e166efafb2ca21072b65c89e76e9c79015"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "e9d8bbe859d6eb6050a51466c40a0ab3ca93eb8b63d401b06edf0932e0175447"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d217d501c4bbba98551846fc02076821c74f1c2c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a648f0f8bfc9951cbe6163b1269c3357143de08cdf6a403ba7f972ebb2955458"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "770e5cd72f9cc215187c413f6bacfdea557d8e0e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e3dd83dfbccc1c07bb01ea9b9ad2ee78b287fb81d3852de564fa4004ee6fa18a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.1+2/LLVM_full.v19.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
