[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "ccf48200153b3dc3fe8c6f283d229f4b8cb9ecfe"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "85c02fab434cf17f0b45de38424ed6d05c77c1966ae732d37043442dec475cd7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "332c2e00213ea378043570d31b986cc29ac8ce56"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7d1c5880be608b2080629f9f2adbe76aadc3bf2198d71bf5cd81951338eb4d39"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81589133b663bd7afca81336c7dab4035eec4384"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "15aa889b6fcf8653bbd2c41bfde5ac43255cc1df5b6b8a94ff981846a4eea006"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1614d9e57a4acdd38af8dbb1ac28523dec21623e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aa8e097d6f14abdb6562ea37b197fcd2c4333ad15fbe7f1c6152259af08630e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c43d647efcce250ba3ae2f59ed1012a80b20ce3b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a8468cc36826ab09a0124d9dabe333815dcc9a578326a6256353a60f79eca472"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "317e65af09c7591164f79d8bac0d04abd0949e1a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3c9e1e755c2cb4461ca60541dff9fa5cbb94c16af9c87d9ecf7fb58cb856ca82"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df6e7d8e92bc899f5701ba1a1899c3c9ee7c6e70"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5351997d7186d3bed7e9ca3d04470b6d07ebfa0ee4c65a87156eb680616fb43a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4609f754df25eec1835aa48b31738572c44fb6cc"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "963dbe4875ac39aa9b9c8b1ffbc288620146c8de96f1ac90fdea94642e6e98a7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ee26f51119411e9bed4bc76ae111d5c92d21fed"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "66bb9830aac70e43f3c7beea9365dc7bb969783f05a33227a88ffeebd3dee45b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4ea41a7c0656cf7f18bad55e91912781b7205b9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "10386a9430c31c8f3b6f1b9cd6c65b59fab92df105c6a3c28a2ce11f14910827"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0aa88e78528bcb3346f7140c72d52905b5231bf6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "86f236d094a6ac97a47bccc884ed844a087d8178ced45bb3da5daa728ad2f348"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a41e8b257ec7dbb00c3b7a61e01c51c1a4231036"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8e962d450649007bdcb6fe6c6324999557b560304d0668e3a93d6d034d48358f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1c0ad99b8e743dd68f78b8a20863d89ed818361"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9650ed1e937770c4e26f400759f29296c607a3b369103d65ee150a44a98b8109"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70de77ca6ca1e19a5447505ba56e15fe7fd1db73"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b5c05d13b73a730f51c395f7131d1096f7e659085f87427c1a7da74332f3fff5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0879ac4620f94c0bd29f603305e1e5890ad41fcd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "35f3dc222425b34be1bd74a342e2948b2898400c17c5e484dc413be5d99b9e49"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38a217661d88993664c589d851ea6639d1ee6e88"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "dfd5a0288e5d9259b7b6eda402d867553074338762b947e2e15e0e6511347bdd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93fcd6a2bd29f3ccd74fc2901d6a4b199355d153"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "521ac232703136ba01412e90f33a897f21c9d5cb45fe5524409997808d0e058f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "819e7ebcfe401ca76810153e02d559c7beb3c8a4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d687f99c0770a434533fa1bec8c0a3c61974c371cbf3050c21c9bfba31a76422"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0babefafc2f9de0004a610c9dfccc0ee326903f5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "925936b766d53e12775fe1b88bcf6ca90852afedc7aa543cbef5e17ec8158ec5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "54d08051a4f4e7e50e62c06dae3399155bd3e30d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9ac15c18fddb2818260b29fd37e1fb7b9aba86657c257653ace82703666e87c6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bb91ba1808aa0e0d645cdfa1252f066087a189d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9f63cf2c5d3871163ee0d8e4333121ef87d4df6b39b22fec94d96914cc171f4a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "016b6dedeeed406526bc8bb04afc81fd3f6500e7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "48b620642351501cbe0d35b1d40fd2007c842e98fcc6b8b0a046cfcefa2fbacb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58de8f51a1bbf234816c343f2b44a041fd5641eb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0d842ca7ceadf322c5b9777186f1365546642e0f6cb286bebdac1229914035c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4b6873ddab509d1dfdf890a5c5156283df7f706"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2e2947b156993a6c2bf4940f8de52c39759a25c0c7209859e617972ff17f6603"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "0405fc0acba97ff2bfa3876098c55d964de5db69"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "faa254864fa53f19790be33de8f537d4cf166a0ca341dc3fea581417c4f44d3a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cd98a8055fd47709590fecad5e9dfc8a945dcdb"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a65886684d50990d3106867b553900b0de7ec88fa990a276ddf8c2ede5e9984f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d83330fc661ffd758506d7430f4dcd79d4cbc3ad"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a2557babf1b6510443ee8e1b9ea479d3b9007258a7999b377ac711e89add8e72"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+4/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
