[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a22fdf171e384a53aec383ea8a9005acb6909d96"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "13d10538a01307e078744d4f09336a0c7fc70a10b11b59bf30c0f23f40826401"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f87ed9c2e66af29e4ebeade763c815c9bd97ed2a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c755d047bfe08a45fc041d1c4ef55b197b9b1eac11980ebbb88805093d9631d8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a160c2036be034d313a78c2586813307dd23c2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1207ef3595598d7cbf99f0ad80e0b325e4e6c16f3e5ac6a52b7e959c34f4822a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c92d9492f0b9c088eb127389a2b29d2ab174e37b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4c55d9aa624ca44990fb9b459486ac162b66fe7440042272cecbf6089f218629"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b65b3b5de35f3bc933f9e1bfdae406f6b7a13e6b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "946e9a05f9703da0fd469c1aabeb74798bded0cdff3dcde63e29a5e046e67ad5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "210a2820585dd014a7c3872587d9ec7c8bbd4396"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3b2771c451637eb401994aa22a802bb7f8e8daf61fd8437c6ab3daa1793bd7b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43605895ac5b7a054270172ae857562734f3b1cf"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "54e62225bd36b540cbca9d1e6d4e80838f0b57a259e43973c11244295e532575"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c83503190f3ab9616d5bd907c99cef193b2d0fc1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "971465dda9faaeb436a98fe930c04d39c3be309e8dcd70c60ac941ab04ef2866"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7f3f87e7d9314bcee22bf12b338c2c7608f52f8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7d2d319d21da9bc81aa71d8cff025d9776ebbeb0147f36b3cde75c37f282fb0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5340f6901bab55905f1c529983a9461e316ffbcf"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3345b8ed38335fc3bc3510aca1c38a23fd52ccbbfffcce077e87a0632ff55e8c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "891ad30ab2cdc1e7ab0eee6e79c35c836bbada7b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "641b442504e6acdb675a4265968cb3f2661ae75e7b3d6ba0540003ff98e2bf80"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f55f5445433b9155f4b3fa5e45e5ccc9ab8b675c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a03aa03efdbde07f9dbf14a503d85bcf73742da5495754d97dd9245960169f00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71afe1cbfee0446713adb1aeb4709c3a644581b4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3576890a21435a87da86cc7b732a6773bf5881c61847f4691a0dc4f30341ca91"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dae8132caa43757f1b09f1b8a490273aa41d67e3"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e60ca4acf4a200e5b85eb13fada74b554562ed46fb12ec5f6183669ca4635aa5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd370379db3a66783046e32f453601b6b7ca7c5c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ded018970856a180cf1d954a07d67a00013f634e056be154a5efdadc79a23c7e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "408270553b218eecbf9ad10271bb56048c87dafa"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "425b84cb796d523ae5350cc5bf2f60345d58354c63521925abfe81b106d4aebe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "d1e3550e6a8f129c371ae6343bf97a99c7e5c11d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "6eaa8bbdaba794ff7ff7737646efec5632ef3ecdd668cb52b91e23e1032863ef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5a98434bba4ac43c93d2abdcfa29fd71fa11aa9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4590a8c5b5ab27649b11e4d78a5350a30c8c3cdea9e1aa96bbe9c4c4dcc685a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "486d90b4a161ac54ac82cfbfaedc296dedd791ee"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e315f9fc4a095c979136687cf2a22d62b9cf543e5f7e4befba79db56a6d65af9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40f11ef184067409a0ce82bc277b71016bf4926a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f8702c932b5ea36b18f3a72e9c0fd8109a754bb10b288fc38ffe94826e052364"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6e0e0dc8a73a570d2760af0bdb46965bbb705e2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e19127178597608b67549689e303345ea541f54dadb9e1b3d6cd02509d280e03"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c1ccabf004a964896e7fc2ae8792ad8d8d5e24f3"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "68d0077c0a7ba9571ae7902f53a35f7b197910fc5df018b5374f19c432ea141c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6febdfea60acc8c2bd1ab0c21641f34589634d8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "54a33b76053fc60e589afa91a12a567d4f30c80a87064300d9e75d7c2d4ac48e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6045035aa40212544e601957af59cb723b839856"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ae98159c3f0943c2640faf954b4381e13f138d4fe974219d1aa65c83d2348ff8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+0/LLVM_full.v11.0.0-rc5.x86_64-w64-mingw32-cxx11.tar.gz"
