[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d782cb895dc6fe9cf8941bd50152f5ff87d8153"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ebd473946a3a09f468233bf8326d2b4209cf659f871c8f1de35a57196d0352ff"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c3d896480ba56de050c0efafa5c6c908d899b3c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "440339bd2ad67fd3b0b36f0e495779a02412dd330e564ff231921bba2c93e1e8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b718fd977fa75bef7fb8f5ec2e62033562937ad9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "58ae4448e29661a3409dd40a0b2aa6f31a964a3625a6db7e05cb75eed185f3a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abb7dac1d8f8c5752c28c315191eae054e21729b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "af6ff9fc5ea5ab884864bc7b6a810b01949392fa416fc04ec5663c0b498c44ba"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e401d57286c433239b7ee717f29ed64ad570139"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c8202263f881f6283ed17ae8738868d6a9afb6bb0794257712f7a492afa8db14"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5511be3b3d89686565cd3ce1c99793c89f77dc74"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fe2696ad4e9f15efab2ff93659a9d106cf1d38dcfa0749011c360d654e41518a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e5134a16c57a0f402600fca0afaadc400280118"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1dbbcd9a4505453dba8f18c85a6e80f66a1cecad9dd86efda2e20d09865b1492"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd777bf11abe16671d99496253b467d887038138"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a629e9c961d13ff4fb3a38dafeeb731968c7574eaa9d837aa2d316c7a337ac5b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc83f6b715687a7db62afc643b6aa4163fc0967c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "440042afbfb75fce07b01e37e2b08c00a9fd276d914844ff82a78c8e31f6bc4d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7032ab26b6cb558f2ebc4d74f2f342be86d9596a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "441ad811ad6c064eb0326fa732ac2b4acfdb37c985bdeb2f6b6717d0494ed0f7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c9b39155a1cea76033c4c0f7d2902baeaec44d4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "63c01dc8248781db7e57b6b34cc44b4a15c3b7981556babdea1c4ae3dc796254"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c69876d3745646d0fa7b820aa6933f49e4126dae"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bff2104c65e7e73bfd148d830185fb39957480d8072b0c8628e3da5068da6a3c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1f169924f8c974810f879761387b2fd20ea1fda"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3daff2fb8733f0c652e603ea8d47a424ef73020b63f018d42fb65d2f07595ed0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adeb4b78630e83e6bf209726b11089992b5893c9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c64a94e1bfccf77cabda759eaa66fc054b6024afa532288a5ebb265b466bc317"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f868d96ebcf46446a9dfb8bfe104b4b41a40d08b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "223efca0a9424d3d67f912c3b58932cf7beacf376a4676fdf9a2610600e1bf8b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97f548541efbc91ca652606a60b91bf75fe44dc8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b894036505b909c20a8623fd39fef5ea810e3778c39d0a12d74ad33d63dda23"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "ed4f245a780dc285fcd9bbe83d5a994f28394625"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "ed38cfd9ed4442c74103282878fae7bbfce8ea4479ed2ead379b732b14ff8a8c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be19feb648b0bd3288d53eac6d13e1a36781ab08"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3525ea02ce3ee18d6c47c18a244546b7da7232047314fbcd57cd4a83f595103b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b87147b381b777b6ec5fcd8110a509988d285c10"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ff9ef557448220938c46ea6f8b3764dc719d79a2411a488ee459362cd9834350"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cbb6f3e399ae9275a73e56ddf8b228355428788"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f08ba477332e78ef03cf3a0ef5189e5c7c05bb6d010d2398390cb5eadc1628ae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cd48915fcac501fa681f877077a5917212ee0b9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a32394ab15eec0b9b077e9b5e031e763dbb9ccf15d960c100bc6290a769bd350"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "2bb45c8c054ffc4d80297dc1ca9d2c94733a9435"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "c22e4cc557dba17b34dc702f6aaef19d43d0f616f655e3f00232a62be9ee1a27"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "021b19cd0ce963a3ee30a8c03197d9a23fb4184b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7cbaf49a96830aee9b7d4149d1d33a99d3fbe079ff28588fa933953bf5b62442"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1db99e129c309960226a8afae791241bfd2319b2"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b7e4acc86f0071673163973a7712e1e7c2a7b61f3e96ec9f43a9c510493bc52f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.0-rc5+1/LLVM_full.v11.0.0-rc5.x86_64-w64-mingw32-cxx11.tar.gz"
