[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "a3cd9d1b7124305ba6a52340065484786abd2adc"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b0366b54e75bc4e7ed5322d673a112f3533e54a15fd6aa70b6bc10f342dc578e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d034bf9085464b91f5a3e72cf8b84d4ef826286"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "14e5f42ae6c5eb3a84ea67eaa5eae7a9c0003c960f6f779da503b255c18fd34b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d58cd77e40a5293bafe574c0d908bd7da8206569"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "38f449cf6b1172e5078c11e2395b570155e04ffe9a5eabcf76031bbe77610bc7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "665fe356511500dc8eb2025f484726e2d62c9c20"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1d8ebc6e00c1e64a4390881adfc1c2621014cd16a649d638baf649e63b772ada"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4252495f7117062c1d0ac82febfa4256b84a8b1b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "35f27500556ecf921b21f5df17c397de9d03b11438763a4d3486559d929ca9ba"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01f8c53dca5a63dbcfa9bf556c32cc03ab284cfc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "40590fcca8a8ef914f30bbad5edafc74195f7ebf94d5400a783d62bec5ce0c0d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1b0c0f9748369179c40caa1f3d4c93e12d68da5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "114722a62b87c38677e0a070a12e018cf1f9d8475f106909b5684e832fa1266e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13dd37e727e351e46b751d4ddf8b43da1d5089d7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0f96ffcef7a2376cecb89253a950127dd1e6c25b32efa95305e460572da8b782"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dd0e8ed1396d489980e0e2653604e0eb3317cdc"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f654eb5ce2cd39b0e4ce89f764ff69e801f17d4ceb15e4ab75ccc566174b5b43"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91b5a2f31dca3bcf1f94ea9d493c283352913839"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "75b36cfe9fca016456e7586e2fcaaaacce3883890f79979fb57bf7e18b1c7aaf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e65826e8ecad4eeed98bc838d86adc1bc45265f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bf63b60ffa2e84efbb24edc621bdfea1fa2ded02faca42ae52238ec613344c6d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97206460a63ceddd5a1b2609d9cbe790eee5761c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4e8ef8ead904f4cafd8e8be11bc0d4eb2726e1ec979203ffab06d9ec6eb3290e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68add04752c5d2778ecebcae7aecfd8d6c3c105d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "94e353c555b208b37a139f173c216de043dbfa24868e67af2ff263bdffe7f5f6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f94a1c2e7c2825a9d7ddc7e1be3fd34b37e725ef"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "55db70c37fe862e538148475e2ba5f177fab6dc626b9634b06ce2ad9ad0d87ef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06a8984539e4d73519bed7f84fa187ede9cacee3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5547f603659603480de7bfed24a48a6a82aeca7a0b34407959316fabe89804e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc51e3ccef1753108b6f5dcf2a07d558324c3ea1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1947731326a97462aa7b4a4878d9885313f01c8ca272220ddf2f621cdef88c1a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "149858a0ad4d1396b2f8736436457edd64d75fed"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "601ade24b6e16aad7842f3dc73e3b718b150fb5b09660b37e0d0eb1e64f9491f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61ab21ee851a1708fd2a189abf6cab77da3fd8f0"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a0c920ac25281109becd17c6c736d97065de936dcfb408a708c71085886ed280"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f541eb6e75146c3191cbdf70c00e068eb381b4b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d7c964d8bc0065dd81169ec3daa0afe58f1d1f0212c89dfd819a5099dbc15355"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b471cf497948295c1f62595bdd9d4fadaca9abc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "186e8e645de18f4bf97a1f82fd429b5c1a4278c540f33019bfce13ceeedf5062"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd4e56d85328a072f9c817007e5acd8286c8a116"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2c39443512aba4bed065c2d63fa1ed42936741970249c7a497c01b0a6feaffad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "8bfb227d3cb7e2ccd779f47050025cfa0b0fea9b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b14521cfe4895617c2fab1b605a8377e8506138833628dbc6f3e28bbe4fd5045"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c2db961dd64bc0fa2890e1ca052e16ff539255a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "44b0804fd3f623cf43e3fa60ba9861d7d12c8829f24afe316358b1a45453a5ba"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c8f6dbf65960d49f1f705d995d93e4a0971e7df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9de9cf71a8ed3be8a7f044832b300ce2db40253c506b690b3ca5058abed35e91"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d29a654ac5bccb1ce7a67e6fc203830744ae223"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "caf3682abd0f2fe7d45cb994eabafcd5d90e74f0b3e836bfec351ee830e1250f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "920eb1d6eb0b3803b0e95eca8c2cb04e79f3ab84"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b94314237fcb9ba53576fcc7110f27e1ae37633703f589f1d60e3425c3f99cb3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "20999685658a304b35a4251c3a0dd9bef8348419"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "0b2d2341d937050035288022c6ed5382fd08076a8867b0df35898a6e435ed00c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1775cd6f4d1a944b13b2fbef45cf3864ca5055ba"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "70db560a968cbb7ff5112cea717832200605bd1d323c8e4214bbfc96c4b0b167"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a43b71bac9b5522cbb726ad88773941bfe1f8202"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f785cd7c559261dd5cd5b8b857d1064e810a9d2fc225d11b0b124781175425c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+1/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
