[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "352640ef3588cd6e450d59d99c8c8de60f09c0f8"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "84ddad6cec5c1f7f73425d3e69d3493511f4e1d592e29f47e242485d59a3b295"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ad4d62f9891b5fe6439dc192ab5b03cd97056c5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9e419c50810771cc3fc20fd5212a982ac47affdb9a8395988be3d6fdcd85c98a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f341a09b680b54f960606be30b5c0a91d1c42d0e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a3f8953abeccc983f111c567e23bd88325735e9207e39aecc8502635fcc5b8a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06a95f1ae29dcab947c3f9c5a15963fd0e0f81c0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "44ca0a382d2cdd0d4a2037b68846253015300c24f9d57ebbc1090e970e8ccbc6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60c9a51b803171285292ec214aac9f14ae345019"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bfe5639073df02b15128a46a3bb9d3f88412eb295babca3ff97cc6940e511bc6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e2ac30d98ccad889a8a8853b714bc6b84a3cc03"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1420fa28b8647d50b74b430da31b526f436d060a43e0833dff9c1b43c7216af9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c33a7c7fe74128d2e64d4d7ee2b26187136efab3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dbff1caf0a777e74a0823f6e6d26fc31597a28960d99f4045bb3211289a8287f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87a97850d4f961bb1dcff4a82e5cb0393fa113b4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eee013db0d82da5365bea874d034df10bb53027839f3ecae1ecb1e8d89cbe009"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f109bf04be3d5bb0b69c87434515e57cf0671a56"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "433fb113dd87a48e8da4e991e1f380579b65ef9430eee5ed8652acc2cc57ab99"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff7885593f2c2c92c5345efbddacd8ed0d26d2cc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "96da92578acf9590c1d13392b798a21df4c70c15de30c0cdcc2db80953dfe88c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "030aa12ee71c63038d41e8541b301ab93862d908"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8d069b36e0549942cd821628b0a3c9bd6467f49a0a35640acafebfa2fd1d4c50"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0823eb49c77b07b6654d1faf937c2857d252319"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a5507d11bb0a6c068e4bd0439b41e9667a4dfe94498c79fa1929eff66899e6bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77defbbce7fd06cb36594d9e57d9f89b666834a5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dbb037c602af75cf65aae4889cfe86190671ee7ae7ea2521fef32c1240b9a5fb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13eb948d3602603bd6595c13ca9a854d5c763fd9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5e2e8cb47ef3ad182e0f1ce98be733cf02b0e17182f4096fea74a1a1d2ebb9fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd3ea87739a2ba411bfceb34f3b41cdc7e604899"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6d1ee3a160c8e715d40100f6db8dce110e198c1bfc26075066359929319a7fd1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0273bcfe3835d70ddf260248e37ee530ff2f819"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8499e0d4e0fb9c55632caaf644eaeed9b7ccd774a3b885f1cb6629811990ff1c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c4d0624867519315773851c0f03e955eedcdf10"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8b4775f7dceee6b0f55e309735f0cce4b065472ec52755b802a6081893443581"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93bd8cc3aba9d9ec9216d3c1740482fa188d650d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9a4acf209bce3976c2213954b3c6b06fe2d3dbf4959f2506bc25d18360427c47"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b9493dcd85a081b5cbce843f11e81c318e12faf"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "170e85a11953fd87060eebcbbd0df3425a62940cfd27f0cc5421b8a040c103bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "100a2b8df054b87dcf0489ec288fd06361c44e12"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "32af994204cd9bf0ab46477b725dd4fc921f2e2ecad6431b8fbf0dfe63697418"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "680d7b1c38588f5f186d96b5eafb7b5e53cc4695"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1fc8358c0196a50fdeace4a08a91a5877e408e7e00ecc5a1bf97c28c3ae62e2c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc8bae757de4961174fcca81f9f5a09030f81bb8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ab6204a9ad2e110f0fa6055f59478416c2481aba437ab070afb24f1a21fd253f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "002b810d494cc1e9f34aa5a64fd928f76a676cef"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b54868bd738cacf23344cf7b5ac838a008c8d4f2f5048f10cd61bdeb8d4f2d31"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca3023cbc4a7a3d4abc00367938d2e8599d93001"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ae97cc2faa664e3c00282a028d03547c2ba937e55dd4eb1a499c46d0964fa65e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "453ac8fef00de22d6968341a95def6dfff946911"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "d020093c6656ce2c276da1745ac876bd1c6c54c931c35a26ee5449a7e3f12ff7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f6fc882bcd6f0986552690b8f9c87c49e9494c5"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0141accb484ecda1a5a55f25fc9c79bd431f8bb280ce7b507fd78482c44bda6d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b51044bf53aca642baacf5d438f72e3fac1a0f7"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6171247c171885d5f42ff3fd15c16cf404d99f9c5de585aa148fc41533a73971"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+0/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
