[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "b18c799e742b9f554a40e040bf7347e88eab8f90"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d543fcef4d77db737ed6d9f57b4c37904f133443ca1b1515248a84c375ef75de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ace998a8c793f1f8b44c763590fc4267aaa4a1f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c4e498e3d814c1f4de89dd78e4b694493cebac750a123f5905e98fa06cf5f708"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abfaa88fd9aa5755aaca3d3f186241dc0c7f9310"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8d0806b9b269e5495d3eb064828a1bbd259bc8d607010c2b0a5bf82c17b65f2d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5aa3d825897484648acb4dd02103bb353bcb8f4e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c5593de5a1b9011f5665ba49d56e66d71d175aa2d075348870be2ae9d9224b42"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52a672043b5e21843b63a695eefd226fe2a137f7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d2dee641fe08cd2960b80b3b3140bd29bab196241f959095c9526d86e0a2a606"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "964b9517c9930525d1fdd8bb517d39a7ed842e84"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9ae9d8b1d7ddf759539f123eb874c31ef76404b288226935d324cf4fd36e3b4c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7634097b3bf08f7032f145968976e7244a49147a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "536897bd5d9a3033cd1d2e3dda40db9d9ca6064b144d7aa6cfdf64d8612dac66"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17e37927e88860472b2ff56c73b0aa2380b5aad5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8a2f71ba4bfa7e3fab016f53dbbb177e85b5732fb56500a7da74d8692f969f71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d64ec34a6c389eb997318bc148229f6a2d224116"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "694e72796e8a36aa69b6a8acfa410d153e7f8411bc59a78d849319a0a723f66b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba946a5a4d6f5c83d757cc7f974462194eb6ebe6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e1e7b6c71147c19a4c6d2342cc693c3ebbe981d7e4e4dbbd04392de49ade7017"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e3474af1adc9a012dc05a224c0870142d4a92ff"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8fc0b9303526c0663073b4bb307a878ab2af4a7780d3e8279ffaa6fd3fe06a61"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58b72172dfea17b0d1d3546e0bae4df7ba95ce19"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d1aabc297f98235032ac0b9ef3f2f070c1af640dc0c7f8a0916ab1436c08bfe9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f67d79c07a0fc9707c31aeb1419673dbf67b497"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ffe6f0a313713501239bd0c70d79a34a1e2699ef9406ed04cca6ffde23a6209a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6502028eba4ed507529c235bbab281aaa7aba042"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cb774487a80d3dd6541ac818c80d0259def8a7be723724d94062efad2af9e82e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29a3cf76636b7fec30c10d33e3aef5281c7d6bb7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "be93ca3d064050c60c184d5c2d9ecaa93757b7146d35585a3b716a9b71e1e8dc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e5a7f915faffccd6680bf68ff1d159c0d2ada8b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "02860b746f16518dce999bf0cfd5d61eedf3f722b619feff14bc3e159c41a5b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ca32f661a67b0614b8c383905a2ef3361b6847e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "618154aced610fa178dc3b5af0056f8cbb04aed441158ae7f561faa6d688f9c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5501c9ffcc5e9f2febb351620f230d36802af56d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8b9b15173494ed0ae4e5c1fccc1db13a95bcff170fc2f42b731b18a5ffd686fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bff788ff1888b315bac4273fb0f20f32292ac300"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d81623ae0fab28d3b4091ce6a72d126ea75bebc2c6737fda5a85764b6a0a949a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfd942025ef9ed02cb863550573d25d2905ede6d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "87a61a8400ba07a96f25671fa3b1daf5f9fb7da7f858d96625ee7b338da962ab"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42fe826c76482007faa11de548da44e618a99ce1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "30f72c158d5780e1ac7a936056e789bea2cfd9efd40b99f60538750cb8ea64c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "7eba1b2b3e183c4ae97e4c534e75c4ce80c8b6e7"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "f1d7d8bfb8392aca3596fb03b9f78efa1226f00609c9121e816d9168708d7883"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54c0f35502e5432d2eb631db8694327590f0f183"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "be73c4dcaba859d1721c3344dc3bf112b4f4e9d5c80d64aac93983b79b259db2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fe38ee9cd0031ae34ae0a75db094a997ce1eec1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ff0615f7aaae29ba73651c7f25f8f7b23c72dabced4f35d55e4ec6e4d58bfe3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7990c75242606af2de624c37ccc24a8c8ad6ddfb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ba8feafddecf7b4a05132ee54a89aebf5f3b37dfd2113de70c7d30a97fe21d0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af18bd1e789b1d2471f323066386893f4efb28f1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1fd46ca2376a0d9c935f3300af1719c937c84a18bd6478d4f58d39729373eee6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "4447785d797882bb97da5f3240cdf03085b27ed3"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "ac6b2aea1abac3537886a1ed66b83fabea83f917cbff9bee4ff3d86b0bb8d4e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "059b6ed36b5d61c6b05a57c14fd0d49569081e36"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9c9cf317bea92f5a861ac0f8fafdcde94c792ecd7d2f5c591db37d0a07d23280"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2667af3fbb650fabd17fd9d6a57e5aac95621d46"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b427b3210ab4b6e39fe58032397d8648176afdbc0322bb9f3b2a5d875c503e60"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+1/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
