[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "4879ead0b36a73ab32de2c4f81eb4cd4110c9c0e"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "67e5acd766e9e02060aaac47e22213c165783c36559f074d0146c464fe54e31f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c688a35db21f55a2a71898ccd5f4745070a2d181"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e2d5a1b393092b32d066b9c50f566c160ef7a8bb42ae1b191287ea91b25a04a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35ba9167fc94ff3930f4fa8bd8e6e5bc1c81ac07"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "17a324da9400feaee5d0e217b8a18fd77d522068511497300ed076f6c695c3ed"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a387a124a3014324dd76fe1cb81669ee6f6f541"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fb53a4962f9e74919d9475e13416f2883eb4efb258f42c55908e5f386fa8de6c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b4d1a9a76d443ffe1a219b97da232d485c52137"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b8a26131ead1d5619e628b5aa0ea0f5c87e0c55e5128c843ca494561879d69be"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64117b30b48c3a1e012120beed45e17d27c9a889"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "afbe60a73bd4edd0a54c2be05d3f44011392c7d6e08bb7acb370431ba26321a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80e970c3a45a77eac9210a32b4a8f818df2946dd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cb5cbbacc00c96fb773e14bec20cfc31a46d0dafbbc15fea833f46a0ccd7d38f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e4df6a0dc425f35b161bdda39692477e7620e73"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6a924779b56bcc0e690783f3c397220202a854b10ed1f3e46cb2a91db8c1cf70"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9a3f1579df2fb371dba2130053d04247bd05d16"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7424b7dd71f823b32150ab63f040382667dd56bfa6211b04a3b7a8c6b0ab2575"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44c95c523836770bc086810bef28e96ea4ca5a0b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0e666b0f6918304733c30e8d5fcc9ebb2d92e2857264f8c594c98a36e3b1e54c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "592eab9371693ed3f96eed2ad38b3153a8a1e741"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bfdc49fe7110974d391ba751a9c7e969e658adb85c7a026028d40a23a7a2bdeb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29835c7bb5c107eaf65ccfb09f92b4090729b58d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2705cb0c2fbb4103db7cf737367156caffc9e4836784aac100938d89e7e54d71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ea0cc3bc446078d3c8f5695c8c2c2e33fe7379d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a37291cc06ec6ca68d8d36a23c872e0924260d73e71bfb62fb18a9a69df03d62"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2397274526ab503b96f5ef02905d830770e0033"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9627ebf6cafaef868e34d2864714072f2ddf78b03c45979fa8ace9d49273590d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4313b4c5c76a34cdb0292f6642d4da4d88320a53"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a79e016ccf6497688d9a9f30330bccbc6d5a5e44e5c6e2e5772998a0aa96e272"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d4d1e613bba4951db72ce7760e4a6ae4f8a1336"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aa809e6ca13ebc49874990fa59419c05ac596ce82c2ca7d62aed3d27acb9275c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2aaa237714584d9c3a382cba5d04089a6a139342"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4fc7e10f03739a42c5f431eeb185b1ba34b4e66ff99b137b3d4b27225a415d3f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63b75c82cfb1c1d67b25c05f9f78469180f2f2a5"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a533ece68ddaf473bec15371379527c2ba4685f84bce2d62d7c053e8e7cd3bbf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c24d610087bbac45f55bda15cc554e53723f3d7"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7a4c7f0b583cb9a8e692421ea88fbbd7cd34cbdf70286d627c23ba2e8ab6ad4e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d96ed9c9c45b66c73bbe4fa29b72d9477f276508"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fe08f416f98d96f833f57d39feeb950fde5e5b634c2875099ebb371bbf168e07"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c65d6fef9334132b5839a926196bd4c31e10336"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1a2561052e9834c06fd8ece150854ad43cbbb8ae444345b1f2b2d5dbed179072"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "03f5ea8783739144695efa6a6753f05df1179abf"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "617f4ff34a5fb4ab06be0918dd4d947bf7c94d26cf28ea132e0fe12c6e8f807e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9065ba530495b20458edb7afddddcdbf4f60bbd2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "191602511d4e85dccb5ec6a407c201c23e0af9cb08813c61c60e077e4ae1f3ed"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0888c005c8a8742cec3e6d0360c0b48647dd6265"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8bcf70cad8a0fad80d98d71eab37e17e000d138c0f61cd1af8cdaa0651bea357"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa82b3574748c785b08c846e18e20e6f4815f4ac"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3785e02a33863698f0eb7867c69cdd70e8309f5f5215ec9786e296afd06613ad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c899c2e81b4107b501cace15585bddf05d6cd2a8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "308e164781eee15811ff9336cf763cdcf3140e00b5f2d3e13395f035085ec789"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "71058c8e3257b5c6eb1201e06930c7984b864687"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "6a0e9106e5c0ba228c82bf5a399a32a464160191194c2244f6fe5f6d0bb640cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e51dcdfd806281bcb60031edbcd7c5eb3a168aef"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b6976aecf0d5fa456067455f43affb7e4f512b1380d84191abd9edf9f619707d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a82d42308c1e1ffb20224075a55fd34c025d35b8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f8b6587a437245aeaaa6d853bcd2fad636e80a46d0e9a7196ca50ecd40dbce09"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.5+0/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
