[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "df9cb6780f05d7cd5b6beb978036c35994c22667"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "132c06d659775137e94b7cbb81252a4c0bc2746ed4050276c7181b52af240828"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1dc302ea2582cb6b84a32b089b93512f3a80f443"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a88612098f35a7d66bf75ae020eb87d61e3e777bd3d63ae33c00587c8753306b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c66f508362d07a4ab3a64c5450230895acccad5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "eb291b75327f2247d2b444226ed80eea1524118dae7f8226dba3ed51badb91e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "921ea0dce167ed5aaa461ea22734e02243d7ad79"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e9cffd26baca59ce40a3973dbb58181681407cef9f2bbeb056b1f0afc838523d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55457ed27ec9a5f86ac9fb58cdf75c1f5f53e289"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "476cddbcf5b4f84ef82097c04e31e2d8c48a93e20eaa1fd1821adbd2b33fd512"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1383e8ac3859f62ed4795e6f72487e013f3f359"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "061b2a5853a3fd18aa95450ca389f779cab42e896d6d63963d8735ff111fb776"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "604e1e9f3a33629f49495449a427cb077f53c6a6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1ed38345bb7d40fe8e681b5f50883cd634d20a84feb4f3ff94d5f07f152893ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3f3b215e91d4494081dd63cf1be2b108a58bdbe"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "293411efd6246eae9ad3941b9f5e5f12ec10815f6d16cd85133607b8ebcf7a0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1489952cd218756f28c4ae8a05c889c7fa2d1f5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "658e186fe91273e57cff4334ed0f78ee606d7f7d0d8e9943c4e685e7dbfd0d41"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d29f2a50ad7fdaaddbca58a630d365bc3c25b459"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9af412c99b06b8f180836d4dd8946fbe8b07b8cb358a9395f8f83aaafd6f3068"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b50bf20df0212170f6f19e3ea2ef8c8af8869f90"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3101eea27afa9bf5fd7982cd2d6ea88b75b66d3e2ae9fe456837159c45723c01"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05fdd77a62ac5b2f0e02f27102fed02e7e87b78a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "20fe830563382f976ef86a0ead78e150256f1486cbaf37e5d54421f11f6523bd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5f7be952ca6c773bddc00c687ad2b9cfbcc2a7c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d3b1fcb69c0f38b878fad88782c1e93a6cdf0ad60270251699618a07a75131e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbb7f611c211dfaccd9bb9e10f279c811e833728"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "22ed442fb12bb097d0d5dd69005c806e318ac9c0db23ba2d5c367004972e9def"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80fbdeb962f5273e5a04e779edf1b47dad4a04b3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "75e609e00cfb3b4c41ac10ef04126c0c85fb5557f8b5581b8733e2574181bb90"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9da8aca592d51690f9b9117c36b76dadb7664436"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b923fd56b6d4ba46d630082488b92c82121452f55886cefa45287dd25faaaff9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae5328d1392b31aaa19a293404dab2760848ff16"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b0d441a3d9d30c37f1b9b8b4e360c084085f9fc6706821930b9027ff3f5093cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70d3a856e83f1c8ea976e8c2601753139e87f97e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "59dc6b6b63f7f25d808a337513699f566db70bceb88d700b698e53f3d4c53f59"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ab48ee31db0983b9bdc66ba033b625f03e9ddf9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "723730bc2d0034f51b480d12b79d9d0043af15b8010dec7b5bb0e42d149fdd3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e07b074027e1e9472531599fc7860faeeb51f75"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ff4b1984c4a8619f0790e888058ebbbc5b1f793f71e99f284df2426d3cabe98e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55f2f0bcda7201e24aa11e2ebc318fa425f54e6b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "38f47f0dd7ecdac547a65279ea9e6ac656794f37020a2b414dd6aa97c33be7c2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "ca8191015e62384964a3a899be7420985eb8998b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "f1d0f0bed876660b21cf1628313a2e0d6f59f3771b85b9f3a7df45ff69faecbb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1905a53aabe77aa1b83b28469af0c6b35e847679"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a920aa8652dbfb2202d8d88ebd201818dc1cb325ab0ac408dd9041e6899a5a5a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d895da996a5b9b9a527d34f83401464e416cd935"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e825c98425ed199663a4d9aa711ef339ea6b6ee872a8678760ad322fe337d82b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8bf521480da8221f1fb02cbef01b0f9e9fa29b32"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "704cd6a77910f5619b6b9d02a8a6d184b601388ac47f0f24bdd8e3930f37f878"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59d40340117c197f3246740af91e2b3466e24afd"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "12302a3ae23e081d1a3570c3385888a18bc6a98cfea15e14535dd041167c544b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "79a67f302813ef0a1075a3b2f0a82bf4f11ecf72"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "a583b07fa05fd482bb21f3ff5f7993f7e803e1a4d34eaacbf63e8d8ae5190de7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4b71c15c07956fe8fc9e139f2c902c2a317ff4c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6c01c5ff8898d94b03417ef0899c1b2a0fcb26e50e9ac40dbe28e4d221f7db5d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e981dad5fcc1d8e226511630284e41e8dfe9a86"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6f7e08661180c01dc6e7d5fac77fe9dbaaef31ce2e8a151601ca514813bc593e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+0/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
