[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d69ec8a094f94751a592f08f7ead7ee55e7b8a29"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d41c2a169595165654da9e371f63ad4111177a456eb8d941e666bf1c1d0e50e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3354ef4d3358aa6d138f173410f5c9117765db70"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6411f6bfc7f57c7519ec0ad4cbbf38473f18d64b73a1039fc306ce8915fbc459"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27ff8f71a3fcf152ce3e551e39ff966e12e00aa6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aa0ee2938657a2adc2a3edb1f20c51f9e982a3ec970cc2207f0c36200f719cf0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bba4da173afd678b3b16b3c5a403213c054b3513"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "770bfbc638df6973719717f887bfe2168925bc0629a37e7aef378c5ec8a6422e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "deda11dc70cac81589487bd03eb4d0e1d2cda2bf"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "6c45053d9fbefe720707776a71ac742a577012a75dde60f0473d8a953ce0bc1f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba4b888557bb78c0ec0a810c2f48697d899553fc"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ca6262982007329d6ddef26739dd7997bee7b3b266a2f08dfd734c7948e4ea2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1b96edf0093adc12f9fe2c91350e73b8c3101de"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b477951d441a2737a3cb79b84679b25e0151a500c903874cd0fbfe8d6cfd3e53"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce9e6f0e73f02e19b397f7f19720db94020a0ecd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "47aaf4403b63ad0987f9b6ca9738c062eeb912dcbf00909759e9c83e3eff63fb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7055a3761ba7cbceb9cf2e2988b3b55bb215633"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1d0c2c531d35096002ec859c6ff15d0c5f8ba91d47b96c363129a4c137a8acbe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffa3cbae4d82499f8c1ed686d4481460b49888bf"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "e70eaf37120f429f5619e67176ac946ee3a768d8d391f9eeae132d0e471a5ad6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "784c22d26f6ae050c43b3fc3d16cb9f2a3e69784"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "03749c7f8aac81a584a096b042dda6663890884522676fc0d7eec6825d7c9c0c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1db834f7ab49c1890774a56422fd2ad9ab4e45df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a17798fd5ec75e6a57219be3eebf6ecec10802ad13ddd43eaff92d264cf46c07"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd742156d7bdb8c21f58673f970066add0a31b8a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "25ef15f3691c034798d64d2c606044f44b2a3f62333c21deb446644420327c91"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e57cb277949cb56283a30d88bc2827383bf581c"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "f31bf8f8bfe7dad5f459a3de65987bd7830758ab6e2c7db56388f8fd8fac7f4f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0a26b44ab45ee9f9d40ddb056c3b8173ed62aff"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "42b7d92c80013c420c5385fab45228c08e94c9c62ab7059935fa03a75b928c2d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d3914a6b958b51a36f79f61ecfe1384f76a020c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a56db3e80be565cf9a65b119d5f00cc1b0229606388f47cae0116c02661d74f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a0ff51faf3360cbaadc2f2d17aaf6f6147207f3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "51460758e7a820886766726440ed9762561646a3f0deccb941683bffb91d7b13"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d735584a55ea99152ceac57fb60a71882b34934"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0ccf15c666c919432933d5eefb0d1aee927189ede1f4c01f44ef6b2a020a3a19"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abd2fe225e6397a2a7c0eecb17486addbee48160"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "221ee33f169afd3392e6d7f6319bb8f08b9da9b532d7a5e70ea367cb7653dd04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "531923e3b56422ec6b0e99d75f0b7a6f6049b440"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "51bafba13bd4cb94be9041788ca69678ed2c1142b7c5f672c334261e328659d8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "225a9663355a82caf5fe5d0e5debcdc27d016645"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "283ef2df31be9e2e061d603f6aed7f7811f4206a654b6a2812693a148089e404"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01fed4e793d2c01d6c394d6aab46e1e2ad5c417e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1f424f3c0136019a8984856ffb7963f20b52ae658081f903c6f525a9bc7b4078"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5177f9771d025e0f98db4fe5bf671599f0a97d1a"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "f32d681eb522ec462c7304fd272282c70e9fee9bc3e544f79d05da9532340dd8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4150eb3ded27f46bd19303efb4af4f1d1a10659c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "95ec4c72d68b18c83ad485fe8fa74118e956fb94a61fde0ab5780349c84048af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "360db9ce4ea9c7a121c2944a5cc9094090483d68"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "785cf67ec1963e1937c86b967d6e62652f6503dc65c37eac7c230c1ce0e92846"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8a4140448c25f5edb653fd32f01e93b7e8c453b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7c676e430f5bb14d6aad2566f758e9f89fb1435b7842ca18ae4e4fc231332d39"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+1/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
