[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "a42ac0ac5444c1f64bdb0b0e60b49a9fed07dab5"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "31c35ae0c2368419a2834fedf7fe6cd2563d54476ff8bdd8b441a9e018cdac72"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "971e49301c1f3773cd2485699c43674607a80613"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "18fde8bf66ee3fc4e028ed616daeba1e0720ef0ab4e5e87ae53e94bb120975f8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bdeb4525119e543ff8f19689dc60080703bc65f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cd1449ca3b3da5bf00fd4f78ee6f3accef6e7360025009d2e31e1fa2818a6781"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a2e500fe71e54d3d19ca6c7dbd0732c2c7d615b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e180828009025bbdd33d128429083bc4fcb12ae4be2cb36423d7bd49d52826a1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6410a02e836a93a38ce06a66f9f399204983e449"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f7af930478fd57ab09858e64f59b7eaf6e20fe82aaa433e1a6c6e75835f4d203"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ebbafaf6162e686d07e6fadfd9bcdfbbdab9a31"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf8bdfca18a5253da5635e37c76e987ff234c6d7a6776b6931620be692198fa3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "907938bbb29d8a761cc1f0515358337e72f0620b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2ae59c69b348f1f06c64dbdbfeb594b967fcb655dbab0741d51bbfe0211fa4a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf1ffcf7b506e043b469e90ae1977231fbe0efce"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5e245622cf53dac7c17889f0217fbc5a9b0ef88edc7498fe46a54a1da360878a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "898113d51e34f85d8e943eb101a9696d68df7791"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "02efcfd3ed2298c1753958f4791be8f2a37cc903c0266ccfb0b7a49376ec0690"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a53a406ffd3d2d59f5d3b65061d39fd5b12c5ea8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f618a2f83e03424a37b2d1333f333a1e4b79103bbe3587dda937bf4e0beaff1e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7117e25e1b05c26affc06bdaba16865f7038edba"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c056b96185ba5491f09fe70194d1fb56b11f8f23f27447d811286229727f918b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f543be067ce661678b7aed9aa759d0464dff6efc"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e319f321f5287c9d67c3b7cdc03ffeebeda930e12f8e22c97e9360c1631b6884"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93116f2b51507fef9bf537e40744d29ebe6324b4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fe6dcddc76db4c68c525d52a5c82a59845831c0dfc81d769984959460bcbc053"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8068fcbd302859bd4805f534ba23cadda962c29"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4cafca358bff95433903f13f82414ff666d18481ebec12cf3817d5f8b18a967b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f83219b2e2ad211470fad56cf3c32fc2cb0819be"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ce5a67ffa0c9b00dbbd0890b98e7376f67c1dc00cce8c0253934a96e96876f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16c688453f1192ce1f7d2b09483fc44be2450df9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f066481bb6c50e0e11dd1546c37a781043497c737f33ebafdab7a4082f26afee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc5d4e6e51ab82b453903b2bc82a67b8129570d8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "30619216e2bea58b75189e9a1b1a69de3ac70262cfec40bec20a8b08084d041d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a68343649b6fb5dacb475b1ba94e190fc09c0562"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "a9507e5934d071d9a4d964f5aa01906a42e2e8ece337f2761323ef66c2d4636b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea157c322484805878c8e576fc8387f484696de1"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ac4ed5f09a9358f7f7d047bebd9a4cc33efaa365ed9a27b8a1b98d6eed4f7aeb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e3990b5a7e9a80d9b56bc243786263a660899fc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6ec7ecffe95883a70a7cccabeca40a4632b3f1060db0da248c06d89494a2e8b5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a8d4e4e9020639c9d808ac41641f7843a4ea950"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3acc4099c6c3a567765be42e5a2e2c96b269c2b1e767160f6da371ee3c98960b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "5d4c23c4c6c1070e311506c1c8ffc6ac5334ac2b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "da732fce68126c3b7d3f054c07f8084386cfdb450ec23deef183ace0b99efa37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "504a8ccb1acc0cec214f7c12e4eea8fe5a2a49b1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "793d2f29762618b863fa61fc2cf38cf167be2167d3d530c75db7557bfda49954"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d607ca108f102a1b2cc3419bf7b4a154c4aad4b4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "26363cd58de3f6c5e08449e3f00f3563d1f8c1af941cc6989adb28f3a7b26d7a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77be5f7d899ba9f62e20da30e3e20dc134b36170"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "79a86045bf421559fa78d1327286126233aaf7e5f4209d67175c589f3cf73ed8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7beb4b0551f86c073044a54d236d7684b789b01d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aaac6637d5789824f8773a1ce6505d301b4c50c85dbc6c9f70b8dcff1ef2ce5c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "d9c0633fa519afd86023d0c9ccadd405c33f4416"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "85dd1327c7fe2f3ef9bddf22b38976e1f2caa9e94ec8976f4e9b1015abd00199"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6b4f9297604fdad55f9b728b22f06f9cb630602"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "664648df36de569c879a90293abfd707b60111e2cbadf09a5eafe14e1f44bee0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a130fed86f98aae9ccd5288f9ceeea0f8334b073"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "5e8c791b1827316a74d89e5a34c759a1acbf7c9f0a2d37a2a85c02a2ac5b399f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+0/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
