[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "3bbf924e080a7c1196d97e9ae8043fcad2fca035"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d66e07a6b7a90f33c637f817f992e2bdf85a7055e7393e8a1f55b1c903aeccf9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3d8bb446e4f4a6c18e3e50d353ecbf238391cd5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f56d767a9fcd6e87319cb9e544c2da1df40985ddbfc92a96467d2165fc8ccc1a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed2d506290a8330b615014d491d1ac0975cc2837"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fb512b929f14b1eb850c9172b8feaa2ced895cac691f62997b07dcf2b217a616"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f61d9b7c6c76a95c07b97197203ed8439386a96"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3c6b57e910c827eb4beaa1d2776ac08968fd04b17ecb73cb4f44efca9a1e8f74"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "089bb66218421056bb2c4e16f8b434f99dec8d15"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bb444aad08612f5722358a1a65d6fe15ceb32de724929892f22334d2bda1f4f8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "14733d5f3dc9861ae00d5371271c5fad79e6883a"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "a6c283dcb1daea3381e180df99b31cc9cc6deb3c58622e8de95d7da76ba66e25"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df88f7fe98d9c714809ea2cbf5f40e09798380cc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "06aec927759089f8244fe49dd28e856c404f7a5b7a28ddac31bf744a28f116e3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99ea5b02c6ed3417dc85f8a6979665ce7628f31d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "60cc7a82133becf88622b00bc1fdf43b9809200f51559438dd0dfa2af5936404"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d9a82a7e56864dc4fb5f106405519c3b0e687fa"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "468c40bc884f5a23b5cc6f7ff5e205079e713addd14348a187fbd45c0297dd5f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25ecb388f909cff01794c73ddb0c2d7e1f46d12b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9022af47fc929f5cdd612a62b4a1b51f9af0964360d7453608cc5e42505f69a2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6915b199fab3a7add31e1a405ed4fb310c7841b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e10db319547571a50970d2983208a84b118781f2b205d1c7383e655cb2f7dc64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4eae3daeb2e8fb95b4bbb7b64ab8c440c1c4945"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5421b0a101c958a1e8912ae3900ee6e47faa653141a32ee9b4380da35be05b16"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06822ecc24527393db32f1c1b6db082b966a82e1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "52358a78db20aa3989593f4a57002f866746d5297a4c49d2bfe4d9cf50d8db6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3823bbb50f887169eb6cfdd6dd4757fd7d0a675"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d2adeb45e69e3b97fcaaa2b551c76ffc31e646a7469aa950296ae32478f88beb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cbf459bc01b0330ac37326fc00a2e90bffab73f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "852b3627f21aaa393c06674eb59ce8c6bd8729d0788a144c9a2560c123d25ff0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce022809befaf5b848eefc73c4f26858ecc07a61"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f8ed77631775a11acc0827e0edf52eff317712bd58a271ec38f0272765106c8c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4df965fff89d20c05cd1c6eb76edc2a5a5221e6e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "02880e6f2394ac39d4e4d41f47bb30673dee10ed767aa3a3a4d0171590a906a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ceff2dc172be0090b7259b785a60bb5c5753a96c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "bce77c398055fc6e76b0205db0147aca4b0402516be06f864692855cb3c9bb87"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d555547e36e97a9e600f4e3714b551237a0a5f56"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bebe55fc5a069bd7dfe2cecc7ede2046598eca11009680e8502875d091018670"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4e74ce8f0938b0d15399b5dc3f1499cb9f7e17f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6415bbda544dd01146806a96021962b1fda6b11460dbd745019ca40889086e3c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc3ce69296c04863a72a4d78547ceed291144f36"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "352bd06b6d3a5d92f81b96b7b7c9e681a1f83d0549ee7c709a878f62c436ee8f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.riscv64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69d2b6ccb6396ef7960f29c9fb004284c05e84f2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a094bf944a1f588e483948453460586bda69e351e4b66a26969624443eeaa23f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c4a4869840293a3112dd460e1af93dce120d5e23"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d928376e5c2a672e9b0215db319b84f75cea92a22aaf374cdc0e68c431d0099a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1b7d9ac540829345e90bf31616aabb867a44795"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1f1dd9b9014494aacfbde9a621d2001c43d5015c617d71eb046f9f934f8fbef5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cb256f92d4d5cd317f7da60a5f29cc28265149e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "61cb68e6282e72e6ff2143b7dbb83ab376ba640bcfc3d407939417e1b23ffd21"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c0cc1975a1503d2e7951de2a47e8c5a447a8ff4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c93da6a55d54aa170cb92c19fb156195cbfcee3bdd14eb29e97cd1d7919fdd73"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb671e0c823419b10fbd353e2cba2bc457f0ed40"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5895d52021e128c264f6b1b901fb7cc57e0bdd23a50759c7cf8446163d73e839"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "392d9639d0efefd2430db7fc817630dc2ad4d307"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "8a58815f3dd167ef10daaff82a1facff684102eab957180c8c7f930d62722119"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee0301cc17c53feb2bb81aecede5c248baa6b387"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d53d9849af7bd8ad1c27620784e571edf3d46169183f4c5923845198bf119c0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85cc6a5a720eebf4435dbfa7576695b34d1f241c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "790f977dee75dd5500d9d331a65229f9138983fa61b47ede650ca2ddf059415f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v19.1.7+0/LLVM_full.v19.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
