[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "72efe1e0f6cf73f528343dcb7a142a6a2b2d60dd"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9c698eb3650e59d3217553fa29dff059087802a37b388410082756742fefa6df"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be2f1e4717c95b624154f7936014bc5daceb92fc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ee39d7ab6a1275e08a8211519a881d895d47591f9f90ba342399f40093203f98"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3205eed0f0d976b5bdaebb59702b920fc8476f21"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b5bcd0786dac1c0f8cb94e5574d7a61e6ae5a868459d92cec82746d292d31737"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6006e3f408e62829357c49591ac698cd21cb767f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "05cdcd9e15d08623aa44b596b0130c2b073f0666b38ce485eec36a18de55ec87"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ee6bb0923ab7fb8cf13024bbc2202cd40a7fbde"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "639dcaace62b394492137ec5236c71af373d3bdd1fb0b39feffbe9de47143dd3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed38b3f93a368f27080df7013121226f227c1a26"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e463a6f8b55c30c8348f8a1854412742fd2471d75a2987582509400a4efe7ef4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "918aa5f15e70a60b7420a5bd9c734a9dfc0b6163"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7c62cd9b6c3c87b2afba2d45ab6c379c36089501df69c3861995765a5cdfeba0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aad79c9815b0f9bf3f72f7a26f243cfa9d5d91c6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b3938baab6e32e063781b3e9c8cd7d2b6f07c0c1bb8af741fb8052089d3dac77"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6ce1c719882f8425ea47bbeab637cb469738321"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8a8ebea698c5793592b635831149afc38492450af035406991f1d3246333319b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eca0bf212e477cc2e4c7bbafb6d02744aa4bdfae"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "04c96c2ae72026cd88278693c91bd0c06ecc885dda3c3a42b4e838f238b11f62"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8212cec86c80a6a069f322e6676a0138bcd483a4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "79689fa350a4b7da3eaffa52cb5df2539fdafb5f9f9159d56056c25c5ff7e32d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bb2c8a0709fc586f1477af12ca93c61ea557be8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f24f382d79eb8ea011ef385562f73ae57636d04c478f2bc1a54332bb423f4779"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a332040df7f09c1f39ecb53915ac7155b9daca49"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d01596008449b80ef36635b60a3f62c20b51e0c666dc60c4a4a742b8c38e7427"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60a8c1d23f3b8e267993e75973dc963df5a36f55"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "01602d011184f6986850b60b247ef9f1927edb35befd712e0e291e4da6f5ef36"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ebad7c306714b0bd3b4760206b87fc13011d731"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "70bbc870f727850202f666a96883b901c6168c15caf80c9c53b44de690ec9d8d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1663be0cd416f4eb35dcbefbafb4eb48bc233e2"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "710d7c68deb74d9ed87a69e9d38506dd323fd6aaeb738ddd44247bcfd90eed08"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0962d11fe0ed8ae0f1ee41a471f7979e091ba303"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f36d1daa396c2eabd09d746c5847d54ef6bf827a5dbdfb5ae86257224a7abc7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e44b2ed444c6a10700414dbb844ccb5963ffc51"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "96516c2ea081673bf183e6d092d24fdb490858b030248907709999457fa0491f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12bcd8decd04002617bd3668e11b2713577df899"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0de9efb4491b088d9eaa1f87d13441b095ae6ff307e2d987c17fdf33a0c390b5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "beaf7cab3409ed49f2471a3c41822041d39f1c0b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "985e41d991faf4a4618ba9518d81568ed999265b69afafd8b37177d4e16c07d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cba5da864e2b3608e494ccde65720a0a33b6373"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d98c16b16ce821e2013df70ed58ddf53b2c0e2b5c43aeae37430e302b0f69211"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2fbed3a55f9e5c56e1f966bb9b4ed18277ddb8d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "de7f7886dcadf2d0d863f7016ca0848cfa81bfedc00006714f8b62630b215433"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94d820b398ebc70ca8d31aa8615dc882e1d41ee0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6a98f1802e92d5bbc66ea9d28b33edac60538f7c8bffe9c577490201f05a0403"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bd708c218195738e3da21240523f7250b24fcf3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8bc16c22fc959c8c480aec20a820f52e75d6f4653d571a45c3ce65a0eff01973"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "f41c7cf3788686c68e9076e95a943e421a434de4"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "ce8b01a23608603914b7e55551d996dc1af9c9f2ab78e0ad848056fb44257a55"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d83a667f9bf8e815a45541b7bd947df1147f5554"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d0351ab9a73c337dde821b1382de64353ea9cd52a31033471fe5507a51b01cb8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6931623711d44e409434836f62b7f617ecaade2"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "05ba1d6509d99f44cd96ca4182f68a280a92f397ae51fd3cd9f66573cb1cc696"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v18.1.7+1/LLVM_full.v18.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
