[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "83a18f414eae212b19fdc137a4fcbd9982fc7ac4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "c81f2efdee495e4c54e10fc85e1c5a7735668ec282a00960a1de32ef20a57b69"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97329de830ab603b55a9e1ee0d01ba4d256c87e3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "71c22173f2077ac030262ea704ae97b0f7db81f2d09c8104da767770f3bd5329"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdcb22e9bfbedd37fd5f32abb1198046385d195e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "33f1f5e27764a0b4db93183867f859f4ba8f93185d73ec044f9d4426b5bcf6b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc98df3e560075579b61377ea44c1e1546a44c65"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7586bc589353b5c8d5cf5dd5580d84bf2ad2ef0edb0f3c4a2be9095cb414d197"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "535eb853d69ee505262959acab6e86e0487890fb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d07ccade504b5c8044a053412b0654dfc69b60ed4c58cc15a7589d3c77cee62"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bee0dd76770d0a7b23cecb71a5791b42da72c07b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b55cefeceb9b6b843dbbeb618769e7c6dde9026226d6ec15734e1544656e32c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d22d350d75b9b065d9156a5b72949273032abf5b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "50b0a425b1c3d431e7d3a20e36c1f2868bd9d26363016ef1ece8d0e838363da4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b80914bc2bd911c832ed4dcaa06e3d328c69919"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7167e13858c2bde5a1de634016ef8f5aad180c2b81d5aa155238fb23805c48c9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5256931a17483d448dc989e90ac8287c0f008b9b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0760b900cf28c5522e108e0f5d89052424c51f54577297cd55b28328d05daf62"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4d8a8edda87410256d2b6b854b34d495e14e6a6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "be9537e39a34855f988c9e7fe6b5d83875db8bdddbef1408e80e3e0dfa42f053"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a4f7da48edcc145d5cb974e69b25747adaf9e07"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "daf2762336b98ff93696b3d1308e45c2cdf5d7d5e24426ed0a2475c29413435f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03da2b0955021e3374472878861d61695b06caf1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fdfbd17c2c095a7d75309db446d8c810ec32357ecc7e6ec1f2840bfa1682b725"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9141a65073bf5d70b84c70aab1667359a06c1f9c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ffd6e472d9f11f7c5268c7a2853737feef12ed019a69f18a5048e2e087683200"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c93bbf1668841570b6e452919e5b92bc6638f4b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4b85d7cf6f3b7bcc632f619a3af63257cea1776178bb6dc6cd21aa9464d58bf2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "597d762e32225ac692e56633c2b90b5f7364a694"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2b7618136d6ce9161b720755fc3cd9675631c293e98ab9665f301c24d5884d60"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dffd0861870deba7b79bb8b03c9353fb1803bd59"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ba045dcb900901123b3567e83669902334224c0921a7aad170ddd67ef2be4363"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28563751972d7e1a277b5f14ab8b1b19e8f8fb82"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "991c7388637aa10bd2a64b03852ff0ee4ecdc14d38426a5b5889c65cbd275e13"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68a246e4f5e80032f5998061ffaebd05787214dd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0da7b2dd789ff558c9dfac39076e020ae74e5cdbf1435a672ec5099b1f350de4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "366d5a00a38d6ce8b9a2358b82969a72b04277ba"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "58187b4fa0ca908e88dc958ea9dfb1a447e534e079ad22ec4111eb3e27a61d58"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "12c3ffc00b8ebd5f24eeae5b02862569f8e656ba"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "232deb6c92996591ce57752f53850366810ea082ccf5c28c056c65c8de63bdbc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fa76fd15ee1cf37714b7f027386b3e1fdf260f1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6a9e45b41c98b6333ae6f2670f8bbbd5d58bb8af53f1d801547c6e083a8c5c65"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "290d06a089f634a44dd3a8838acf3f08dbc77534"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9d8a221531fdaab9848848e90cdeea45279e02429f18458f83859d5babe3e140"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08a118477f85dc4f1e9eb29c21b77e6e6403f6c5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "86ea8404d5d2f021b38bc1f57c0184ea4d227b947a07864e7f568f0ddb65b02c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "324ab6d017510a44a1c36abf8062b4329820c0c7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3fd9012bdde0190ed2528aca17cf6c7f7b20531637ddaf9d5b65f9d44640f07e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c083ecfbf370f4fe031d2af2eb05bed5f4cde03b"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "63bcf3d742265b45a305f910a548c2ec7a7f06ee34c3ebc03e53fbdcf6e14015"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "797a31a5e596b294e831164402063cd4e3f52701"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "193585eb04570da63db24276e7db7858bf98f6d7563524a7242e1f0649635917"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2c0845d6a83fd9befbadd9db74fea197416b2bf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "35dd427e69f31cfd734e02a1ce4fa6feaf087fb97c272727afcd2caf3773a3b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v16.0.6+4/LLVM_full.v16.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
