[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9328378970caa7487c5f6dbf99c991523246cb65"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ffa4bcf933f71438005df40241d42093531e89d2a31a6720b2d008a565633115"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c7b6d2b5e38740e2cedee2b2d333ca80fc26391"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cc75d636761a40283428f76492643cc39a81160402576456b491e6d5f8865253"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55f876daa7f7fe02a7bcd1be776f388fdcaa2d61"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ef7847bc3c68a6b4a1669376d2ce18e6f23fc1e65017082caffb5138810175f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcdb4d8c05286ad4b4c1696623a9a88365204f20"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b75c28a066a629e0582718eb0377346dea5b7647fede86d76740edfd755bf64b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4580ad8ec958c6c72f70656321f3a5e59c90f1cf"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ba8c10384802bf0b7ac0ce4067c2fa917432d328ea751a24a353ad03183462fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8f741ca44a4d3b337d788cd0ad02a19f0b5105d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "455c0afd6393cf46b3e07599e08c14ea140b3c4db48de3f7c43bc889207fb6b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1935e74affd9d6d3f2689f0f708ec0ee0fa32d48"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "0ff4018f067fed36824985f407fcd3fb71845aa11ffe2b7a32873d6ecc844491"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07733237b663c684c8cc606454fbf4812c0589c8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "93ab1a463b576c536dfb2139c5b37f2adf091f2e82a2a996a853af48f2a61e5e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1acf50344f87fe4dbd4ba34a8b48d56d09f71623"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1642d3e210ef0f62dda20534a52fbfbc2687612f4bddd2565349a944d1386378"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "233d8a169b8fc983c83d2d1629367c0402a46d7a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4c3d017e9342bb7ede3dc64023e72c67a057c3239da08afc86287bde3709b8c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93f4dbeea4fb4610452097e2e241fe35325a121b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6453a8074447af57ca338d69bc5f2a7a2744628a3053d3d66c677aebebb12ba8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "716aecdea3ccb590c5787c96a42084c7ace0b5da"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "53ffa47dc614778290483a9d2bb6ee12d6b7237de3e9fbc555fabacbbf8e13df"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97eac85c87b9ed9307a53d7227631babb71cd633"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cf2281a0c9cf6f25f8c15530c673266a69eab2fd0c6da9f62ec6d2097053bb0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08355f27e80035a7b7e8e1e783e15797caf4a836"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "1d4fde6d5b2d4e6a895ce94e49236c5212821b1dac1fe337b2d3125735a1266d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9703167bda9b606891db4c193714eb739053794a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "400e7e7ecd94887edd68ee7d54daab72af16b2d07e7e14ae54d28c327b0acb74"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a56522ef392dfc130cf4c9a2ce4aae52d901e8a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c77ca33e32d4c049931038b951d91d417ed4c6666822c0f871f01629315c9e72"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29603b5ead781bb3cab4455fdf71bbd8dbb35c85"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d1954d3999718d8175d1c733e917de82c00b31ec7953f23065de3e0b32ccde4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc37ca8e74c770ed9af2e882547aa106e176812b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3ccba1e1a05eca95d6542266af21d934d482133de8ce286b97cfa2727e5b0590"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5eaf97cd752babc6947d2ae0e40d9d54e52f634b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d4e8858a53f6590de27bafc7d3d0ac6c41385e4da8170c8ca2a0b137126f6cf6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3490da7d2ac7639fe658a9b8b153dd0eec2bac2b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c6272016e57b3a7c1606ea4da7842e914c145503980d7909b538949a41e75a64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f9851d25ba35348831128fd398de6eee5324147"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "08e7d0e489ff353f9221863ea2c0d78bdaee194f34ad27ae4b6fe0e7e9da1774"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f78fb0e5fd11ab62d40fd90224e67c7f7e748d0"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b4d522272695b3b1bda6f175ff0abdf314bc96021e06161136daf447e31c4891"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6164aecd0cb3dbf42ebe7f608e3ad144ace722a"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f3f7e5ab284d53d70688cc74581279c3be6b788f6b851d86d2f38547dcc0e555"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba2008e44317d45223baaae26e39c44ff274907"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6b0465f5117427466fa345d379acf3c37eb4cbb529aed991b0a6be5151f9f9de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48f8588c790355a96629f0ded91c2416236314f7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "72083a557d391fe9165af89dc454897956bf44bece35575f6835f0164a173658"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eae3b0986c9ff02126d707bab0b2e1459f8c11a5"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "9c6209e0f1467c87ade4ddb8b1e689f933687a980291a6a6874f6fde2a337cca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+0/LLVM_full.v8.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
