[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bca216a1edd0de1e0b11bfca68c9120e81849f4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4358593dc61cc1ce282d775cfb4f578a5752a0b096f3f1a5195520e6dd583c00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed80b0aa0bd32b214b0a0266b63bcb0d9a3281f8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8169becfb56d86ecac1c0855e37df021b0ae807d32c3e1394e1e75ac971dd36d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8ee77bd283c5b003ee9333d602001c08df5cf8c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "51d3d8107181088c85799b7bf08a2ab3c2dfb8388b7fdc4594e43609a869ceb1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c35b67b4f07ad1f8013d7e54b1257aa24b9147c9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6c3ccde3822e44c51015322b4cb0d6537a5d4811b921bc29145655491482345b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ed02d1b71e14f9b6118cb86fe55529a4eba7ed1"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c0d4d986bbf04d1e1aae017d959f7e4666f42992fbb06283e1c9b8bfee013cfb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4783337799e0fa6307d2d198efb0fcdd048f6f25"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "97f851ad722ad27d428a68ada96af1699f59f669f4c6044bdd435a883a25ad0c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2b8cc1a0e16ac95d561e2dec29e41da052e9ece"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9280ff9704a814a6820c93c384666598a3fd7c406ee8c0489a5bd811147698a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a13d9f0da2b5fcdfff34026d99419fb86a789426"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7cf17b48aa3253d292492a83009f63d16150e68086dedb08285d8688bb9599fc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99406bfc5553685de1fc6d6153fda1dc04c71f5d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b8d0f53ed4c153ee3b26205273a1295712722ecaaa362cbfdc3a13b793a42b22"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baba880ce84c452fd3c70d3fba0f80944f51f3ac"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "69e591e760284caa4f518274d62371d0085cf4065bcc172d9b462b6cccfa2b57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c7a9a3ea6bedeabf11f9e1f1895bdb4b0f8571d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "724ea2e8c922ec19d8d6aba58f7239caa9d106867a98697189a6e190d9e67ffe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65073824c3d3f57cc7dfff38653957071451fbc3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "702063a7d44249beaf8ffb7703db1c54f8f53c2324f64dbf43d131ee62c35d6b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aaad2fb87cefbccf9433eb758738c0479271830"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e94f6571289c0fc641d3d5e3d0e39b2f5bb94c866b5630b2849ae41b6c9df7a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd74a0f97bad93035c4a29a6e5d4448685fd6f28"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "75beb1f037b6390ed763d6756cf3c57e51dfacff4ca04a048cbb8ce67a83122f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb147eec338ba9b44dba3fab4cc97ee223aa3aba"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c42742d9312742e60a39912da0c40163e71be8368aee067a043a470bdefe04f2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b266cf1910c11ddbe16be5cdb6731eaf05ecc04"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "49b969b2af6ce68aae7c46f9e43af304ef5e30be887db93ccd2ea6ec5374b82c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e299e15953b3634e81108739acda0bfa6603c40"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "bd01479048fc1b9141511b63007d7a49b60d72ff0b30550256b446f36b769c68"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f835622b225956a2b60a82c7222ad8a757c72241"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "87aa72e8d4aa84d06de72b0f0d93a12fd190c203015b160f7629a6283d26a814"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85ea5600d499ee6fde9f9e487cd8801f1ff54825"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "5867c5437fe956ee1119a573cb91fd16fc7ba701d2f6837283a5e6b8646eab8a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95db13a4e0bfe5d1933fe1f2bf4f10e213eece16"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "366b924c4b23f083cb1ec6e619458068a50b09ffb05582af23bf298585b99cf0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf03dd085c5e90591eac234da3fe7806e5222131"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "485bbb144f4ad95807c7d55acb0e683239bb7ed68ca0b85a9d09736e5782a761"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09520ebdec5211c7de38d02a896210ef2158b618"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "feba04d27eab73438f2fab30db1e9c0113c1e4cc850d8df8bd1cb03ee235586f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c242e8b89bf45fff5163e55a86cb93fc918fa596"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6f419a1d7e614f34c3b0b5d904b59cbcc7bc8e4d8fe7c5ef9c0c93ee9338630d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0bfd58ca45807b24af69bf332962825836d9c9d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bc947fe7c16327b565bf681d750d0f641515365699967f50d13d7f0bd6b5618f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "165e74ea144bc1ac5b8e862d80a313cfa9ac4601"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "e5e554578d2d101cce370ffb0277d927399aa0b87da734955e254ae7cb52e47e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23fafcab945d9ff12377846f20dfa4f5bdcdf205"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "417ae26607bc5891b31d03b55c52c603434c60eabddac2254964a1ab82fc454e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v8.0.1+2/LLVM_full.v8.0.1.i686-linux-musl-cxx03.tar.gz"
