[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "26c25c9b3908bab836b3f3757585c6885cfda766"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "e5b8ca5e6bf38b89b9094707a2dac6753034370a1e9061f4a76a9368c199b6c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0ed1f5f56768492a8426c45047ad2f4a4bc7816"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f47f79c0e0619088824b9f612930d587242adecedf2f4d46041c41727fb2e8cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d03a31a5265ec4d01d94e4e7c38bc3f0d56843f6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "adf67c5e565a723f1b3c17ba491d511b9d00d56d30f940a54aebf1fe1e5ad793"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d323caf68df7073c53722f4c03eac6ee1499c7b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c4adb2b889e1ecc567e31f5bd2367fbdbc5264b9f89c57ab97f4b21ed4bfca39"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a30dd03677cf84f276afd4c3eba342c4f58f224a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "80979197b825ee1ab743495c2bb8a1ef4056a63cf4f69dfef8c29de0445e4c34"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2581042335c6c3b9327e42ea90fa54acee7d195"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "26c558980e74da4684e04863d0397964518b0e16326cf65052cfb671a30300fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b3cb56f92b0ca1d9789ffdad86398f76981a861"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1e296b0bb8a60d6001a9d4d53b5815c07c7c12f87379599f9d3f739c693e9e7e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "123f99c1dcc0287781410ae634d3654dd251609b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c92944f496bc2604910b6ad2ac6dbc672444e64c98e8da66647cdb07e9b6810c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c624e54eea7a549bb7e5dd02457cd822cb15f757"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "509cf631cb61dc5d743ea55c95e67e607fcecba75607fcdaccd31a69e10729e8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8f992dc378ab9e8d087df085a261f755bbb54de"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4b24f98dc9ad0d7e96784599916a86df3324df1cd90bc0eb16496c6250cb1710"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7d95ca838370ea267ec46fc19a0c9b83b8bbd37"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cc5a7ae856ee83c3ffcfee950c105430c7c156b4a1b015f562c9f9ca8f2f346f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0282729f2b5034f565a5254b9ee031b306c68902"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "48514a52ddc8b674efd3c42804596e4393dae8e48924f364b98051bc601bb9ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a02a9391ed3efcecef117f09565b10eb04dae8b0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "25e2ab5f29f95a3eea1770215f0010cf962d3dcc1dce2ff3f125f6a1496253a5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "918b24dfaf3214c9aea2242038d9abf602ea4b03"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e10d06ccc23c429ff9e7ba2836a0c3294e0ee729591d1a18317f7c4f118dc017"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a8b54bed731f46bbc7bd103544cb0743cdbfb4e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e070105f6776cb0f9e00f132962a35954992f7ad6122d57864f650548d743b69"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d92477f251878bbb660d24dce0d0c6b08229b84"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "ed88396f085cd34f120ecfccf2227e1446ead8d352d40857574edc057c7491b6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0021de075d16adb048c522174fce168888b48d4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "14d60bfe7b4bf47ea02f8f32e81a545da03617646ff2a3ef3e6418379a287b6b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "475dde755d3cd85201be1426b0efc274898c1ef0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b8192f3a5de0dfd12bb61b55f4d497c6c94fdbc339a1720513ce62244b5df9a5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e5f1b4aa609e327a9b3799e9d1c1dd4b120345d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d609d5200d1cf2149b73f46bddb79401d0e2707e667dfa95bf582fbd41783edc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "70a4ff35cc501d36f978bb30864c1611a10c3fba"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "45999d3e260a3028ca8c5d298db18e7ada34faaced6c3dfea715a6f6a3fd8205"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "963257fe77bf83c4da08f849ba495cb60b99ee00"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c04f5b36bde31bf88eebb5d654e2fb60daa4cb296590adae24879f85a9256c45"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7397f857adee03734083da1b01628bf6782d62ab"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d5ee05f42be78520df41b83aa26b206b17d9382c987dadb186a85552cf242f77"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbe420a6e98bef86696334233441055ebf361b2b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4109987dcb619bb7a5e69b79806d03cedc394a3bde751691539ea68a349b6a42"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f15bb5fc6f6c24f514d7d7584b127c06dbce32d7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ad63f795276c48f07be160af2eea81070cc70a14f373818c12fd4635ec6cdff4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "60684aaa1820aadcfc416fc52b6796465e954409"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "e85bf28229d5fd4cf9b84c6d639189ba59c99490bdbc43b2ee8ab863afbb485b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac2050d19dfe188d31473f99fdbbba349bf71663"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "396dbec58cc659c9928a90fcdc320a76fbffa2dd02010dc618c9be68d87201d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70e3a986e4f6bd25018c2dcb27e3f9d90fd0a86f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "28d90cdc0b95e95b4747651cbe32f260c4f5b54251b45369f39c487cab6f86a7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+0/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
