[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "6ef4d602d884a717a9cc64c9361a13ce2c8140cd"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a432bb55bdd5c363878e7230558a57fa2bb4e2950b8177d8a20c2207af592dc7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b84bd1839edafa876f725791910937b2ead80a3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "26ba9e43039b8ca674c8cf7ca572cedf6056aa92e00d952c96ef956cc7578717"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "492acb1d7ae41b1c54c4d0d4435a7798aed8fc99"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "130f4e1ba6c4847ccb927bdf5397eeef8f0aa08741d2df24e01668f9b4eeed54"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d49042cbc7b3806f2610faa18dc52635d38bfc4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ac4ee9a3a13060aa99eee0554f34e2d9f63f30d0bc31e71b310974e575c6efb2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d597172cc01260759e9648d7feb3339578eb3c2a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2a1e85b1f201584d2c0231b1080ab3fc510435742b5198c11bc9b65c3d07a7dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76d4007d3e95a5a7f2c5c61b52ce59e046b23d08"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2f0f21936d80c4f6053e923253f3d4219f24d18d264a9070de19391388300d04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63f682f9f33f88e1b879ecd7d70f041a00a0b915"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "45fec9b190052f201810bf3f4414778b747a8f9c29cc548af1255de806131b92"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c682072d813c697b839f32d244366aea046e548"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "570e0f179b12c1aef2c0a0c39dd2b67fb7e561ba1091bea7f1b8771e8db4e4a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d81b671e844a2cd66a0819a0522f65cdbc01dd5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c20d54332cf20fe4303584bf075f2a0d7f80294a0bf6cc942e0ebd6aa6a99ab9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d75c320c884792f9f5f70e005ead7bb39e30ebe"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "80a83c6495c6913c039c71dda4cbd1ad44b3c8d111fbda057470a3f6e919d8b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47808f31a0fb3414a5e8c467c4a21d1f3143c221"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f723efa75a441ff3b9851f3c9f98f1587444e0906d3fc9f07d2fec1319f32233"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "766a95bf562924a8af059653aae164ef4329cf80"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b3284357dcc22d27c2cc68fdc46abce1dadf03eedc07b4641470bc09ea193fad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0596ce2f8619f0c2a00b7ab16f4a61fc6387d227"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "805a1d7d4cdb177cc0c12cf6d1c33cdab528700700a7adac1aeb4a96d8b4cc54"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4927fcf80715666c1ec97917c42863895632a3f6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "45ee028ca09697ba21bf6c06eaf77f9bd11e706d41a7574818f507894e055eaf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2bede2d4dac96d7be6594512c26f136c48e1afc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d82a241a5b38a0e38e86fd515e6fc42710e56579ddf1dea021426640e2bfd890"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c409aebf3ed0abd0a057a9fc1c97aec215bab16"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "70869f4cb4f612271429306ffdf7bbd1b0e999904fb00723dc89704853a4313e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c2acd14ffe990b0e85a46b1e726358f1b2a0a5c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3e447ab944167a2685a6e7a1800f622cb40b9effb4d3185003634c7510b85b40"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30adcf24a0b7d1f716308b52b6530ce1acf186e3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1338aa59cd4d16412676b25e5f73375cffd0023be8e01d34a697768c66589073"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42c2d2f1665ea28393a806d40c6357fe4719e12d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e31a45ebe8ded05cce9446ac4c169a3083e4915fb8faf231f1164fdfc0538579"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "110c73a6f74b0fa500ba25343329dc73d5bf4303"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "1a4f2fc131fdbc2c7b2fe7dc61848af08b21da4d7480eb269163c09b6e126a30"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e764b6acca9e5069509128bd2df68e720e5b3d56"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d9005998f32e89199418ad9ff882b69356790fa71d0d675cd7337a3e8dea9d0a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87d5a0a59e820279126aab1db0a62a90a76c42ea"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5d9171bb5ea2d418ea85c9b5736f7f1ead79124240319130f749a315c5e18645"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2401c4548126ed5734a0c7e41622d3a645dbbe7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a44f3651719d53105005bd8365aad41052aaa75c5f191ebb9ebd45307023e78d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6d09ab104c5e9c87fb256a5331e1c661fe3ac61"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "081d3158e436b81836aacefe9a64e495a8a23f4897ad37133d5cd34d443c4912"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "f5dce3f16117c81a2aa8aa2f272b88a6fc998421"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "db47248cad779591bed3b544f27dd7f44475f5549cef7302653840e632938206"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be39e17452c6271d3d9b7cdde123e4d283e4fda8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "52a5ffb64ff3b028ebe1accb5e56e7a58ddd8e6da7ad26330476c79c29696fa1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6782ab042e5c766740c059ea7d8bf3215fc05a58"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "19777ea1e53d21027308a3d9d8b4812a018ba575d573b34956f389bfc14c0809"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v15.0.7+3/LLVM_full.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
