[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "9aaf00756046dd80eeb3cd541e1e78986ceb6146"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9703224f83022d0051be087c1efba7280260ba7e5df6a9889292a9d7b97ea019"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0cb6d6954b3029d687608ad713c2bd5feb3866d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5f77a25c4efad3b849fc728812633e939f887642c7be3409ab2f5ba1359f26bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d75e88e4d3d899e6b366352cbe184e835038af8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "497b049517ebab06a4ac1f3af36a6c4e026dd92ec8ac7b77ceef3f30b06205d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "829ac264573f03f74d70ce47c22d595e1fd16ec9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cfaefa4aa79ccab27a6200ef24bd2e5f0bcdc0403edd425f835bc6dfb830571f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e41deed348c3235ffbb1fd59833d59fd31153b9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4c9d83a480c2bd0df7572cfae603d38add54e51a150ea7601435c119bb584b0c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "951848f6b550073a95b9c567f13c5795c8d9f7f5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "244c913d47af69f7222ba8fbc542687a8c49880b47871f3ddb787ac0eec40cf3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef9ab4d2756adeca8b4a48395c0ec5246bf7dd69"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "494b015c8d4f6be586d90d7fa04cb82d5b5c7fc3d7676197394da07e3f1fb18a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32c92649b7018751e7efda4c98d05589b431362f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2c67c8cc658cb8a32199e821897e8bccfca66d3c263ae3433c695fc514cf83b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cef4cfc177f422a6fe035a170fd995cee5e365b5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "189cf333ca0da32053be2e03b4ed5030364d5acf24695f5c7be21aa78e507204"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ebaec0cefec768c31d5abc90e42029fbfc3bad4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e8ab22b92d7792176d46190e4421624569743a0d2923b136782bb600fc103648"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89393731ee4cb833af6f8ca3247ab876edf89ed2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a358c6de08981076542c62a6e344c18fcc16315e9a6bdbd818cbf7d10f451c33"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "591d31935a7f99387c079cd3049650edc2492da9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0fbc9aae3537a1593fda85c799f1c8b838556ff2bc03edaecb40b78e16cbe8ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8099e97a5ead2f4237bf82595d2ad3925adcc72a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "450c6266082c234af0648cf7cc1d5a44a075890ee25be7f9c99f788820121355"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be5a279855431511af03c59f0891b2bb00763bb5"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e7aab201f8deaa24917c4292a29c39a1a01e0ce02b06bbb805f12e2905a10cfc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93ec2e97bf0e8a05e507ef75b19af44e3cbb28bd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9c2037b252428a7075204f5c461744e7115fd8b77153977f4194e971aa10ec7b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84101b6e3c37937ad1b573314b656b9810218d66"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "07314ac3ceaaa62c9acbf8b0c5cc7d6eb7d836c7d8825c2740df354992b38a22"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77e9ed78b4c989e60fb053d95ab9573085715e01"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d91aab43c696b4131bd602e64aa1966276aba6b1e0023e1cd7fe75d0a5d2434"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3ac326bd6ee67d664fa080c9a282460532d887c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "1dc679d58589499bd4be31f9ee30de2789989d469c1e0bb8549e93b4b25815c4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "651a2c4ac8ff956a140a2259943d0225269799f0"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "44d36e7d573feb85150d18160dcb6f823bf417ff8825c7704547a8dee5b0bd08"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87b0d2551422fd10c77835a8785d1fe99282dd74"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b764755640ac56838a9751c8889605bda8ffe4fd27d251c400fe9c3a0d90be82"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f2a51a6d01d53c88c65dee1d9d5d8f7d8af7e0e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "184f7dd988cbf0cbfba54acd63bc0a4a0b33574b9303cb7784e4403d5ca0838d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "15f6225113382a50c28982ea39e6b67922e192fd"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "9175152d576f7256bb6f25a7de6bccce053dc7dbf502e32a9383ff7882c41560"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ba0bc283dcc62af7c282f7b4bcedb764dc9c64d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "15628c57c84f0d7ea1c558cd37c7739607c1ab48f03c503669178ad26bf60770"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffd25b575618865cee0c288729a95629485632ee"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ed9fc4619c189cf80140c006393f092511ef6356379526e4bab597af6fb76b49"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d5e3f9a1b38ee28ceaa8e2730206202540a3692"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "77e5a10d4943eae96a25bfce7348b2e3b47261d8f0dd180a1579ef711c1db707"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a318f2d0c6650e418a7da48e0993aaa9679e87ae"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e8fc8f91de48fd78c99f0519fd274cf687fb5f21205a98b74dd4fa3ec3da90f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "21930de56ed7019132a386a59999ae6befe23c74"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "05ff64484e8711d396ae93505a2f07aee92930434b332f2d6eda6b619cc7c229"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "213f6d5a46dec2b03be0f998b2e34d91cb14e5f4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3f70a6fdc78cf7371bf0f174801d14f2f944ce822787cf15f52be6f0be01788c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd59317009aa86adb90f65c04871214076578616"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f72e8400e0d162285c21cc3f2c88b7ed424b8927d16266c3705866d1056e0451"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+3/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
