[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "d3f13a38c1d5c2d5d6c9f25304a52b99ca29efb3"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "5b738a4999f5b9ce3b0662fa14c85ad52b9d476f64aad52767415720809accf8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afa6774ce9d059ffef1d6e2e73ad68002f58e326"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b37f6e304ed095564a1af78b7a613a2b0216f712dd50307415aa41ff70bab77c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c19769e86271f5375521cb35fbf7eb124795d883"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aa460a265d9ddad5884fafc33f2d908e7689d8cb0ab46e11290cdd987a8b29e2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d509d2e58e803f3cc1fc31dfcbd22b0d9918b95"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "19fae4f01866f54d203a64d480ac686c683b05ebb359cadb5b93cc43a3dd48d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76b3fc1acdbd2acd01f1d214e836b1b29da12fb4"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ddc16689eb9b112a681b75051c16d72f06c6d74d95ef86a6329f602c78baffa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b98b9c60d3c1eb8ff9b66b16282d2f28c00de8a3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9bceb67c4b9f394ef6e110b3463e68245ee3e0ab57ab43af877b60ff25c2f640"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9af946d1c2284d8c0ccc3a58ac36813e9f518e3b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a555317a0dac63ca4f12e92c9bc88f1060b2c579f1bfd90b7c78b6adff685554"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d5e69df45fc373d6709606bea6b0cfd3d4de118"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0a7b407400e3bff3a1d6653526e589cec9c08c4398c6cb69f29ee8096f673748"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24ca095fc81bf2dd01be809e975f84da0f018990"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5a31a96ee32901d0ccdb63416c95a20034436845165d980c09334adcca2aed16"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de2796534d329979dec33186daae8c0c904bc4e8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "955b7a528a53dbe53c8694e7d729b90f84d8f85fb600d8bf33cc0a40c6e072a2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c96f416c1cbdca4fe7027d0d57d670cfa3fd2fe9"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5fdd1b3acadeec3b3e0939a596a1f6190d274b68f9e8947723cc914ec0a8a9dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7811af3d77ab978ec6c845a5f5f3ab79e0a2b28e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b3b396a458247ec4072ca35297dfb6d1d798ffbe963961aaf8af667c66dc0339"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d0911fc0faba8b59949024801b8af1d491814a7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "755767a2aaea4d80ffe35179c7ee9faf95b5ee29d361941e6b2a112e74b01cbf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "982975d45b5499f71df614c92253c229f5f66082"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e36d78583d6b49ca5ee6bd290a39efebf7ac52488759990531c9b6e510ab83a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28d1daa59ef1c7f308351a316d01d91c294359c8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6fff622a01474aad02b28b2bd1f7fe2df2bf97448588e56a8cd417a971379611"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d040bae5094a3338a3d7399b6eede97652d44144"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ae60b6d13e5f21646ad70ce8b4cd2a0d9b797c7be0ef53e01fa65be9f1448c2c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36fd38e6277b5738b820ffef0765b0191cc21a94"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "812a13f81991d7d118164865d0da81dd3f68d0e5cf778f74e7d24b046e860e42"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf790b4cc87032849160e06db3de51c73ff671cc"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "7110ddb875b001d35a7df8e46b8523811df7076dd58f77633e0199aac8ed6f0d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d4153a72e775233f70cf41b8795717acf7a064e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "9cf5b33d7364a48eb2f77ff43118bd24fe9573f903737fab8c00a188b3ed5e3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f57b6af120b088089744cd6ab2d19d818e4e995"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e8d114bb648b5c0ca81d95db2214aa86e7e8e13eccdb5a70ad8b95db692fd636"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7673b158059f66da78db6846a5950a52e1486f03"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e4beb1b21234078fb08ac77d729d14f4e45ca0e22f93c9c848c40ec6e57b3c13"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "fc1c98713634afbdcb341a882d7e9b34d04fb4a3"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "986cf78ce01e2a1f46f4f288f7cbc60571e70d46ba3d861ec3438904a9e4a450"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "197a1d4d3ef13e5fcb10d62fbdbb4d6a9b9febfd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3601c8705fc2af0a061b681e51a6bdceff172b2b79add1c38bf99123736f00a1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8525442937e3f1f91ae295e6e001495ce7b5c18"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "20e856dd9d398700aaa06f7dfd0647ed8914f102ad11790f231f159bcad90500"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5acbd7eaef1884045b40de77b8ae0c8f1f0e8a4a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "478105422ec0f5b31f78f12a19a0c594dee5a857ca9bb70685e44652ad3a2a23"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0388dbc9362c71d5ad438ea75e8348ddc37858eb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d592fed067b33db565e945f4075bf10f71130ebe563fc691500529ccbe9dbd12"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "399e0c23b98cbe8b706d1eaad0c80254e2d09690"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "1808d65dd1754e4c6802d99f50226f3da01ba2ed397efcabf2d356aebaad59a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74678e584a712586037974fee5b14388ae1ad9ab"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3e74b06f9c079aea53995514af36af0196dc490303eb721d9827843ffee0de57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e83b154f6baa7046fe82c3b5e611fb053b36263"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "1bb0e7db78fd1768bf3d1993d26ba2b5637bd51176aaf75790a9b87cd68fbcf7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v11.0.1+3/LLVM_full.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
