[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "27ce017910eeb4e94e60a516f21df7e7f4bff7f6"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "45a12935d1b1b5493430571b33ff2c7bbe4ef696dc00ea3e5bf617509ad2461f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20eecb68094adbe584abdb33ff843ad5c641576d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0e00d45314142ca56cfc4cda2a8775e1d5f0ee760e56da15190b9779315a6ea8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a08ba6e43b9d63d0a92f13f6c69700b88afa1b4f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "02d98845b587f3cc1b5856f4a3bfbf12f9ef4d87ff528ea0239d1543f21a3499"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223f50647d6d7a6fd81e272286a3b0b7c4dae193"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "25549237f113f11e955d7f13218611567055a2f213cd2137c665372991172557"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e0c1449fb17868a4559aabb93de81c26e556730"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ff3783edc1965325862d65762d6c52b741e9e00a182f0a4f8f80a6f30bf281cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "251331c2a339341da803af80bbac0819667aa75b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e8ee1bd168c7cd3eb48a6359d3cc932095628f2c730a07ee9d75a3ef3b78bd21"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51a00192c748437166f1d9788c8b0b8e5cc27bfd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ba0bc1f33a76f052886eeca3fda722dcff3016082b40e273025f3944b13c5990"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a757c9c797e91c1f9675f70f24ae1cf1d4cb29a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "966345deb2ca5a295e617d09256c7602a7240c8d576f0532b2b8acaa4b45496c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "859057571c269bf0ef194667be8ca8684c08fb17"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "45a0036d64f9480c5fe6c22975844e0ceda7077e3de4dce0f647bfdebe24b214"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d9f967d73f2fb1bae383e323c031e490206d5c8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cc49e6b548d4f0b53dac95d58cf15111678b2e4df86a4f7ef4701e9f32ca9d5e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95d93b513c9a6514bdd3a5a5ae7ac87c83b36140"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2a6edbb67a6c9ebcb9e90fef9be3ec193af233c8693ab36d071463346fe82028"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06374b7681126e91b3222ca03410e417aa040621"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "11d14bdd93977698b41375465b139926fcfb98a28ed7e625a9555bf6e02b41dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b580614598054f31180724202d85f5a2fabcdb35"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b251ac5649acf4c9d1efcae0d1108b5b754f52ef0f705ca5b5f3771fe808d8b2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "023fe9ee4b30d224750b10731e7b7b78de9d8906"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c1ce210d0769e0e614f5cad1be3f01e7ff1b520a9a162b1647acef18b76ee49b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8964c5c68dad549cebfba3e8a8c0cec093a484d2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dab0df2a66c7fa3200e5902adafc84a143fa52edf46b6abc30f36ea567931d00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ba6f2096dbb427cead9fdc55b98be5dec4dd23e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "724898274831b8305e83319075e0c6d114f22f75bbce7256d23a2079a0d33d39"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a26a0cd692ea31833143f1bebc87a9b49b67c9c4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "41770cc48080c1e2920b834945d5e3fa7d80c4736e522331e17f6521fb1c83aa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58c01b5310000ea771d9e6145d89b33299c28357"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3c47cf7178e7c5f2f4cd6ddb59353cf55fc62bed26c039cc893830d8687ac533"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dac500d131af7a39ddbf5e5f9366ba16cd19cb94"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "82b6c7abbeae685d50408ee4b36d17c3d2ff4493ac884e361a89932ddd7b06f7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "e2c824eba7156f877b9427afe87f86d8211c8b07"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a7d36dc34b7214a2e989c140466adf4a8a71a83bd663f390e57b7d1ac1aca18f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09f43070fcc76891e7fae9c7b9e949afd6bb0d4c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f15226b9713651388b00375d3d11b398e540f51d6d0eadc06bf5c62276429c0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3997526cf93818d99d15d579fa7193212f78e0fa"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "60497db90a7d8b6fa52182fca5b1193db67661e27560597e6fe2ada5ebeb1f9e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78e844ac5535b4dc80bf964f55b723d7d3195d9f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c4bb9fce3fa1e5bb293d40d802ba3cfe7cbe25889e7326b21c3022f530b9a117"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "036fbcf50e08d5e865474bf07412634b0386588e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c1c1e576bace4633084f10c0128ac74edaabe8ad6b5136b14c1d90684645c06e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "446702b994580c1daac1fcbaf00ade32f8163f44"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "baa832b9d91aaae1c5ca31412737b6525e098c029660ff0f3e56881121a93a8c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "451e22be622615ff5bf99b42b566d0b2465045f7"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c714fb6970f21550ac1e5bb27d0a03d7f4fa19ece77313d77649d6199fb55764"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b831fd1d0b59060c53f98f6cf486d1259bbaf7e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "12564ad005bc5d6957c4069f10d841fdb698aaf3dbae702216099edf598a3cd3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v17.0.6+1/LLVM_full.v17.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
