[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "50bf0380475a35ce60b43771e36dae575c5b8947"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "7a75af01034c67215b100c7b5f279a4bc6ee31e04c655df589122e8da9a2d3ab"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9572f45dbb8ff50aac608492fb5980e8abf834db"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5c3925bfbee70ab3df2400797161f4780a4f945d977aaffaec77895d8655dbd0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5597453b36ec187e7f774c4a88cc71d13ce051b1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "cd391a560bd6a263b7b824b05f5a8117f2ec46320a9eecc3d60a3774cae371e2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca47012c29cf327c26a02241f8e6bdaf22cfa2a9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "34aec83f8d5459b0d1437c13060b08309a36137d8acd1041345be3c71d322bd5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a78e7cc1978c9414cc562e514aeb76e4463a952"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "672e7935b3f48e6af454b917cc746f3c9b3a43d1e0a297e67294838ed5c41fcd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c155c1dfbde29710b88328a9730ddae65ab7dde0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ad82cfcdcab4e1c3e3167201e45183913902fbbd77e3c8bfec996fbb98914e85"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6f42b6a853cb1f4dd0c3d6b0dd394e83f905423"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4556ed3bf11bcf0d0324fefbae27e03f2758ae284bbb0edd87862b4341caacf7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c39a40099130a3875d158e313303dc1e8d940428"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "814a213776f1a14f798da0d41e5f979ed66257339c709125fa4f2ae0576fbe39"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba7eb9db3f2590b5c062d72bba2e575928fd293e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "22f7450e183dcfc4f44f512d3d40dc7e628af926800b9c3c422fe5bc3974abe0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb6e68a682572c87b3bd1a5e3799f663993dc08a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "96e0792fdc35004fcca8ea079119069102e6f3795bc04be22b46972170631905"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3267f99599c3253d9e73d6b3c347b8d3788338fd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "88100b5cd51633da6abd630d4cc3106860795cc400ff7c1ab09153c8bf49f5e7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19982b0081f0cf9a4b5cd568ca88177a5279e2d2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7b2addd8b8ede17731bef34ab26150cdad8bcc54b889fb5c25bed8d7079d3741"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "405048549b230d6d1d3db924f0848a6c9551f453"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b16fcddbdf92f77dbbdeff7b05a358387032de4ac969198efad5dcb2295eeef9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7778e7ea6f9d46a5dc63f4058dd0880677ed2236"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "545aefcf20a3855f2d7b29c1ae6c3a897bceb7976fc939d26400b7a94c39aa48"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "145acbb9d655a231c499cc75d53539891d8d6024"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "26026bc2f2d0de64e70e8413868959f1b1279d89e4fa08927b4b19d9cb6c2a56"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "761c9a646cfa93c9e94b0e55cac6a6920157ae4c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3ce810027b5e50dc5cf35ab1c5726c269e6cdcb5fcfa8dcba2aa751091e1dc8d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "028fb9aa33fdf3a53ff9eb1ad7cf8565f7170074"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f49a6a9de7415d91b903af1100751f912fc7fe4fe7daa25d9b1c1da350f9bf4e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f99b30c3d4c8dd41d1c6ab3ec867109d679dbca"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "4b6edddac55c02b77a4c7e8cd3350f10027069758f8f0c8c209013d55cbccb2d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7763df9b373207b3f66830f9180db5f2484820cf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "2089f800559ed807bb1068a964797f225890f0a15d6ff5bc77fa6510c4ac173c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73b60e077356933c317bcab1f60987ea3e0ac962"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f98c2620e6c7c62046350eaff1f55d83f02ae0a3d2e2660bc356e9ed4c924dca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25f6c1f4584bcdd3737262abbdaa3ba305f553a3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "912839cea9f2fd74d06916427aba61d893c07efd4f075673439beab2eb12ad5f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "e3368527eaada671bcab6dd3cf2b6b3b5c0241ca"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "61b044521d3845411168fe7c226ff879a9ad1267f13cf570f12e2ffc7a8075c7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae500a6323ed2315c5665144b4354b1228b76e3b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "155a4ff10ba1513b41699b83d336bb797a97a39301aef9afc301a44bd322bb65"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c77f38bf3aacfff7b295aee4bf62ab9d859f2df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1503fc12cc9de4b32dcadd95d5b1f85b00996163bde10db2ff07ed85aabe53d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "502b14b1cd6d9dde7409744b3ae2057f3b62f1cb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "788b6ea2705c2ee566cdf92ca727b168521912c51f6de9f2bb71495663dbce84"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8408b1f32bf6379b0a8345251a200f2b078a78db"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a1fd8e7d4c67e39a5e96334f30e9315bc1ec9839fb13d5412206a9fbd5681e83"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "a9cef024297669511b1b4963684ebedd99f7bc1b"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "6dc73895d5db14b220d3fd1516109c97edc90a4c9a701c78841368eb483a042e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0d1bbc37a418659232af4a0e6b2a3a254311f61"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d67f75f065f1ada0dc87dd0a626654a3bfcaf8045d2b955b4f3dd4d3031abd19"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8853ec3b23f67068408a091a8d9f79938907995"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "62e12bd159b6b0e562504bfc71eb629230db2e859c44a52c7b9e05fdc7d92520"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+0/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
