[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b091332ae4f583bcef4ffa41cb439ca945cd4a02"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ca5741e18f72126e142bc0acb90a3e4298fc011619e65cbef8611399d8ac2047"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4562931361390731e04ca35d4583a45d066e67a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0658ab2f1b8e90d2a44f79a54c33c76cca1f5158af6e96275d03ebfbefab8ad4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40b25b9a1f97462729616843d9a1eb94fdbb5209"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e2ea74ee514dba1ae67ca22d49292d6032c6947ab1b818b70fdcc1a799a5ddc4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "410f4a61795b0db807877f6a20c2595a64e8ea7e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "89279a65dd600f0fdbfa6ec852a34c5b8f3021c1feb1a34210d2ebff404146ac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32f22c31da4327c88572e876ea324eb7fad53d0b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "42f01f84f7a355dd56f92061a3a333539d81e38e1b4c8efacb7877fcb383002e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18b013caa204de631a742473bf79a9523223e491"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7fdace137e5da59e5b25e33e5614a0479cbc1f4e9aa528f68f423dae9846ac89"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a9ff010de96d39b7991b1d1a53820a39f2767fb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "117bca2895728d30eaff1650ba1e0eb16b845a46dfd79d9e4cea97697aebe0e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01153ab66d793486f7c2bf8189d9930e07984924"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "42899dc165fa519076a0b362511f4a50a7172a82990f8943a795b651982f01a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b17ff09efc3168fd064a28ae9c1b670f57d305ca"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "df01aef44e01c587ccb435f04eede246c08d7429f6fc2837a60ce07b1181620b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f891067b89c20105ab2a4bdc0e726378bdb7741"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "daddd1f14e491dc0f9cd488fdfb087d15e9ff453cebbdf6447c037a6f921f974"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f24dd5a4e141ac45c213c79b277d75570ddf20ee"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e5aa2fbb5012206ba78d2bb4ec786a508c8b026b90397ffefd374e1df78c2fc6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5950a3642558a5349693c57a0a492872f951d84c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e2d521caf26c86c41fef912c6b4bb1ea18cbc38c66a55907d9e6ac23ec39ca73"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "083d8ecba34ca5b9d1ea92a8ce47b82d46e47a18"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c2c3390ec7d16930d342594518c8fa07dbeb573a4c88884cfdf1973ad63cdf8b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69d61ad557a0133519502edd97b01b5ccbcea6cb"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "732d66d249b13025e900638876b149c14dab5967720d67fb97fe6a8fa642f655"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "826dd4298429d8a59dc24396b944a050edee5d66"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "adab4765936a534fda6e35ba8cb010ef19d369c540b766dd24832b754c5bbf0c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee57ecf558a14bbb21fd342235dedda3f3d44b16"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f850c7193b504c0dcf02931834d14ca0bb51d459b21000a8217bd87cac2eb9cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bd3b2dc8b097258171173852e0d879df8a3504d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "76ad7e1cf81bc24c09ad50b28c969bfd8989dbf7eea739d641143b33cf214fcf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bddbad3f28acf0178fe241edcfc2bc0b384d46d4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "0fe84dbd22f456ccb7903c6acf5dc25936408157094536c6b69f0c1dcf2eaec6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fd00356187bc4d2b007c261125011a9e8fbd46e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "41f5f8ec772d7bde99c036801d3195a7df02a802b6de8fede66f63670f0434cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63602280d008fc0c97db4aeb4348f6033dbca708"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4e0c2961af85a06caf53a324321658414e96043d15d6217f57130aa0a44d0140"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "987f3b5eb74d62bcf3bd7c715a1e4e5d83b0ae4e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a16b5bcbaabd9c75b6ab2f968bc41fab4def7612787c43c877aef861411d4a6a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f636f454816723f84ef0c57d9b8e63ee75d4bf6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f782dce1d610f3a977f036f2327296a7216317acfd3e0155a55a25422695f068"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67867fbe9332f3160d68235535c1d8305b92aa12"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "43adecea73b12819db37627c43720ed0c51c939dcc1491df069fbb1c5b5f6ffe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "468fb4cefdaff4348f9ffcda46c078a648ef591d"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "c6e3b64da4efcaf553ea1e93503dcdcc713284f90e8126bafc41b7de0fc1f58a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4e459b62330b6effe001f64abd19bedb1fca6f6"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "516004fe6f49cd271559e64b8e9173f12e72a0a22f2a8f551188a0d987f147ff"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47afa4dda603d3bbe77ff1ef20fcc8c08b62bc9f"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "555397d6b9e3b80e3d2c4a2ea2223612be48a275c830aeab90b8aa9b875fd537"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+1/LLVM_full.v10.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
