[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "665581698370a278fc925fa6da8bb93141b39b28"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c3652b3353dcc47eb94b376dc1c03e37bb62a07ce6f19a8bcf53cf9ac5248a37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37d0776e9d3fe13f7f6d76a0d539ca611634031e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b72396567fb87f29648e71808ce31f02b042a6d58561ce2fa3935733b04edd5a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19e0887b7f728884cd73a1fdf64d0166db1838d0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5153e025c4a5febc105329964f1964cfc51d50f0a48de34a71b35a273947d8a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20eb29980e5c475a38f2f41c8ef191af916e5492"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c0e94a4fca65c9209107fcc4fb617a6a6aab256918691a0a784cf45a24a20df2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a406dc5a4267d306563f37683478770d6789df18"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d286ab5e129c8fd4e2907850172471a89d16c41768b86413c35a8cd6f7bdc0d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f224a84b1ddf967048b213c4887309f349c7f06c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "581f4d01df6879228e966b2558b8961d2ffdb98ea5c1d9f9fd3e4f9f0c4d4f31"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1d305421dfc7dc647f601e8d72a9eb5290911e2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "16d4a7f8b3b30cfdec465b271e342be5360f87b6b9a68904833208deac5e85b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8cef6f0b60730a44f99c760562a81c76f59aabe"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c65e03eed2b0e4a4c9822fc254c6301ffecf1cb3874a9ccb704133b940961220"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbbd924fd0a35950c76fb4fdf8943f86f603826b"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "6ca775919785ffe6eda008f13902de26c9d0738aafe7b27f77c2bcc806a2cb42"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0c810fab71e5d9438b50d22b83d6969cd16a86b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "91fda443d5494748497edc7d2c81f8cf47e0d0b760548574bfe98e139eb572b5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8e97e1912642c9108804c0739f79e9d6b977e00"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "95f61cb141c3d8ba6cc3cd077567cf6277ca3ddbc14d8c03627d21a3c42c9aca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1052aa9d46a0d8a8ef0eaac21bcaa8f081b94c76"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1f7ea0a51ec6759e7f024ae3449140f706a0d71cacea2640aaf8eeecf269eac7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3867ed96bce490ee42b6b1a2b0a3ec9ce0f5fa65"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "366728faaccdb858f27ce99c139c609cb022d892f2d981d6938362021dd63589"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebd017ea36256abab523599a3609997826e6a843"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "01051de0ff03d0d97ed7b27d3e2069c5c8316e7b546b2f67831c87f4e1607255"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92938f91ca492abf2335d358364d131ae907cf69"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2cd9e35dd982e7d9cabef9c25c2ba23e61ba952fdc4b01adf3dd4ed6b29216c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06b0770a2d4ba46db25c6105f24c63beaf517378"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "3d6eb9b5079f87f6bc58f13fdcd98223d61c120275ee321b504b146fb52d56b4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "242f05b0ba02a0025c1f15c6cca7c6c459733547"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "85402c206fe902a62d8fac9975da4030489983f5da6427b1c74a6ef6431793c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfe8008c9cfddc76f31f7a58d52dec121119f462"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6bbfcd89a2ccf5c5a516ea251a0b3b8f4fc540b4d11ff73bbbdd13709eefaefa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c0f05bd7c84d89f6b386ea3b95d95ff3e2a9307"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3c1662a381f064c5fcbd529e09f4d8517359a720f23761cc6c8e8cf36b80390c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "177117b99cf2a500143c9e5da943f8cd46e7d8aa"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "658c5a253169a5b8ff6ecd19c13253b3718aab86386e0d5547a1b4df8b2e51d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e992a075763aa10026e7c4183b8560eba8e9fc9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "35e4e7392d11d2d06669366faa7ccf94e199a0df6d33c2dfe1c5e7bce205ebc7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d625bb0a9f1c28e5dbdcaf31fc42da5be481a0a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ddcdeba5923a42dabd1ca140a8d18c03afb3ef9c7183c93f58400594badcfce3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4f594808549d46c50bb258d4b66526ad91f44c3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2f239bb13c43abe05968cf6039227019ad17987898f9c52464367d1ab7b9e8d3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e918e0015ab618beaa06764ef891d39ad37221f1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4e6edc7ec7d766bf33065dd2d761e7890eb9acc2fa6dc7a9eaa560f38ae0132c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc34eb8b8cc73336a9237477615b1bddad0c4abe"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "0413b979b88377e4d36ab70ceda20a5ed6f3bae74187313f87a053249339a6ef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3cb0cd9848a49fa3e590ceeab12d5b9d9a2b4c0f"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fa471b5df962d5e53560f4468ee88eaf3b8c1c1082ad06d9bd06bc4237fd7e1d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+6/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
