[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "3c5d03995d43986d44b4edf0e0a8dc03f99a3210"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "f550de389157e5d928fb542b25a5954d58ce63cbf0b2d483dd8a4b6296f29efd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a7535ec102d3cf0e2764efec55d26cf8612a6dd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b5a076367c6a25b3eab0206c02b7a07753f608f8878f05851ae07e6d86656443"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d86b6e9f605bde648d84430b84ce4f0be384a6e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e775f102496cdc6684bf59c4f285803e7b3f465773083b0433a9be8e3083d98b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cc4ef63a297136cec5943daf197ea6a07a18465"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d97c20df43f6d29155bb71e24855fd3b743e5b3de9f613c0f54161407b72fe48"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78f4b3575c57a53e212023209871025e2f1b87f3"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "94e6e9c6b9cc2142268c85e7d953c164b3e819a9aec649c60fac5f73b4dd9216"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adad9a6a6b6fbfc8929021267e85f8e4e4fbfd5a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a24d64643d0a6a466cf0cc67bdd0dcffd52e0488e13b3ca0403a36a81df82aa4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35366b2ba6ed7c72e73cf7ab104b7ace52e5e4d3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8234d787ba7608e5988b337653886cb94a08749d862ab56dcce4c9e7c7c2f608"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b7c26b9c9567256eabbf4982bc98ecd68dd9bb9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a3095e086893a1dac171a4bbc7f381ecdaba0dd60011e64811113e0164841ab3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b8bdfbb3aa84284cbc7ad7563b6cf061acf2103"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ab122dce9b49698f1b28d5d3beb0c15e9c7ebc60973649b78697eee89078d14"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e8c1b6106746682c50b87952f3eb75d82d95c74"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "01ff7a4ae8a798ee537fc371b7177f3500d50338905e64225f0c7d7e503da675"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f09871c2a49535e3294c31f00f2d8a9e2f0f7770"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "85d262d44a66c4123a8afc2ad16708aa9a0bc32628a3a671931b7d9bff682d7b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06dd347e61aa5ac789f59ee728b415723471dff5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0e7c4e632a2df976c039599ad045eac91d1c136733fda4ac6a44014227460607"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7489482e3c45500f0589b2406dd67453cbc1a03d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "323e6326681d3781d29d1f64c66a2336f784f710b38e14c3f9ce20d05defe560"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1232c92923f97df0e9eea34d7c1c44a52e05784a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0c2b5a6ae7163978cb78bc591256cf707adacb4d6435ab02ad82d14f679c3894"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb716adfe48fe35e4ee54b1422d90813ca8caee8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "61f452a6d6c614bfd1171fa95389d3ff18e6b5a86cf35945f2433eaccfa3d394"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff466df3296967217af6897430f45bff28cb2cae"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9abd845faf835719bdba110709d6a15f500edbd09f3ff8c6642814a00056e59f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e846010d06bcc33eab6376cc605e9d9888237c09"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "497ec4343680ab1a94e6f0f57a9a34ee425d3aa90fbc31cb51d929733e1a31f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4089a81131398cdd2eec63cfd8ed7876fc5a750c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c777ed413c4fbf7c3dda1b5261626af763d50d481e803ca4f015e9a0dee90645"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bae6a89ebedd51fb81b1ac76c33d81225876e445"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f057af68461fe09364b5f96b458ca54e15d052a10b2b05d11538bcb74e6dbbc8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58e6dd6d45c9d1f2980d5e0b475c7d319294932e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a8ebbeaa2fccea7fc63bfc2db4112de2aae189d5f704dc3730e99e65883b2751"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ad1c28a329fa501b4f3ba9dcdccc71acefd6866"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ab47d67057d14fa8f8468c089f1a1ad1eb15eece228c51c0f02247a0bb9dc380"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "18b81a60b85950833949b7e2e80edb7e41841a3d"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b98195980f67c5a187912aef42960924ae11d9fb5feda1e09227f284f2d16440"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3b647a76034fe2f9dadae4391bf1aad6bd42145"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8ea0cb302549ffdfde3bcd323273bba6de51e67547de2193f806fd3d66a5526c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddd56b8e61d277889ffc1097df9f1da99e875300"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e24282375ae59e031ee24f2fb227f4c3b9232ae291265dfe6de18aafb96e3c18"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e63b5bfe77a032144b291006d2a0ac0d44e626a8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "13ac99d6562a32dcce717d1a321daa66fc8e16788f470a0715cdad9e3f3730cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef3cf2679dabd0bc67cb97cd44893c36dfec03d2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5fee8378ff8902bdb7f82e91bc798aae97426c8aaab1ec7714201bd236cc1d26"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "292e3d2868ab41239d45f05c2b2e26cadbb8a97c"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "2b95594b845253d377a60906ed91b5945135f677424b6d0b07206349ac9e6b24"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "790c4afb5257ff7e181b9c5843a4fcfa464e8e92"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "cd211d6ebb548c1ee4146703bb7b61a1e8a08f535b30613599a1873ece79d244"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "981e9af27176ba5ae915c79b38cd555b50c0df89"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "64fd7cb5aef2c4d40cea1cb4930c3ce53171005992de5b59631c6a1388eb819d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v13.0.1+1/LLVM_full.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
