[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "449538f2c0076976db9b3f5f18cd4e90ace62390"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d879f031e93415d999e312bccd5fa92a97085060185570b5514a06b41268453c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76504ecc61c309dfc2d224dafaa7d8c93d09c979"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "91c0ac7601d4edb2efbd374cff1b5e4f5ad5fd92df9f480addb1404f1e28b6d3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db6c0d0a64750f8093919a6e74ecabd9f836d598"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3a324f8e0913eaa5f394fa88d5b07de2864a944b4d592145ed8077e05a2bd64d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8bcaf303007dcb03ed3d11891bc2cb64567eb054"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0490a8084bb6ae5cefbca453bd926c81e1573ba99e9aa93e8900eedbb62cdeb1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ad640b123c3e81f630680e26bd3b0e78408fd33"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ea0a69907f250bcdf825b18fb3c0371a30df79454436f16c78b4c9ad30e876af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10cd1dd4ce85ddd69efcaa697efd9a8a548bd9b2"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8fed0bdbc93383a9451f3c566bb4faed8a2fdd3b2406c225d4f0aa0712127bbb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdbd14fa0e1e4982f2f86a980ac4051ce5f43333"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "752bf1b47830c456cae8b98f01a77df3c393e44e59c9849888c285580cb9a2c4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ecf90cfd06361fafc5c9d1b333af8ed9c31b8a6"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7c90529de3f3680afe51fba03ff4d76616d62b5bc24ef8db1fdba2adfd37188b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92a923f59dde2adb0cff670153d8699422bbdc7c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5f4dbf29eed14ab0978c17f2f92977132f5e920836b3ec8f8af6f45826368117"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e250456cf3c4b6c7dfb065012114061d4ed769df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "134e1255f6ba2c92a5181624cfcc39aa43f2367f3a146a544930f13e8a6807d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5e81a5b9caf8779a538ad8ee12c8e275eeb6d01"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "824017e35daf8fcd0fb83e42b6462931b98163dce39dbd557347de17f0918792"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c88c13dfd6d7730f8123be1d69794285ad20487"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3f9207ffd3376b56a554d64fbaebf508552d4ef845749097a42580cb3a85e9d4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9301313d54d3534e2075ad817c6f478c9513998"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "99026654449d782612bd9130769a02c05d8a5a13ec76d507901b89ae997e30c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14bc62033d900a8009acb0090634eabb5498ac03"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "049be6e33df038e0d59711efbd20a1869fbb138a8abbde124ab4c513f7a277b2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21f604c5046de9a4ad9fbc7a9e6baa7290aae5f1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5ac35ba6dbe4c50ad0bf72f2bba36e5d8e8e5e64963cdb866df89d3e7e590cff"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd056c4a0b507b13d173e560df1ff7c9b687bef7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "38b90cbec2b2ed5afdca65242ddec98f3b1fcdf51edb22d9a634435d7e4a8e8f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2aafca28a6ba4e778b58b8a71fe4ea115f8c7969"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4b7870e3e99789b44cef190f4f9cacce9e76c857ab16a51f43e10036b06386f0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54216b7e5b675bc32e77da68edb39893727d8b61"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6751def827743080b7d1385f481781f57099b218928bb830d5d43213ce62edfc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d4036219defd77507cfd02aad7984bb3fdd9ca5"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "c9a642a2c7f358f897519274a93d42f5fc45f20f75f0214c0bfce0126ae833a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12d0681642fc52aa3f158f6d7d48f7db2009de6d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0e71ff674d486744bfc5216f12d1583401b3e38b043f391f2585c14a5244d854"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e97d0762cd1e5a8ea6026606ce3714c0f86cf424"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "db106c26de4ecdefd45de6fac2687220a033390989fc67e0bdbc3a0540d94cac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "a36f8e1a1b6676f7315763c4069a38b59b11a7bd"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "c53419f757cf8674227050726b32f680e2978dddb5b94328d15ad35aa7f4af93"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19bb3e4b75de782ba3f8e34cb7c5a8e2683d5c90"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4a949176cc68e7e60b6bc2a1183615cfd3c4f3e82529845661490291efe32378"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eafd2f7b0d85ea350e08b2256f27369aac85aa18"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7f763cf30581f66e57d5c0ddf0e1a5ef4d265eb2c42141319728db528e424448"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "738b326d057ca2cb60c247cd8e8463323b733fab"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c8300ba9e7fdde25e144b3f2a9596624a343a4322a301e39bbc84d120270794c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4803d018dad2a278e03c10017b6a90aa4edc59eb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ec2e4f8581400f76d090e039c462703bc7f91fc3e94fe40c2f6f157129d7fe3d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "6fb0e15eca7c3072eb392f890869423de08c8ab0"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "caf6b5b1472d0f9588e3e16b4d9642c4663356c1458cfe0d229554926f8e3e1a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7405ebf6c3694bd1de2d2d05f4a1789181c69303"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "65396865212e3ae39cadf3bd73ce40bf8bab159c706b7fcb72ca528272d32581"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e801f2aed6af40214148464b7c4deaa3ee1250e3"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b0ac43a46d634f58aebfcb4ed16e03548c616ed1f933c4815f669925bc18ce7c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.2+0/LLVM_full.v14.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
