[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "9fb82ef4179eb6fcac1bba6afa78eb5d3044c2f6"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "124190762d1c258fcf40f3a781c0249ce4e4a120ed751fe20ca02a00bf5076a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76803b2411698fa40753c33305b10fc47e95fd21"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1e5a907bd2d981326d142929c8c0afb9129861d3aa4df41f15b165cea6fed5c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "181cdfc7c319bc3f9cc0ab4ef0ea62b491373b59"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "923c733828b8321340f2f7627185f1bec89433073328ef67ee1d2a1158c65fe4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0beed4d8e348a22f36f8d850a6ed01566fed473"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6b3839be2c5f5e905068273f6bb991874f8df0d33a7fa17ed226169852172af0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6033a5fb4058e1fe865cfc858d7ee47aa150a283"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4ec2e175ac09b0192313b39e82c3404e1196812b6c129fa8c46e84ebb17df425"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8a693a3c3a3ba2ef94243309630be144fc90228"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3da123de3c8cbac593064b5a5724c965d129fd9c414d7b600c1a250351089f7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd81f3755be1f592502a0dc06725d82d600cd1f4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d5c5527aa4a643bf41c0b70a70b59e0db06ec9a6795e442a1110c9673cba4b70"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cc700de22f8b90cde88e0c7d0cd9332dcc6c589"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "296823c1e05dd33aa64b1499730febad6e313078b423143bac7a29bb64eb5131"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "714c702c154a18ca2db306e51042708caed52347"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "37b75a0a125f53d7f4f18a0d6489211642e01bb5015640e14048628834aa9393"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "317e1a754b2b95c42ad8c517182e4a699a32c3f0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "53a3563508325931648498839c87e7c33543c7274ffbc27bd03e940d09566c4d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7904a2c8f030dcad63d4db53e067a9c0dfb645aa"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1246048764eae64a45b3ada2389e1bda1f56e7b3a0a815a2673fa68ecf1d4cfc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "397180bcaec901d598066c445d9a1a0812951c3d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5f865b5693c22fedcc92e81134072204e66d411bd2e737d1e3f0b7c22484c7d6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e191dca4165541def61e2e629868df048627cf7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d4b9045a36099f8aedf631648f969828ddede1dc30dfd0f05f3139a13d21fa74"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ab19effef7af70f3b82906c06b3aca49b2b5090"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "97ebdabeed1b34a39d621835d9f5ea11841ac6e52a054941af59e5c9cdeefccc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f7d9db5b3c00042c2aec1e0dd5b966c6dea6b54"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e8be59f0a6514c15af875b2a6df77b63bfcbc335fd48a773db4569d2ba3c1979"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b0fd96c89001247b9709bf0e788e75b1a6fdad0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2626af5e9a3b02955a9eba25f77b31877130e6328d93f6e961e77646a273ed45"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a52cf507e7833dcb38b58448ed6ca5a1d4cfe49"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "58bea5da367784bebffb0cf1db633d744f32bb99d60fcffa0beb5465c01c82ab"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f67e4afbd65c1ba5af174e2c3f759a8813db91d9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3b5c15d5db2a0acc1ea509c19f88d7dbc6d4976ec9c3eb7c42e4bf6fdaa8b83b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67e1257e2d052eb91d8e40a8e13cc1c7241539c2"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "f31654c36bc1701ffa749fb673617f79c788171adbfcaa85889b1b94e9ec8f7e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e4dc4c11cad20d04a151a7b11974eee465d0e0d"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "441d54ba3583d7a3e0d888d55c950bb0cdc1483d4df1b818592367b3dc09182f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49f66b6795118ca812aaf5604b66de742ad497b7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b69c8dc8affb652319679be0d5aef74d026ab8226023e27908e166dba6ccf13b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "299ede4ddd8935346dd13abe4887729b98958c67"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "a3daa5ea3f9ea9c7e4a415988100d256860e6d254aa7c239419274c058be7076"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00a6cb1aae2f15094a9032f5a7a48572a110af4e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f9636d7671e5c9b09cbb532271c4cff7a39e9a7673c5ccdf52517971ec47d32a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c90711842814121dacf839a59bca4c40f573cbff"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "29d30c0e4472e4c356156694ea7a25945ceb26278f6a4c20f8000c9a91652bf0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f28b01818a19b139d6bb0dcaccc50f959090d47"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a366ac448ab24c37c5f6cf9ca462ba13e247e55e99eb6eb84ea3f5617025d2b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a400df0ae9ac5bf495cddaa215be64b44605e54e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "25c1c1255bb50e277a8d064f7adff7fab38c2dc3af6a946fe51c6062c8238a10"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c2edb0a28993c9376dd067d0c1e8f33f50a6d6e6"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "5f6fea319bfad668bef7169abf5d9dea99e21b174f5602623cdc08a78af3e20a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a360d3656bc215ebf301f2cb1588574d8c89dea6"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3472b2c13027483f550bec145b4d80e1bd7f241fb42ba867f9d8dff41df5a96c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3adf27f62f84649d62acb9a9e925fd14bfd9a4f9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "075eec7085099c314be0ab9dff7f07ad835c4cf7e1e1a6d4488616fe095ff4ea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v14.0.6+4/LLVM_full.v14.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
