[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8de8d019d03acec230cad8c4f82d62c5a5e42f5c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "dd32203ec325f47130eb8653f293328aa0ffa0a03684085002310c58883027eb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e681e4790476cedf9c89b9cb5775c93fa59fa88b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "c95c59a895f0ee35124fc986698235262e0fdbf3607de8627518c98eca77ef7f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "482c29b6646438cc5d6aa43e18efc42bce4d4003"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bea66258c0d42f99fb1ffca7b91befc7363080321815a76bd4ab9a896bb5da10"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0277d93872d67eeedcd9f3d5a9ce26db8ba83fa7"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "d4a187cebf0e0a2813b09f77a5afb099b975257872a48182a434f3efd2c72260"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e524974691a828f6950b327b953d702ae1a45351"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b66d1ae8244e738a7b5eaeac6220cd1ec785d1c082ecb6b6ec406889cf982db4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae6ea984b4995c42bc67c9aa28f2c6ccd26f92ea"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "372ddeaf40403000e234758deec14b94ee388abf6dde2dd744391c7f87f9cb5b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "978e8b8a44626bcaf8f5b92a336f990d438d96a3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d6e5f1fde009d775cf2b4919dd1206e4bb5dd8b2ce650201388bc7a8bda7e3b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b4ebacea6d3fad6d496e1e9d682547923bccbfc"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "23705d7be47ddba08498301b051ebdd75e5549e3fa098fd26126e228209df4f9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e757aa64adf4b90df6462995f5bb28513980d4dc"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "d07d5958f5591a528c51e236b2468385e4f272e107f969a35098c62482f0ca8a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0e1db1b0d11ed3181f17b565dbd1c4fe5aeff98"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "39eed8b3c7ceb83f232aa04c8adf7a2f0d6598ac5320c3bb0c154844d5227da4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70b880416480529bafc7149b1eeaa2a26fb8e969"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "8f09cf3aa14e4e0af286f9deb10985158783c5b08699e451c963dab119b73b44"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2b182c590fd7f73de027b6fdbbff1fb59b3542f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "09da268021f38eced0febe58c51bf71da28374f6078a37987de748ac2a299a66"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f52cbafcdae5063ae469f220747e3b07fb0f0095"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3fd2d1760b75e8a39b4a85d3e7f40fc0760f625e7bf5571fb0357cd5833f4947"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8db4a264419fdfc7fe50aea5b0f35b667369180b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6cef28338f31ee3ee7033a7b5df513f12ea1c9151559169de5a4aaa00c4d152a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b3a1fdaf818679ea69e1f17910acbf6be9a0f64"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f4af0521775e17c09fe0e4a264611a6a8d0a3db00cff5086847e3cc2ffc3c964"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fbaf58f21e593ee974fb533dfb312d99c9c6d62"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "353840ca1421d382c9f35b754a80323bc72c0ace20da91a467f4c2dea794e7af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1a50c14e92f6d689fa32672815f8e031e7f5a9"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "3d0949f31d051c272f8e4b6bf2d197fd201cd3aee6966917ad43f7a816c651f3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d583a85599ae92504d3e15e97c794f1ad3c798ee"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3997c02c7967981f76901eb753efa486722b6574d7efa9102e498213a0d6e326"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "356cb020f328f920680475d827328d29fb0758bf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "04aaed939da48c0f180ac0d653155df59d16b59653e7d6dd084daa43424ca9a1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bbc82ddd339a992668cc0920dd9cd341c515e1c"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "5fde86654e1dce11b20fdb96fcba601e9215016be85c2c813f597adf4a5d6fb4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d09d43019c5c4ca0949a6a1f7308413951e6ea2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9ec9c20b8dc0491f60e67e8b2e49d804c9c923099da63ef96f48cd260507a2ba"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "962f8d64819382ce800e8995cd9be9033fd47f0a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "599b45655948e55c62db7792d90b8c8a0d20d2bfea74ec448f9a800cf6de0397"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35568c50dbe850f980db6b7cb778312b6df5acfd"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2031e9e50b546058b17ba837c0d0b6a89db608e8e2969252d47c4d114946ec1b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d92806f7290b9aa4712792ddf55c9e47ca06a4a0"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4ce3dbdeaf94014bea4ed8ce9b6fbb88f9772720192ae6d39a816fb856a34141"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d03990660ff5f9cf65b905b42c78b86156898c15"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "3d17bd40c00246d5c9131f5cdeb40f3466dd25efcfd5fd9caa7ad1c7234f5961"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11c6f19dfff17c72a9a0b5dca0090649ade44939"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "403374c9781fe6c89cdfe51d7a52f1958428d265123a61fdacdd88d2a9bbc2df"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+3/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
