[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96b5b09e1529df14597e91b30437e6431851ebdb"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "54d460ef15bff0f17ea06486c6bc541f1cd5460fd03cb713e558f393cac653bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b989374ed3a13d6892414efa125bb179b5e3b16e"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "254aad698caa0c65c4e7e35714e16fda9a92ebe83e7444fbda532aac9a4537ce"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8b7321fb2b81c6f510a45059496b9c85d05d3c5"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0f22042c95b54184c1ecba04b30ecbcc1a9b1d9bf4f7b09c716534dec1054a89"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea8114b13c9588323dfd72ddde8baf85ca37ae8d"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "38ec8b9e13144dd4cfdb9e687e6fd8254e3bb500843714e823388f65c4503bad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6804288c89f254005b97d2a5337030114d8cd0b7"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4c3c52d7b6f2fcaa58c4392f30654aa3574feebe2ad8784051de8115b64d53cd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8780a60e3e4bdda199b4fb633096bfb129745b9"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "989eda527f75579dcb3cb727fc046187bc274b12cd051f8b10485a605c42db6a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c018b134e4e27cd93bbd31cd1bbf5856d5be92b6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0dc8de53349afe91f0d033e43b8af30d11cd8f3febfb1abc104888d8fa22d5e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccd4fc1ce31380e912836041d415d241e95ff048"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "65318391786b79cdc0ca1cb00d598cedbdb49200ad3802a852e0ce9ef86d633f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f0fb60709c8a07bf9ca3ce758a281c255502756"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "eeaad7a47b886a87017956eedc14963efa85f0e7e11ea48cdaeb1b055bd13684"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "079518d85491b7cd79fcb7b425a758a1a816c8a7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ab8cef3bde26b398b9604d4dffeaf51e6e966a88ae01a6545d5b55e4204b1d80"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9ac523686976885e5bfde3ffd59ec3ed08f7383"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6b726099c8d9d54fed2aed207b9f25d80a2dc8eff7338128b5a892d379fd7f0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba1efa7ac63be14974295890ff6bc80cb829ade"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "47bf36b05c3183ed27b2b94d887c6489800a6350f869ae4e9a681d64917f7168"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6800095ee1e3c221e463d09f282b6a42ca21df8a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "294c811d61fac0bd54ce73c411c737d089f63bcffa18dbbb572cc97be4bf7305"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cfd7493229137bf075446daa2a73889d381f347"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a3dbd53b20b4c12e30ba4ac286d9c3939c0e754c4993ebcef23da4112b489867"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "175158ca5dcd024456ee3db591e448ea1e92b560"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7dc04adf1e067fd6a11f6345debb4c94ef19d5e6f9a7879ed6f5d5b6640c6704"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad116bb40298ec5e91ecefb6964afb617ba44a80"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "4d74e0654e614c847bdd9ce64d40adbd4bb214c15b90923b6929471f67705128"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "136dfa488871c069a450901091aa97a114a8c3e8"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "3a28aff48916ad17090cf808741b7efcad275ea3ef6e36f99f53408de140d985"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f13fe120837890fe7cc0b58cbfc5ecd67792cdad"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2adf612aa251fabf4e16d89773e597b617e278bdc9fc8efc87bef1be78fd4266"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40cb8aa14b6b30b13c7230cd7b31e385ff10af54"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "cfc0eb6c80f5b8c4652a7f429790a5395afe3a6d0133e36302ddeab244598f87"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "415e5ce1cb1387af35d1fc1aab4e18e2785709e8"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "3e78b7c04376b24cb334ce172a75df778b5c544419ec1d65da3c7d7ff6156bfd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82b43786d8a24170ddbe98dc75a6e45b680b2465"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "aabde6d3587dcfa23c3b27bac30a380acf041380039917b7891116a8d654d21c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be637d738412446f5b868750ab3f253a5f634b3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "b94598d23d1b7e764974af2c14893db141993779f83670e9b2313a7b70fee459"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "436b8f499dd7ab027c23f2db9771a2ace041f551"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "73788fe0a644070b8ef1d22b544c32f1b9b01edf51e728aea3dfce39e6f84056"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70ed7bc60976a29fcb38d5ffc9554847ee1298b3"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4a2ddac05aa94082f6738b0b120f7df94ef6bb4e7652a88a184f66e5ba619e59"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0225fadd2e80114a13a2597a9883cd44c1041987"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "2563bddb92ec105802af096187d654c34131cf254ee49db53f20b6d3a75966ee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fb520f3aed60a99ac2b44f3bcfa1b9843dba7da"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2d80a751f3614246231a39293d09916a0cc9a0c1ff502fa92db62330056e09b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v9.0.1+4/LLVM_full.v9.0.1.i686-linux-musl-cxx03.tar.gz"
