[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e2f25666b498f8edc077d6609ceaf19501b1c18"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d9feae6f680cc7939e842246661bb314310e19907c9fb0479e2e30f5114abcc7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba32dd8b7fc39ea3536c6fa8cc4ab50695666f92"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ea31038912a0895b936370ce745bd414ec01b49833dfeeaa56dd11ff11934407"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d34442fe1650a66bf137e852c9fc136010d50bc6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "4918c5b8ab66a6cf8294bf4c40497308d26f3fee87e11598c666263ff9620af8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e0f578619166f3fa86c9f60953df10f23359c98"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "3d5da47e1d044d8e6c46f1127598aa5080ed62b5fd3b0a4c7bbfa20136b876dc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96cf4fae950510cdfa5dfb4426eee3e31eae49fe"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "bfa98ae7ce14c7fe46f85be40477d86fde78aab20b85bf3bd72f568615c9fae3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d3a1e162cb10575c5fc2bbf29d89e2d92efc9b0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e42da9b51ee43397dbd96d2cf00ec1c2b40332e33b99375db8b20b59d35072db"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9af73c349072df00cdd89c17567a4ccb82904f9"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "da36922e53fe4fa95a5081c23e8bea3f3780596b55176fa6f9f12ffe5e872919"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9eefecbbeb6156afd2eebc70a61a714111f4f333"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "f2dbfe21f4ec282d5792602e70e0d3220fb038b4d87abcbc673b748dc977488b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "093ff2a870142cd35bb663bff13aa15b7c0de88a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "21093b5425e2186cc4ce04caed8067c9621d8b03fb485ff50d379f4f799bf653"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32b3e1f3e2f0b11f5b4474e89c335a19117e1d2f"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "b8b55d7fa1f933a3b02aae8d047fd1e7abfbf2a905056b8eae2e511fbc344928"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c23a3bc213e604c2de0721faf2a3a17bd342390"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5dce93c4f1cd7807186c0a1f5241a5b609a269251529746b42efb59e94cd20d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "462e99ef7da5efc25aca73a823c8cb421c685d61"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e0263c6d2f79194306e35552da5ef1dfe468a88b9b31e6b97222c76095a2122a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cd56e3e81e5770720c31304026f3b23f129153e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fbc5f6454af47502da0c5b5f9a1b0f653b0e2175e28d5d78b707585e68b34701"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26e9f422b7c0cad1c623d6ef38cef3ae43f90fc8"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "6797ce7ef312664d63d0e6e2bd33d89c944826592983a0914e06d8eb78b6fd71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39c1cc30e5217c3f48b7dfbfd3b10170c410184d"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fa3ea7e7ca58d4d68b43525c4c5106aef2bda550b7afd57ba522434b47140e7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52746418122086910be0d29be673a6d107008ae1"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fd0f3846a2054f58ca545b3b2bcd90bbd5b6ea1b88e2784010a9a9447b8828c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1df8773d18359c5ccb3913c9b1bf5901099832ef"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "253f7003a9527a1d1fcf133b71e14b036b54327389eda3ee9368f4f5adc97406"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3d86394f1efc620d1c1b65a5e35e509f22f116a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "1cd9efaeacc3d1b2afbe7d6195a7fd2b38429dfc359c8bb7badd53c5598bb12d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a3783506230f2d4bfc30728a3cc7c9e15e0fff2"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "78ea1fe8dffb612e335bd9b16b83ec8039579e27e981104f7ee09a80f3431e83"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d5588b3f94ec6df234ffb96258026c56b1ce65e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "b453dafcaf1b2d5d3006071b2e825e1421c7eebcffce38305bcd6d72ffb229b5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9ec0f85168c57131edb461ec095a01c5047d14b"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "58970d9da0c13db987163cdd300103eb25191bf708f7a3052774d5755bd1b8e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "012dbb28d2d1a53782449c2521ba619c21818daa"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5498b8a10667fd9f5bc27cc775df8c3c8e6d2e4f461e9cda1f22c312f01d51da"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bc5dea5e3ff3ea269897e1d9f42506b5380ba0b"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "36cdd2f75b76ef6989eb037eae718a8d1e7be48a2329f09c2a4b8427a00c2115"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a97d56919feee44753f9ac168aa9fb617725c6b"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "e270d1aa026f36054b42f25ce0f6943c92b3b8c89473015328ca53ecd8752668"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c24a8acef005cc8c6d8e5d1c1ff5542b966ba210"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "64e6b364427270ef1211eea8038a38fc1986c8c5018a4c3c42dd55650dff9182"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a74a9e5bae50bbb1b0e7525c62c5e34a37a32a6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "a36c00a76126434789470eb8859bbb4e23b070cbc7a63a55d30330b8c9e19820"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.0+0/LLVM_full.v10.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
