[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ac8e7a599a7bb3d2dcf5e20d7e702283666bcd6"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "85d7e68e79c0469e748001528c90a853c8f66da497511c82087153230fe8d536"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4193d64f840c4bfa80d9fcf8a8df9f8fa07fd9f8"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "734446effaeefd6d3917801325a4c631f2c8842fc4c0fc09be6fac8b3ef59df6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0586ef4cf4c9e9a93bb83f7b027c429c88045abf"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6891822f3f489c9fc93e27aa406de1bf97181eb0ec30f08c9f0bfdb47aab258a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7671f754eea5a6d52fb3de28d8b119b6dbffaaf8"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "33f317102cd420755bfa4a4037a08093c416de9a75933eca210369eaa7d84029"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b30cbade014a5dca278c8c2acd8546a1f19cf06"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "fd54a3f940884999d6206f70090e205350e390b69f499e407409afee278109f8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd3fcccdf05bbf5b741d559b0708b6cbe939256f"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "820cc07bde8045ad7f14fca88fe4073fa60289bc7ca47da5ff99327192e85345"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1a455fa2e79c2df148cda4680288809181a807c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "190af42f49599406dd1676bb7ec9fdcadc9a20eb7e490caa255e738f220e903f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e692a430d2288f85449e89a0b9b237dbc51ee55"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "64bcfdb26322ce09a45b0de4beab8034ae3cee8565883bdd0dba1f01d4b2c7aa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc2b60764ab00eb62a0416441b329440f88bd3df"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d91644d635c2f015b19799793c15190f7506398ff036a8c4b0321f614a94f55b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00ed0de9769f151780476d9f7ce948b1ba5e7b2a"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "2bd7abbb3c208be69447a61d486baa7a1033397453b97e7fa3672f161e7c43f2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9453593e44b3cc9a82537ea27a96753d61755e6a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "8ce85f787faa83b3c07da0df5d0a3f2918d988b49fe94531effcc12e9310a074"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9be56d5b339850861eb09f34828c8812f8f8c745"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "af1bb65e058b13d2731b5bf1d21c57428c371fee1b4b4560c314af394f67d348"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24c4c049a63125c5b19f436b277040e9d1c5fdba"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "03d0a670791b8c4ef97f5ccc4f6e8ab80266e25443297b9581105221aed5b3e3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4370d368ba60ff6e23a2a48d84c495ddeb10aaa4"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "48a63babc9f9f4983b77168af03884c733c357f57f98e9ea6752f8ec91000659"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d63d5efcd8014affcbba5af3bfff0c2eeb40b33"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "5431b730077ad8ee7aaa6755774b10280d4e94f23e6d577becce5e486267546f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2648a7d034c600c10946c75e17a0f4299efcc945"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d629d9f70dd8e5c6c05701e32a798abb93a34a346d5b36020cb3853b0da85093"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ccfa0ba2914c5863609538d82722536b18fac70"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "c8e99643d88e4b64d3aa4022e25534d7d5d493f292e0edb17bae2cc79b8e28cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22df352df17ddfd87f3ec4539fdca7e226f2d7bf"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "55f8344aec0273941eac0fb593972307576402d1be5aac3293d40089b7c3c95b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9ad6e236858a06b6a1e0122d141f33080f9ae42"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "d24bc6efafe904879791a50378e9346ce241d5dadba113e34e0c5a29010d139f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb0ca6eabc2792d41676e918aff17b8aa8b7ad0c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "461fa2baf8e0e0df3da0c46a908947f3c94ab49584a30e968759bc037d4e633e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff190de98441b3951533d1a41969cc1f77527a9b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0513ecaa9feb9af75c9bcfb7ccbe93efdfb9846793d3eb7428bd3d6a6ba38f36"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "589abbc2708dfb184f6b34aea167faed17cbcf03"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "65fe57f0eec23562a812679849748494481c5297a4c6d14d2c1e477c2e295bc8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1303e9c56c4c6b4159506b9d10d61d2acdc52004"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "fcf3a8179e2155524dd90059a363b75eeaed5e38ae227b868282d7557fb49283"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6df593170d9365b152eb980fe3b9f3886f6aef0c"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "d8a880ac41e0a8832b7291440a6a9a4ea327b78f4074efdd9fe1432b75340ba9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83fd11bf90fb5d5d30258cd76f61c751ce89a349"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "6928cb2ad922f869ce6bd6de89cd45d9cc1726b107665e8d4d348cca344d9f26"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "796fdcecef617c210aa28d1c1f291a9c1eaa6998"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "bf4ad9dc5557bc2c13713323f88f6a595aed83fd05dfeca86388afd3a76d2631"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v10.0.1+2/LLVM_full.v10.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
