[[LLVM_full]]
arch = "aarch64"
git-tree-sha1 = "e366f56278c9df73c89ea0cd95440d20f7300443"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "c89a88a2d12bafbc6fe5ccf3d2484bdd35522931477be072dcb7953a9ae4894f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbdb106889e9c42d349260122dea3c28a13be063"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "60469988d10a03b381fd0953c3889fad70a3db86ef9330be08d5b363909e30af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c3c98d14414ab9cc469539217aaa43c4428d72e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "08473e61bf75aaff7c354aa7a6e2958f85c4c0065ce65587903d2d2312028a81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "affff80d6b430d5b0a49a7d8eef4a389e7653a17"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "463d3e87e471d8bfe3dca481faa9d95f190224f0302a5be0f12e2f89617376cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d42f6c7d02e2087ec21230c34edaede904579214"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "9bffd2c30cfbc4e7a091639b30eb157f633772df521df7b320adc79f794d99a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "405a3da9e1d1e90fc0fba965778ff30aa7eeeed7"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "74e955c66f012063f4298e932a16ac04446369fdfabf9c88e4534abd52ee2a43"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c86fe2e937baee9004c2f75aeacaf7030f7c72e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "978dc32247f472a59f6a693fbc3af46bb5e59d043917ec1dc61f3cbdcc15683d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef0698c807ecc6b6cf8fe32ab2534329373af83c"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7117240feae955a2b792efc17ecbe091298d7f30bfca6ca7c7b91a0b51bca0f3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c3c7578cda9b6029ef9bbc1e2d1c09fa1dd2124"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ea96df2f692b4dc2e824f50666f9178beaea90c99daaadb972992e2f90d608a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "410fc396e85a9a75edbc66b9714e203622f86d12"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "ae0ba3c2a54fe77004b2067188078cfa4010e1329df0255946c11760ae40f6c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f2b702ccae87b24f39cd8f18e09dbc17320ae6e"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "95a524ebfbc217cf1be99dd1a0618a1f0b3d68e795a6865452063f00431ff2ea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7052650a67f7bd5d1614755aea09c1994e3dbf0b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "36cfef3c3dda23e3793d1f00f86a368aadcde0f8a375d27cad2914d78780d971"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_full]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c51717679b5e3402c55862569a874da56be688b"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e702bcfbac6e8ce829f904892446630269fc1fa871acd7bdefc63a34e317b4d7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a77d519d22bcc982dd7f784093d2021621252d4"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6cf37a410c8b7f14e1e935db6e27fdb2f098d817248456cf029c1ade2eb13edd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a700b234a83e7c5c0dbc4e8fb6198596249bb305"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "abb2898d62adcfc13202c4b2bf7ca684ac2a3306f37578f74546029fb8331934"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e1bac29256aa948401c05aa70c27d0ff8fbd9f0"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "048e0253eab852bc16a5f0ecbbf3c2b3874e1b1858bc959b929fd157fd4ccf48"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1736c7dcdbdac47a94e7b21921475ade369b8ecf"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "e85a3ac78ee3c31bccd2ac1020aa0e663f3356afb0b5dfb5a0786e7f8466f69c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03fa45976fa22de7452e7e1dcefcb36d7ff9cd24"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "94a5326d3237f21f156612ad519079d3bb384c7e81e5b89f0c49ddb37779f6c9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a1da829abeca050bdbd752045231752ef82c4b2"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "64490a3bd137a97cbf51f3d60d5031d5142a3be3941eba994076ad8efc3b3c01"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2375005e5269f6846e255ccce259ca9114c3a97c"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "24b95955b232f8722ded750fc0c32119b131b6b4eb97d3344d8c4f8d98630ab4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fc626ead488e59bc8944ed95dfa43441114c203"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "7658b0f1460ada5047394dae610c38bb73c6ce79c0b2cbdf46468152dbdf5854"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "d562fb0d212c389a6ab1005fd8723003599ed9e4"
os = "macos"

    [[LLVM_full.download]]
    sha256 = "dc1615780179cf1053d80608f6047d2dc85ed497654a1054d5127723c6bc2f7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2d300898d10c062f295d5a3581b0c5f6f660663"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "819de358a8cd65e57eefa6b8aa0cee9b6b6baa8b3058d834083318191f7e0a4f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f227e8cf75baee7675090c0e13ed177c2ca1cbe"
libc = "glibc"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "bd81fc3360ead6a645491e603d087f0cfba61b50a90338b443b2c9be4e38a884"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "473fb0c5e14341b27b08dad4ee40c1ddf5ea86bd"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "0f5efd37abd3f18e0f4c46bdabb73f6fdd107bade8704271f5c7e99a6de5ee11"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7abb14ab5cf21a52f9fee1015a5059daa14e884a"
libc = "musl"
os = "linux"

    [[LLVM_full.download]]
    sha256 = "6e3c4b698149be969363738dfc8e87d6e71340c616ce6a755facd389544974f0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full]]
arch = "x86_64"
git-tree-sha1 = "c34bdc5b501f6d69f9db2fbd74aa266f59c5341d"
os = "freebsd"

    [[LLVM_full.download]]
    sha256 = "598f6f0d7258770ad69465dc77c5309e76937602c329a2c6f0a8bf0340ebba58"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4a6e3503edcc7aa5fde08194bf86d80acc9392e"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0a60af6f263c80d421346ffd7293a68f8b53ae4714b81470f273ed3ba1fd6cc4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9a1c30a00d6980ba4693c022295df450ef34c80"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "0bbf3125006871c765d06638021beaddb52f007902ba9626944321014fdfafe7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/download/LLVM_full-v12.0.1+2/LLVM_full.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
